-- Start Bias
delete from StartBiasTerrains where CivilizationType = 'CIVILIZATION_CVS_BERBER';
delete from StartBiasFeatures where CivilizationType = 'CIVILIZATION_CVS_BERBER';
-- Traits
delete from TraitModifiers where TraitType = 'TRAIT_CIVILIZATION_CVS_BERBER_UA' or TraitType = 'TRAIT_LEADER_CVS_DIHYA_UA';
insert or replace into TraitModifiers
	(TraitType,								ModifierId)
values
	('TRAIT_CIVILIZATION_CVS_BERBER_UA',	'BERBER_AQUEDUCT_DISTRICT_ADJACENCY'),
	('TRAIT_CIVILIZATION_CVS_BERBER_UA',	'BERBER_AQUEDUCT_PRODUCTION'),
	('TRAIT_CIVILIZATION_CVS_BERBER_UA',	'BERBER_AQUEDUCT_BUILDING_FAITH_PURCHASE'),
	('TRAIT_LEADER_CVS_DIHYA_UA',			'DIHYA_MOVEMENT');
insert or replace into Modifiers
	(ModifierId,									ModifierType,														SubjectRequirementSetId)
values
	('BERBER_AQUEDUCT_DISTRICT_ADJACENCY',			'MODIFIER_PLAYER_CITIES_DISTRICT_ADJACENCY',						null),
	('BERBER_AQUEDUCT_PRODUCTION',					'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS',	'DISTRICT_IS_DISTRICT_AQUEDUCT_REQUIREMENTS'),
	('BERBER_AQUEDUCT_BUILDING_FAITH_PURCHASE',		'MODIFIER_PLAYER_CITIES_ENABLE_BUILDING_FAITH_PURCHASE',			null),
	('DIHYA_MOVEMENT',								'MODIFIER_PLAYER_UNITS_ADJUST_FRIENDLY_TERRITORY_START_MOVEMENT',	null);
insert or replace into ModifierArguments
	(ModifierId,									Name,					Value)
values
	('BERBER_AQUEDUCT_DISTRICT_ADJACENCY',			'DistrictType',			'DISTRICT_AQUEDUCT'),
	('BERBER_AQUEDUCT_DISTRICT_ADJACENCY',			'YieldType',			'YIELD_FOOD'),
	('BERBER_AQUEDUCT_DISTRICT_ADJACENCY',			'Amount',				1),
	('BERBER_AQUEDUCT_DISTRICT_ADJACENCY',			'Description',			'LOC_DISTRICT_FOOD'),
	('BERBER_AQUEDUCT_PRODUCTION',					'YieldTypeToMirror',	'YIELD_FOOD'),
	('BERBER_AQUEDUCT_PRODUCTION',					'YieldTypeToGrant',		'YIELD_PRODUCTION'),
	('BERBER_AQUEDUCT_BUILDING_FAITH_PURCHASE',		'DistrictType',			'DISTRICT_AQUEDUCT'),
	('DIHYA_MOVEMENT',								'Amount',				1);
insert or replace into TraitModifiers
	(TraitType,								ModifierId)
select 
	'TRAIT_CIVILIZATION_CVS_BERBER_UA',		'BERBER_' || DistrictType || '_CONSTRUCTION_SPEED'
from Districts where not RequiresPopulation or DistrictType = 'DISTRICT_PRESERVE';
insert or replace into Modifiers
	(ModifierId,											ModifierType)
select
	'BERBER_' || DistrictType || '_CONSTRUCTION_SPEED',		'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION'
from Districts where not RequiresPopulation  or DistrictType = 'DISTRICT_PRESERVE';
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
select
	'BERBER_' || DistrictType || '_CONSTRUCTION_SPEED',		'DistrictType',		DistrictType
from Districts where not RequiresPopulation or DistrictType = 'DISTRICT_PRESERVE';
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
select
	'BERBER_' || DistrictType || '_CONSTRUCTION_SPEED',		'Amount',			50
from Districts where not RequiresPopulation or DistrictType = 'DISTRICT_PRESERVE';
insert or replace into TraitModifiers
	(TraitType,								ModifierId)
select 
	'TRAIT_CIVILIZATION_CVS_BERBER_UA',		'BERBER_' || BuildingType || '_PURCHASE_CHEAPER'
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_AQUEDUCT';
insert or replace into Modifiers
	(ModifierId,											ModifierType)
select
	'BERBER_' || BuildingType || '_PURCHASE_CHEAPER',		'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_PURCHASE_COST'
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_AQUEDUCT';
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
select
	'BERBER_' || BuildingType || '_PURCHASE_CHEAPER',		'BuildingType',		BuildingType
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_AQUEDUCT';
insert or replace into ModifierArguments
	(ModifierId,											Name,				Value)
select
	'BERBER_' || BuildingType || '_PURCHASE_CHEAPER',		'Amount',			20
from HD_BuildingTiers where PrereqDistrict = 'DISTRICT_AQUEDUCT';
-- Unique Unit
update Units set Combat = 42, Cost = 90, Maintenance = 3 where UnitType = 'UNIT_CVS_BERBER_UU';
insert or replace into RequirementSetRequirements
	(RequirementSetId,								RequirementId)
values
	('REQSET_CVS_BERBER_UU_DEFENDING',				'RANGED_COMBAT_REQUIREMENTS'),
	('REQSET_CVS_BERBER_UU_DEFENDING_FRIENDLY',		'RANGED_COMBAT_REQUIREMENTS');
update ModifierArguments set Value = 7 where ModifierId = 'MODIFIER_CVS_BERBER_UU_DEFENDING_FRIENDLY' and Name = 'Amount';
-- Unique Improvement
update Improvements set TilesRequired = 1, SameAdjacentValid = 0, BuildInLine = 0, Workable = 0 where ImprovementType = 'IMPROVEMENT_CVS_BERBER_UI';
delete from Improvement_YieldChanges where ImprovementType = 'IMPROVEMENT_CVS_BERBER_UI';
delete from Improvement_BonusYieldChanges where ImprovementType = 'IMPROVEMENT_CVS_BERBER_UI';
delete from Improvement_Adjacencies where ImprovementType = 'IMPROVEMENT_CVS_BERBER_UI';
delete from TraitModifiers where TraitType = 'TRAIT_CIVILIZATION_IMPROVEMENT_CVS_BERBER_UI';
insert or replace into Improvement_ValidTerrains
	(ImprovementType,				TerrainType,				PrereqTech)
values
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_GRASS',			null),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_PLAINS',			null),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_TUNDRA',			null),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_SNOW',				null),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_GRASS_HILLS',		'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_PLAINS_HILLS',		'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_DESERT_HILLS',		'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_TUNDRA_HILLS',		'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'TERRAIN_SNOW_HILLS',		'TECH_IRON_WORKING');
insert or replace into Improvement_ValidFeatures
	(ImprovementType,				FeatureType,							PrereqTech)
values
	('IMPROVEMENT_CVS_BERBER_UI',	'FEATURE_FLOODPLAINS',					'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'FEATURE_FLOODPLAINS_GRASSLAND',		'TECH_IRON_WORKING'),
	('IMPROVEMENT_CVS_BERBER_UI',	'FEATURE_FLOODPLAINS_PLAINS',			'TECH_IRON_WORKING');
insert or replace into ImprovementModifiers
	(ImprovementType,					ModifierId)
values
	('IMPROVEMENT_CVS_BERBER_UI',		'BERBER_UI_HOUSING_EARLY'),
	('IMPROVEMENT_CVS_BERBER_UI',		'BERBER_UI_HOUSING_LATE'),
	('IMPROVEMENT_CVS_BERBER_UI',		'BERBER_UI_ADJACENT_FOOD'),
	('IMPROVEMENT_CVS_BERBER_UI',		'BERBER_UI_ADJACENT_PRODUCTION');
insert or replace into TraitModifiers
	(TraitType,											ModifierId)
values
	('TRAIT_CIVILIZATION_IMPROVEMENT_CVS_BERBER_UI',	'BERBER_AQUEDUCT_UI_ADJACENCY'),
	('TRAIT_CIVILIZATION_IMPROVEMENT_CVS_BERBER_UI',	'BERBER_INDUSTRIAL_UI_ADJACENCY');
insert or replace into Modifiers
	(ModifierId,						ModifierType,											OwnerRequirementSetId,							SubjectRequirementSetId)
values
	('BERBER_UI_HOUSING_EARLY',			'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_HOUSING',		'PLAYER_HAS_TECH_ENGINEERING_REQUIREMENTS',		null),
	('BERBER_UI_HOUSING_LATE',			'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_HOUSING',		'PLAYER_HAS_TECH_APPRENTICESHIP_REQUIREMENTS',	null),
	('BERBER_UI_ADJACENT_FOOD',			'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					null,											'PLOT_HAS_RESOURCE_AND_ADJACENT_TO_OWNER'),
	('BERBER_UI_ADJACENT_PRODUCTION',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',					'PLAYER_HAS_TECH_ENGINEERING_REQUIREMENTS',		'PLOT_HAS_RESOURCE_AND_ADJACENT_TO_OWNER'),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'MODIFIER_PLAYER_CITIES_IMPROVEMENT_ADJACENCY',			null,											null),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'MODIFIER_PLAYER_CITIES_IMPROVEMENT_ADJACENCY',			null,											null);
insert or replace into ModifierArguments
	(ModifierId,						Name,				Value)
values
	('BERBER_UI_HOUSING_EARLY',			'Amount',			1),
	('BERBER_UI_HOUSING_LATE',			'Amount',			1),
	('BERBER_UI_ADJACENT_FOOD',			'YieldType',		'YIELD_FOOD'),
	('BERBER_UI_ADJACENT_FOOD',			'Amount',			1),
	('BERBER_UI_ADJACENT_PRODUCTION',	'YieldType',		'YIELD_PRODUCTION'),
	('BERBER_UI_ADJACENT_PRODUCTION',	'Amount',			1),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'DistrictType',		'DISTRICT_AQUEDUCT'),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'ImprovementType',	'IMPROVEMENT_CVS_BERBER_UI'),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'YieldType',		'YIELD_FOOD'),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'Amount',			2),
	('BERBER_AQUEDUCT_UI_ADJACENCY',	'Description',		'LOC_BERBER_UI_FOOD'),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'DistrictType',		'DISTRICT_INDUSTRIAL_ZONE'),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'ImprovementType',	'IMPROVEMENT_CVS_BERBER_UI'),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'YieldType',		'YIELD_PRODUCTION'),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'Amount',			2),
	('BERBER_INDUSTRIAL_UI_ADJACENCY',	'Description',		'LOC_BERBER_UI_PRODUCTION');
insert or replace into RequirementSets
	(RequirementSetId,								RequirementSetType)
values
	('PLOT_HAS_RESOURCE_AND_ADJACENT_TO_OWNER',		'REQUIREMENTSET_TEST_ALL');
insert or replace into RequirementSetRequirements
	(RequirementSetId,								RequirementId)
values
	('PLOT_HAS_RESOURCE_AND_ADJACENT_TO_OWNER',		'ADJACENT_TO_OWNER'),
	('PLOT_HAS_RESOURCE_AND_ADJACENT_TO_OWNER',		'PLOT_HAS_RESOURCE_REQUIREMENTS');


delete from CivilizationTraits where CivilizationType = 'CIVILIZATION_CVS_BERBER' and TraitType = 'TRAIT_CIVILIZATION_CVS_BERBER_UU';
insert or ignore into LeaderTraits(LeaderType,TraitType) 
values ('LEADER_CVS_DIHYA','TRAIT_CIVILIZATION_UNIT_OTTOMAN_BARBARY_CORSAIR');

--城市
delete from CityNames where CivilizationType = 'CIVILIZATION_CVS_BERBER';
update CivilizationLeaders set CapitalName = 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CIRTA' where CivilizationType = 'CIVILIZATION_CVS_BERBER' and LeaderType = 'LEADER_CVS_MASINISSA';
update CivilizationLeaders set CapitalName = 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHENCHELA' where CivilizationType = 'CIVILIZATION_CVS_BERBER' and LeaderType = 'LEADER_CVS_DIHYA';
insert or replace into CityNames (ID, CivilizationType, CityName) values
(6951, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CIRTA'),
(6952, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHENCHELA'),
(6953, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MARRAKECH'),
(6954, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_FEZ'),
(6955, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ALGERS'),
(6956, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUNIS'),
(6957, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TLEMCEN'),
(6958, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAIROUAN'),
(6959, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ANNABA'),
(6960, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SIGA'),
(6961, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RUSSICADA'),
(6962, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIMGAD'),
(6963, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GAFSA'),
(6964, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SETIF'),
(6965, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THAGASTE'),
(6966, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TETOUAN'),
(6967, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TOUGGOURT'),
(6968, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DARALBAYDA'),
(6969, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TANGIER'),
(6970, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SAFI'),
(6971, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ORAN'),
(6972, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CEUTA'),
(6973, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAPES'),
(6974, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SABHA'),
(6975, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TRIPOLI'),
(6976, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SOUS'),
(6977, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MZAB'),
(6978, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEILILLA'),
(6979, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SALE'),
(6980, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RADAT'),
(6981, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEKNES'),
(6982, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_OUJDA'),
(6983, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHOURIBGA'),
(6984, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KENITRA'),
(6985, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BLIDA'),
(6986, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DJELFA'),
(6987, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THEVESTE'),
(6988, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BEJAIA'),
(6989, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIARET'),
(6990, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MOSTAGANEM'),
(6991, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TATAOUINE'),
(6992, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BAGAI'),
(6993, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MILEVUM'),
(6994, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ZARAI'),
(6995, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUBUNAE'),
(6996, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MACRI'),
(6997, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GEMELLAE'),
(6998, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEDEA'),
(6999, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_LAGHOUT'),
(7000, 'CIVILIZATION_CVS_BERBER', 'LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ERFOUD');