-- Warning: this file may be loaded twice! Consider using INSERT OR IGNORE to avoid foreign key problem.
-- Traits
delete from TraitModifiers where TraitType = 'TRAIT_LEADER_GEDEMO_CHARLEMAGNE1' or TraitType = 'TRAIT_LEADER_GEDEMO_KARLDERGROSSE1';
with T(TraitType) as (values ('TRAIT_LEADER_GEDEMO_CHARLEMAGNE1'), ('TRAIT_LEADER_GEDEMO_KARLDERGROSSE1')),
	M(ModifierId) as (values ('CHARLEMAGNE_CITY_CULTURE'), ('CHARLEMAGNE_CITY_SCIENCE'), ('CHARLEMAGNE_CITY_GOLD'),
		('CHARLEMAGNE_ALLOW_FOOD_PROJECT'), ('CHARLEMAGNE_ALLOW_FAITH_PROJECT'), ('CHARLEMAGNE_ALLOW_GOLD_PROJECT'),
		('CHARLEMAGNE_ALLOW_CULTURE_PROJECT'), ('CHARLEMAGNE_ALLOW_SCIENCE_PROJECT'))
insert or ignore into TraitModifiers
	(TraitType,		ModifierId)
select
	TraitType,		ModifierId
from (T cross join M) where TraitType in (select TraitType from Traits);

insert or ignore into UniqueProjects_HD
	(ProjectType,										ModifierId,														LeaderType)
values
	('PROJECT_CHALEMAGNE_FOOD',			'CHARLEMAGNE_ALLOW_FOOD_PROJECT',			'LEADER_GEDEMO_KARLDERGROSSE1'),
	('PROJECT_CHALEMAGNE_FAITH',		'CHARLEMAGNE_ALLOW_FAITH_PROJECT',		'LEADER_GEDEMO_KARLDERGROSSE1'),
	('PROJECT_CHALEMAGNE_GOLD',			'CHARLEMAGNE_ALLOW_GOLD_PROJECT',			'LEADER_GEDEMO_KARLDERGROSSE1'),
	('PROJECT_CHALEMAGNE_CULTURE',	'CHARLEMAGNE_ALLOW_CULTURE_PROJECT',	'LEADER_GEDEMO_KARLDERGROSSE1'),
	('PROJECT_CHALEMAGNE_SCIENCE',	'CHARLEMAGNE_ALLOW_SCIENCE_PROJECT',	'LEADER_GEDEMO_KARLDERGROSSE1'),
	('PROJECT_CHALEMAGNE_FOOD',			'CHARLEMAGNE_ALLOW_FOOD_PROJECT',			'LEADER_GEDEMO_CHARLEMAGNE1'),
	('PROJECT_CHALEMAGNE_FAITH',		'CHARLEMAGNE_ALLOW_FAITH_PROJECT',		'LEADER_GEDEMO_CHARLEMAGNE1'),
	('PROJECT_CHALEMAGNE_GOLD',			'CHARLEMAGNE_ALLOW_GOLD_PROJECT',			'LEADER_GEDEMO_CHARLEMAGNE1'),
	('PROJECT_CHALEMAGNE_CULTURE',	'CHARLEMAGNE_ALLOW_CULTURE_PROJECT',	'LEADER_GEDEMO_CHARLEMAGNE1'),
	('PROJECT_CHALEMAGNE_SCIENCE',	'CHARLEMAGNE_ALLOW_SCIENCE_PROJECT',	'LEADER_GEDEMO_CHARLEMAGNE1');

insert or ignore into Modifiers
	(ModifierId,							ModifierType,													SubjectRequirementSetId)
values
	('CHARLEMAGNE_CITY_CULTURE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',		'CITY_HAS_7_POPULATION'),
	('CHARLEMAGNE_CITY_SCIENCE',			'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',		'CITY_HAS_7_POPULATION'),
	('CHARLEMAGNE_CITY_GOLD',				'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_PER_POPULATION',		'CITY_HAS_7_POPULATION'),
	('CHARLEMAGNE_ALLOW_FOOD_PROJECT',		'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',						null),
	('CHARLEMAGNE_ALLOW_FAITH_PROJECT',		'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',						null),
	('CHARLEMAGNE_ALLOW_GOLD_PROJECT',		'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',						null),
	('CHARLEMAGNE_ALLOW_CULTURE_PROJECT',	'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',						null),
	('CHARLEMAGNE_ALLOW_SCIENCE_PROJECT',	'MODIFIER_PLAYER_ALLOW_PROJECT_CATHERINE',						null),
	('CHARLEMAGNE_FREE_PALADIN_FRANCE',		'MODIFIER_CAPITAL_CITY_GRANT_UNIT_IN_CITY',						null),
	('CHARLEMAGNE_FREE_PALADIN_GERMANY',	'MODIFIER_CAPITAL_CITY_GRANT_UNIT_IN_CITY',						null);
insert or ignore into ModifierArguments
	(ModifierId,							Name,			Value)
values
	('CHARLEMAGNE_CITY_CULTURE',			'YieldType',	'YIELD_CULTURE'),
	('CHARLEMAGNE_CITY_CULTURE',			'Amount',		0.5),
	('CHARLEMAGNE_CITY_SCIENCE',			'YieldType',	'YIELD_SCIENCE'),
	('CHARLEMAGNE_CITY_SCIENCE',			'Amount',		0.5),
	('CHARLEMAGNE_CITY_GOLD',				'YieldType',	'YIELD_GOLD'),
	('CHARLEMAGNE_CITY_GOLD',				'Amount',		2),
	('CHARLEMAGNE_ALLOW_FOOD_PROJECT',		'ProjectType',	'PROJECT_CHALEMAGNE_FOOD'),
	('CHARLEMAGNE_ALLOW_FAITH_PROJECT',		'ProjectType',	'PROJECT_CHALEMAGNE_FAITH'),
	('CHARLEMAGNE_ALLOW_GOLD_PROJECT',		'ProjectType',	'PROJECT_CHALEMAGNE_GOLD'),
	('CHARLEMAGNE_ALLOW_CULTURE_PROJECT',	'ProjectType',	'PROJECT_CHALEMAGNE_CULTURE'),
	('CHARLEMAGNE_ALLOW_SCIENCE_PROJECT',	'ProjectType',	'PROJECT_CHALEMAGNE_SCIENCE'),
	('CHARLEMAGNE_FREE_PALADIN_FRANCE',		'UnitType',		'UNIT_GEDEMO_PALADIN'),
	('CHARLEMAGNE_FREE_PALADIN_FRANCE',		'Amount',		1),
	('CHARLEMAGNE_FREE_PALADIN_GERMANY',	'UnitType',		'UNIT_GEDEMO_GPALADIN'),
	('CHARLEMAGNE_FREE_PALADIN_GERMANY',	'Amount',		1);
-- Projects
insert or replace into Types
	(Type,							Kind)
values
	('PROJECT_CHALEMAGNE_FOOD',		'KIND_PROJECT'),
	('PROJECT_CHALEMAGNE_FAITH',	'KIND_PROJECT'),
	('PROJECT_CHALEMAGNE_GOLD',		'KIND_PROJECT'),
	('PROJECT_CHALEMAGNE_CULTURE',	'KIND_PROJECT'),
	('PROJECT_CHALEMAGNE_SCIENCE',	'KIND_PROJECT');
insert or replace into Projects
	(ProjectType,					Name,									ShortName,								Description,	Cost,	UnlocksFromEffect)
values
	('PROJECT_CHALEMAGNE_FOOD',		'LOC_PROJECT_CHALEMAGNE_FOOD_NAME',		'LOC_PROJECT_CHALEMAGNE_FOOD_NAME',		'',				9999,	1),
	('PROJECT_CHALEMAGNE_FAITH',	'LOC_PROJECT_CHALEMAGNE_FAITH_NAME',	'LOC_PROJECT_CHALEMAGNE_FAITH_NAME',	'',				9999,	1),
	('PROJECT_CHALEMAGNE_GOLD',		'LOC_PROJECT_CHALEMAGNE_GOLD_NAME',		'LOC_PROJECT_CHALEMAGNE_GOLD_NAME',		'',				9999,	1),
	('PROJECT_CHALEMAGNE_CULTURE',	'LOC_PROJECT_CHALEMAGNE_CULTURE_NAME',	'LOC_PROJECT_CHALEMAGNE_CULTURE_NAME',	'',				9999,	1),
	('PROJECT_CHALEMAGNE_SCIENCE',	'LOC_PROJECT_CHALEMAGNE_SCIENCE_NAME',	'LOC_PROJECT_CHALEMAGNE_SCIENCE_NAME',	'',				9999,	1);
insert or replace into Project_YieldConversions
	(ProjectType,					YieldType,			PercentOfProductionRate)
values
	('PROJECT_CHALEMAGNE_FOOD',		'YIELD_FOOD',		66),--锤转粮百分比
	('PROJECT_CHALEMAGNE_FAITH',	'YIELD_FAITH',		133),--锤转鸽百分比
	('PROJECT_CHALEMAGNE_GOLD',		'YIELD_GOLD',		200),--锤转金百分比
	('PROJECT_CHALEMAGNE_CULTURE',	'YIELD_CULTURE',	66),--锤转琴百分比
	('PROJECT_CHALEMAGNE_SCIENCE',	'YIELD_SCIENCE',	66);--锤转瓶百分比
-- Units
update Units set BaseSightRange = 2, Combat = 45, Cost = 80, BaseMoves = 4, PrereqTech = null, PrereqCivic = 'CIVIC_LITERARY_TRADITION_HD', StrategicResource = 'RESOURCE_HORSES'
	where UnitType = 'UNIT_GEDEMO_PALADIN' or UnitType = 'UNIT_GEDEMO_GPALADIN';
insert or replace into Units_XP2
	(UnitType,	ResourceCost,	ResourceMaintenanceType,	ResourceMaintenanceAmount)
select
	UnitType,	5,				'RESOURCE_IRON',			1
from Units where UnitType = 'UNIT_GEDEMO_PALADIN' or UnitType = 'UNIT_GEDEMO_GPALADIN';
-- Does not replace Knight since France STUU does.
delete from UnitReplaces where CivUniqueUnitType = 'UNIT_GEDEMO_PALADIN' or CivUniqueUnitType = 'UNIT_GEDEMO_GPALADIN';
insert or replace into UnitUpgrades
	(Unit,		UpgradeUnit)
select
	UnitType,	'UNIT_CUIRASSIER'
from Units where UnitType = 'UNIT_GEDEMO_PALADIN' or UnitType = 'UNIT_GEDEMO_GPALADIN';
-- Ability
delete from TypeTags where Tag = 'CLASS_VARU' and (Type = 'UNIT_GEDEMO_PALADIN' or Type = 'UNIT_GEDEMO_GPALADIN');
insert or ignore into Types
	(Type,											Kind)
values
	('ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'KIND_ABILITY');
insert or ignore into UnitAbilities
	(UnitAbilityType,								Name,													Description)
values
	('ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'LOC_ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS_NAME',	'LOC_ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS_DESCRIPTION');
insert or ignore into Tags
	(Tag,											Vocabulary)
values
	('CLASS_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',		'ABILITY_CLASS');
insert or ignore into TypeTags
	(Type,											Tag)
values
	('ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'CLASS_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS');
insert or ignore into TypeTags
	(Type,											Tag)
select
	UnitType,										'CLASS_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS'
from Units where UnitType = 'UNIT_GEDEMO_PALADIN' or UnitType = 'UNIT_GEDEMO_GPALADIN';
insert or ignore into UnitAbilityModifiers
	(UnitAbilityType,								ModifierId)
values
	('ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'CHARLEMAGNE_GAIN_CULTURE_ON_KILLS');
insert or ignore into Modifiers
	(ModifierId,							ModifierType)
values
	('CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'MODIFIER_UNIT_ADJUST_POST_COMBAT_YIELD');
insert or ignore into ModifierArguments
	(ModifierId,							Name,						Value)
values
	('CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'YieldType',				'YIELD_CULTURE'),
	('CHARLEMAGNE_GAIN_CULTURE_ON_KILLS',	'PercentDefeatedStrength',	50);