delete from StartBiasFeatures where CivilizationType = 'CIVILIZATION_SUK_ICELAND' and FeatureType = 'FEATURE_FOREST';
delete from DistrictModifiers where DistrictType = 'DISTRICT_SUK_TORFBAEIR';
update Districts set PrereqTech = NULL, PrereqCivic = 'CIVIC_EARLY_EMPIRE' where DistrictType = 'DISTRICT_SUK_TORFBAEIR';
update ModifierArguments set Value = 2 where ModifierId = 'SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_WRITING' and Name = 'Value';
delete from GreatPersonIndividualActionModifiers where GreatPersonIndividualType = 'GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON';
insert or replace into StartBiasFeatures
	(CivilizationType,					FeatureType,				Tier)
values
	('CIVILIZATION_SUK_ICELAND',		'FEATURE_VOLCANIC_SOIL',	2);

insert or replace into TraitModifiers
	(TraitType,											Modifierid)
values
	('TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS',			'SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT'),
	('TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS',	'SUK_ICELAND_SAGAS_AMENITY_VOLCANIC_SOIL'),
	('TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS',	'SUK_SAGAS_OF_THE_ICELANDERS_APPEAL_FEATURE_VOLCANO_SOIL');

insert or replace into DistrictModifiers
	(DistrictType,										ModifierId)
values
	('DISTRICT_SUK_TORFBAEIR',							'SUK_TORFBAEIR_ADDAMENITIES');
--	('DISTRICT_SUK_TORFBAEIR',							'SUK_TORFBAEIR_GROWTH_RATE');

insert or replace into GreatPersonIndividualActionModifiers
	(GreatPersonIndividualType,											ModifierId,																AttachmentTargetType)
values
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFLJOTR',					'SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFLJOTR',					'SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_WRITING_HD',				'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',	'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',		'GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER'),
	('GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON',		'SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_PLAYER');

insert or replace into Modifiers
	(ModifierId,																ModifierType,												Runonce,	Permanent,	SubjectRequirementSetId)
values
	('SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',								'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',						0,			0,			NULL),
	('SETTLER_SHARED_MOVEMENT',													'MODIFIER_UNIT_ADJUST_ESCORT_MOBILITY',						0,			1,			NULL),
	('SUK_ICELAND_SAGAS_AMENITY_VOLCANIC_SOIL',									'MODIFIER_PLAYER_CITIES_ADJUST_TRAIT_AMENITY',				0,			0,			'HD_CITY_HAS_FEATURE_VOLCANIC_SOIL'),
	('SUK_SAGAS_OF_THE_ICELANDERS_APPEAL_FEATURE_VOLCANO_SOIL',					'MODIFIER_PLAYER_CITIES_ADJUST_FEATURE_APPEAL_MODIFIER',	0,			0,			NULL),
	('SUK_TORFBAEIR_ADDAMENITIES',												'MODIFIER_PLAYER_DISTRICT_ADJUST_DISTRICT_AMENITY',			0,			0,			'PLOT_HAS_VOLCANIC_SOIL_OR_GEOTHERMAL_FIISSURE_REQUIREMENTS'),
	('SUK_TORFBAEIR_GROWTH_RATE',												'MODIFIER_SINGLE_CITY_ADJUST_CITY_GROWTH',					0,			0,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_WRITING_HD',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS',		0,			1,			'SUK_IS_CHARMING_TORFBAEIR'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL',	0,			1,			NULL);
insert or replace into ModifierArguments
	(ModifierId,																Name,						Value)
values
	('SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',								'AbilityType',				'ABILITY_SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT'),
	('SETTLER_SHARED_MOVEMENT',													'EscortMobility',			1),
	('SUK_ICELAND_SAGAS_AMENITY_VOLCANIC_SOIL',									'Amount',					1),
	('SUK_SAGAS_OF_THE_ICELANDERS_APPEAL_FEATURE_VOLCANO_SOIL',					'Amount',					1),
	('SUK_SAGAS_OF_THE_ICELANDERS_APPEAL_FEATURE_VOLCANO_SOIL',					'FeatureType',				'FEATURE_VOLCANIC_SOIL'),
	('SUK_TORFBAEIR_ADDAMENITIES',												'Amount',					1),
	('SUK_TORFBAEIR_GROWTH_RATE',												'Amount',					10),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'DistrictType',				'DISTRICT_SUK_TORFBAEIR'),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'RequiredAppeal',			2),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'YieldChange',				2),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_CULTURE_HD',				'YieldType',				'YIELD_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_WRITING_HD',				'Amount',					2),
	('SUK_GREATPERSON_LAWSPEAKER_ULFLJOTR_TORFBAEIR_WRITING_HD',				'GreatPersonClassType',		'GREAT_PERSON_CLASS_WRITER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'RequiredAppeal',			2),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',			'YieldType',				'YIELD_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_FOOD'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'RequiredAppeal',			2),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD',			'YieldType',				'YIELD_FOOD'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_PRODUCTION'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'RequiredAppeal',			2),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION',		'YieldType',				'YIELD_PRODUCTION'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'RequiredAppeal',			4),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE_HD',		'YieldType',				'YIELD_CULTURE'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_FOOD'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'RequiredAppeal',			4),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_FOOD_HD',			'YieldType',				'YIELD_FOOD'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'Description',				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_PRODUCTION'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'DistrictType',				'DISTRICT_CITY_CENTER'),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'RequiredAppeal',			4),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'YieldChange',				1),
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_PRODUCTION_HD',	'YieldType',				'YIELD_PRODUCTION');

insert or replace into ModifierStrings
	(ModifierId,																		Context,					Text)
values
	('SUK_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_TORFBAEIR_CULTURE',					'Summary',					'LOC_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_ACTIVE');
insert or replace into Types
	(Type,														Kind)
values
	('ABILITY_SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',		'KIND_ABILITY');

insert or replace into TypeTags
	(Type,														Tag)
values
	('ABILITY_SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',		'CLASS_RECON');

insert or replace into UnitAbilities
	(UnitAbilityType,											Name,	Description,	Inactive,	Permanent)
values
	('ABILITY_SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',		NULL,	NULL,			1,			1);

insert or replace into UnitAbilityModifiers
	(UnitAbilityType,											ModifierId)
values
	('ABILITY_SUK_SAGAS_OF_THE_ICELANDERS_SHARED_MOVEMENT',		'SETTLER_SHARED_MOVEMENT');

insert or ignore into RequirementSets
	(RequirementSetId,													RequirementSetType)
values
	('PLOT_HAS_VOLCANIC_SOIL_OR_GEOTHERMAL_FIISSURE_REQUIREMENTS',		'REQUIREMENTSET_TEST_ANY'),
	('SUK_IS_CHARMING_TORFBAEIR',										'REQUIREMENTSET_TEST_ALL');

insert or ignore into RequirementSetRequirements
	(RequirementSetId,													RequirementId)
values
	('PLOT_HAS_VOLCANIC_SOIL_OR_GEOTHERMAL_FIISSURE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_GEOTHERMAL_FIISSURE'),
	('PLOT_HAS_VOLCANIC_SOIL_OR_GEOTHERMAL_FIISSURE_REQUIREMENTS',		'REQUIRES_PLOT_HAS_VOLCANIC_SOIL'),
	('SUK_IS_CHARMING_TORFBAEIR',										'REQUIRES_DISTRICT_IS_AQUEDUCT'),
	('SUK_IS_CHARMING_TORFBAEIR',										'REQUIRES_PLOT_CHARMING_APPEAL');

--海狗uu
insert or replace into Types
	(Type,								Kind)
values
	('UNIT_KNARR',						'KIND_UNIT'),
	('TRAIT_CIVILIZATION_UNIT_KNARR',	'KIND_TRAIT');
insert or replace into Traits
	(TraitType,								Name,					Description,						InternalOnly)
values
	('TRAIT_CIVILIZATION_UNIT_KNARR',		'LOC_UNIT_KNARR_NAME',	'LOC_UNIT_KNARR_DESCRIPTION',		0);
insert or replace into CivilizationTraits
	(CivilizationType,						TraitType)
values
	('CIVILIZATION_SUK_ICELAND',			'TRAIT_CIVILIZATION_UNIT_KNARR');
insert or replace into Units
	(UnitType,					Name,							Description,							TraitType,								PrereqTech,		MandatoryObsoleteTech,
	BaseSightRange,	BaseMoves,	Combat,	RangedCombat,	Range,	Cost,	ZoneOfControl,	PurchaseYield,	Domain,
	FormationClass,				PromotionClass,					PseudoYieldType,						AdvisorType)
values
	('UNIT_KNARR',				'LOC_UNIT_KNARR_NAME',			'LOC_UNIT_KNARR_DESCRIPTION',			'TRAIT_CIVILIZATION_UNIT_KNARR',		NULL,			'TECH_COMPASS_HD',
	2,				3,			15,		10,				1,		30,    1,				'YIELD_GOLD',	'DOMAIN_SEA',
	'FORMATION_CLASS_NAVAL',	'PROMOTION_CLASS_RECON',		'PSEUDOYIELD_UNIT_NAVAL_COMBAT',		'ADVISOR_CONQUEST');
insert or replace into UnitUpgrades
	(Unit,						UpgradeUnit)
values
	('UNIT_KNARR',				'UNIT_DL_MEDIEVAL_PIRATE');
insert or replace into UnitReplaces
	(CivUniqueUnitType,			ReplacesUnitType)
values
	('UNIT_KNARR',				'UNIT_ANCIENT_SEADOG');
insert or replace into TypeTags
	(Type,						Tag)
values
	('UNIT_KNARR',				'CLASS_NAVAL_RAIDER'),
	('UNIT_KNARR',				'CLASS_NAVAL_RANGED'),
	('UNIT_KNARR',				'CLASS_STEALTH'),
	('UNIT_KNARR',				'CLASS_REVEAL_STEALTH'),
	('UNIT_KNARR',				'CLASS_SEADOG'),
	('UNIT_KNARR',				'CLASS_RECON');
insert or ignore into UnitAiInfos
	(UnitType,					AiType)
values
	('UNIT_KNARR',				'UNITAI_COMBAT'),
	('UNIT_KNARR',				'UNITTYPE_RANGED'),
	('UNIT_KNARR',				'UNITTYPE_NAVAL');

insert or replace into MomentIllustrations
	(MomentIllustrationType, 					MomentDataType,				GameDataType,						Texture)
values
	('MOMENT_ILLUSTRATION_UNIQUE_UNIT', 		'MOMENT_DATA_UNIT',			'UNIT_KNARR',						'Moment_UniqueUnit_Norway_Longship.dds');
delete from AppealHousingChanges where DistrictType = 'DISTRICT_SUK_TORFBAEIR';
insert or replace into AppealHousingChanges
	(DistrictType,							MinimumValue,	AppealChange,	Description)
values
	('DISTRICT_SUK_TORFBAEIR',				-100,			0,				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BASE'),
	('DISTRICT_SUK_TORFBAEIR',				4,				2,				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BREATHTAKING'),
	('DISTRICT_SUK_TORFBAEIR',				2,				1,				'LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_CHARMING');
--移除冰岛基础1粮
update Districts set Housing = 2 where DistrictType = 'DISTRICT_SUK_TORFBAEIR';