-- New Leader
insert or replace into Types
	(Type,										Kind)
values
	('LEADER_NEBUCHADNEZZAR_II',				'KIND_LEADER'),
	('TRAIT_HANGING_GARDENS',					'KIND_TRAIT'),
	('TRAIT_AGENDA_BABYLONIAN_CAPTIVITY',		'KIND_TRAIT');
insert or replace into CivilizationLeaders
	(CivilizationType,				LeaderType,					CapitalName)
values
	('CIVILIZATION_BABYLON_STK',	'LEADER_NEBUCHADNEZZAR_II',	'LOC_CITY_NAME_BABYLON_STK');
insert or replace into Leaders
	(LeaderType,					Name,									InheritFrom)
values
	('LEADER_NEBUCHADNEZZAR_II',	'LOC_LEADER_NEBUCHADNEZZAR_II_NAME',	'LEADER_DEFAULT');
-- Traits
insert or replace into GlobalParameters
	(Name,									Value)
values
	('NEBUCHADNEZZAR_GOLD_PER_POPULATION',	30);
insert or replace into LeaderTraits
	(LeaderType,	 				TraitType)
values
	('LEADER_NEBUCHADNEZZAR_II',	'TRAIT_HANGING_GARDENS');
insert or replace into Traits
	(TraitType,					Name,								Description)
values
	('TRAIT_HANGING_GARDENS',	'LOC_TRAIT_HANGING_GARDENS_NAME',	'LOC_TRAIT_HANGING_GARDENS_DESCRIPTION');
insert or replace into TraitModifiers
	(TraitType,					ModifierId)
values
	('TRAIT_HANGING_GARDENS',	'TRAIT_HANGING_GARDENS_CAPTURED_CITY_WONDER_PRODUCTION_ATTACH'),
--	('TRAIT_HANGING_GARDENS',	'TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION_ATTACH'),
--	('TRAIT_HANGING_GARDENS',	'TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD_ATTACH'),
	('TRAIT_HANGING_GARDENS',	'TRAIT_HANGING_GARDENS_DISTRICT_PILLAGE'),
	('TRAIT_HANGING_GARDENS',	'TRAIT_HANGING_GARDENS_IMPROVEMENT_PILLAGE');
insert or replace into Modifiers
	(ModifierId,														ModifierType,										SubjectRequirementSetId,	SubjectStackLimit)
values
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_WONDER_PRODUCTION_ATTACH',	'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',			'CITY_WAS_NOT_FOUNDED',		null),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_WONDER_PRODUCTION',			'MODIFIER_PLAYER_CITIES_ADJUST_WONDER_PRODUCTION',	null,						null),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION_ATTACH',			'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',			'CITY_WAS_NOT_FOUNDED',		null),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION',					'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',	'CITY_WAS_FOUNDED',			null),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD_ATTACH',					'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',			'CITY_WAS_NOT_FOUNDED',		null),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD',						'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE',	'CITY_WAS_FOUNDED',			null),
	('TRAIT_HANGING_GARDENS_DISTRICT_PILLAGE',							'MODIFIER_PLAYER_ADJUST_DISTRICT_PILLAGE',			null,						null),
	('TRAIT_HANGING_GARDENS_IMPROVEMENT_PILLAGE',						'MODIFIER_PLAYER_ADJUST_IMPROVEMENT_PILLAGE',		null,						null);
insert or replace into ModifierArguments
	(ModifierId,														Name,			Value)
values
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_WONDER_PRODUCTION_ATTACH',	'ModifierId',	'TRAIT_CAPTURED_CITY_WONDER_PRODUCTION'),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_WONDER_PRODUCTION',			'Amount',		5),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION_ATTACH',			'ModifierId',	'TRAIT_CAPTURED_CITY_PRODUCTION'),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION',					'YieldType',	'YIELD_PRODUCTION'),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_PRODUCTION',					'Amount',		1),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD_ATTACH',					'ModifierId',	'TRAIT_CAPTURED_CITY_FOOD'),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD',						'YieldType',	'YIELD_FOOD'),
	('TRAIT_HANGING_GARDENS_CAPTURED_CITY_FOOD',						'Amount',		1),
	('TRAIT_HANGING_GARDENS_DISTRICT_PILLAGE',							'Amount',		50),
	('TRAIT_HANGING_GARDENS_IMPROVEMENT_PILLAGE',						'Amount',		50);
-- Agenda
insert or replace into HistoricalAgendas
	(LeaderType,					AgendaType)
values
	('LEADER_NEBUCHADNEZZAR_II',	'AGENDA_BABYLONIAN_CAPTIVITY');
insert or replace into Agendas
	(AgendaType,						Name,										Description)
values
	('AGENDA_BABYLONIAN_CAPTIVITY',		'LOC_AGENDA_BABYLONIAN_CAPTIVITY_NAME',		'LOC_AGENDA_BABYLONIAN_CAPTIVITY_DESCRIPTION');
insert or replace into AgendaTraits
	(AgendaType,						TraitType)
values
	('AGENDA_BABYLONIAN_CAPTIVITY',		'TRAIT_AGENDA_BABYLONIAN_CAPTIVITY');
insert or replace into Traits
	(TraitType,								Name,				Description)
values
	('TRAIT_AGENDA_BABYLONIAN_CAPTIVITY',	'LOC_PLACEHOLDER',	'LOC_PLACEHOLDER');
insert or replace into TraitModifiers
	(TraitType,								ModifierId)
values
	('TRAIT_AGENDA_BABYLONIAN_CAPTIVITY',	'BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE'),
	('TRAIT_AGENDA_BABYLONIAN_CAPTIVITY',	'BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY');
insert or replace into Modifiers
	(ModifierId,											ModifierType,									OwnerRequirementSetId,	SubjectRequirementSetId)
values
	('BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE',	'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',	'ON_TURN_STARTED',		'PLAYER_AT_WAR_AND_HIGH_SCIENCE'),
	('BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY',	'MODIFIER_PLAYER_DIPLOMACY_SIMPLE_MODIFIER',	'ON_TURN_STARTED',		'PLAYER_WONDER_AND_LOW_MILITARY');
insert or replace into ModifierArguments
	(ModifierId,											Name,							Value)
values
	('BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE',	'InitialValue',					12),
	('BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE',	'SimpleModifierDescription',	'LOC_DIPLO_MODIFIER_BABYLONIAN_CAPTIVITY_POSITIVE'),
	('BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE',	'StatementKey',					'LOC_DIPLO_KUDO_LEADER_NEBUCHADNEZZAR_II_REASON_ANY'),
	('BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY',	'InitialValue',					-8),
	('BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY',	'SimpleModifierDescription',	'LOC_DIPLO_MODIFIER_BABYLONIAN_CAPTIVITY_NEGATIVE'),
	('BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY',	'StatementKey',					'LOC_DIPLO_WARNING_LEADER_NEBUCHADNEZZAR_II_REASON_ANY');
insert or replace into ModifierStrings
	(ModifierId,											Context,	Text)
values
	('BABYLONIAN_CAPTIVITY_LIKES_AT_WAR_AND_HIGH_SCIENCE',	'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL'),
	('BABYLONIAN_CAPTIVITY_HATES_WONDER_AND_LOW_MILITARY',	'Sample',	'LOC_TOOLTIP_SAMPLE_DIPLOMACY_ALL');
insert or replace into RequirementSets
	(RequirementSetId,					RequirementSetType)
values
	('PLAYER_AT_WAR_AND_HIGH_SCIENCE',	'REQUIREMENTSET_TEST_ALL'),
	('PLAYER_WONDER_AND_LOW_MILITARY',	'REQUIREMENTSET_TEST_ALL');
insert or replace into RequirementSetRequirements
	(RequirementSetId,					RequirementId)
values
	('PLAYER_AT_WAR_AND_HIGH_SCIENCE',	'REQUIRES_MET_10_TURNS_AGO'),
	('PLAYER_AT_WAR_AND_HIGH_SCIENCE',	'REQUIRES_PLAYER_AT_WAR_WITH_ANY_MAJOR'),
	('PLAYER_AT_WAR_AND_HIGH_SCIENCE',	'REQUIRES_HAS_HIGH_SCIENCE'),
	('PLAYER_WONDER_AND_LOW_MILITARY',	'REQUIRES_MET_10_TURNS_AGO'),
	('PLAYER_WONDER_AND_LOW_MILITARY',	'REQUIRES_LEADS_WONDERS'),
	('PLAYER_WONDER_AND_LOW_MILITARY',	'REQUIRES_HAS_LOW_STANDING_ARMY');
-- Art
insert or replace into LoadingInfo
	(LeaderType,					ForegroundImage,						BackgroundImage)
values
	('LEADER_NEBUCHADNEZZAR_II',	'NEBUCHADNEZZAR_II_FOREGROUND.dds',		'LEADER_HAMMURABI_BACKGROUND');
insert or replace into DiplomacyInfo
	(Type,				BackgroundImage)
values
	('LEADER_NEBUCHADNEZZAR_II',	'LEADER_HAMMURABI_BACKGROUND');
-- Religion
insert or replace into FavoredReligions
	(LeaderType,					ReligionType)
select
	'LEADER_NEBUCHADNEZZAR_II',		'RELIGION_CHALDAENISM'
where exists (select ReligionType from Religions where ReligionType = 'RELIGION_CHALDAENISM');