-- Rename type to disable lua script
update Types set Type = 'TRAIT_LEADER_LEU_PACAL_HD' where Type = 'TRAIT_LEADER_LEU_PACAL';
-- Science & Fait burst Amount
insert or replace into GlobalParameters
	(Name,									Value)
values
	('PACAL_SACRIFICE_FAITH_AMOUNT',		30),
	('PACAL_SACRIFICE_CULTURE_AMOUNT',		10),
	('PACAL_CONQUERED_MULTIPLIER',			3);
-- Trait
delete from TraitModifiers where TraitType = 'TRAIT_LEADER_LEU_PACAL_HD' and ModifierId = 'LEU_PACAL_FARM_PRODUCTION_ATTACH';
insert or replace into TraitModifiers
	(TraitType,						ModifierId)
values
	('TRAIT_LEADER_LEU_PACAL_HD',	'TRAIT_PACAL_ADJUST_HOUSING'),
	('TRAIT_LEADER_LEU_PACAL_HD',	'TRAIT_PACAL_ALLOW_SACRIFICE'),
	('TRAIT_LEADER_LEU_PACAL_HD',	'TRAIT_PACAL_BONUS_PRODUCTION'),
	('TRAIT_LEADER_LEU_PACAL_HD',	'TRAIT_PACAL_LUXURY_CULTURE');
insert or replace into Modifiers
	(ModifierId,								ModifierType,									SubjectRequirementSetId)
values
	('TRAIT_PACAL_ADJUST_HOUSING',				'MODIFIER_PLAYER_CITIES_ADJUST_WATER_HOUSING',	'HD_PLOT_ON_OR_ADJACENT_TO_LUXURY'),
	('TRAIT_PACAL_ALLOW_SACRIFICE',				'MODIFIER_PLAYER_ALLOW_PROJECT',		null),
	('TRAIT_PACAL_BONUS_PRODUCTION',			'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',	'DISTRICT_IS_DISTRICT_OBSERVATORY_REQUIREMENTS'),
	('TRAIT_PACAL_LUXURY_CULTURE',				'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',	'DISTRICT_IS_DISTRICT_OBSERVATORY_REQUIREMENTS'),
	('TRAIT_PACAL_BONUS_PRODUCTION_MODIFIER',	'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'REQUIRES_PLOT_HAS_BONUS_AND_ADJACENT_TO_OWNER'),
	('TRAIT_PACAL_LUXURY_CULTURE_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'REQUIRES_PLOT_HAS_LUXURY_AND_ADJACENT_TO_OWNER');
insert or replace into ModifierArguments
	(ModifierId,								Name,			Value)
values
	('TRAIT_PACAL_ADJUST_HOUSING',				'Amount',		2),
	('TRAIT_PACAL_ALLOW_SACRIFICE',				'ProjectType',	'PROJECT_SACRIFICE'),
	('TRAIT_PACAL_BONUS_PRODUCTION',			'ModifierId',	'TRAIT_PACAL_BONUS_PRODUCTION_MODIFIER'),
	('TRAIT_PACAL_LUXURY_CULTURE',				'ModifierId',	'TRAIT_PACAL_LUXURY_CULTURE_MODIFIER'),
	('TRAIT_PACAL_BONUS_PRODUCTION_MODIFIER',	'Amount',		1),
	('TRAIT_PACAL_BONUS_PRODUCTION_MODIFIER',	'YieldType',	'YIELD_PRODUCTION'),
	('TRAIT_PACAL_LUXURY_CULTURE_MODIFIER',		'Amount',		1),
	('TRAIT_PACAL_LUXURY_CULTURE_MODIFIER',		'YieldType',	'YIELD_CULTURE');
-- Unique Project
insert or replace into Types
	(Type,							Kind)
values
	('PROJECT_SACRIFICE',			'KIND_PROJECT');
insert or replace into Projects
	(ProjectType,			Name,							ShortName,						Description,							Cost,	UnlocksFromEffect)
values
	('PROJECT_SACRIFICE',	'LOC_PROJECT_SACRIFICE_NAME',	'LOC_PROJECT_SACRIFICE_NAME',	'LOC_PROJECT_SACRIFICE_DESCRIPTION',	0,		1);