-- Start Bias
insert or replace into StartBiasFeatures
	(CivilizationType,				FeatureType,		Tier)
select
	'CIVILIZATION_SUK_SWAHILI',		'FEATURE_SUK_KELP',	2
where exists (select FeatureType from Features where FeatureType = 'FEATURE_SUK_KELP');
-- Traits
update Modifiers set SubjectRequirementSetId = 'PLOT_HAS_REEF_OR_KELP_REQUIREMENTS' where ModifierId = 'TRAIT_SUK_SWAHILI_REEF_PRODUCTION';
update ModifierArguments set Value = 1 where ModifierId = 'TRAIT_SUK_SWAHILI_REEF_PRODUCTION' and Name = 'Amount';
insert or replace into RequirementSets
	(RequirementSetId,							RequirementSetType)
values
	('PLOT_HAS_REEF_OR_KELP_REQUIREMENTS',		'REQUIREMENTSET_TEST_ANY');
insert or replace into RequirementSetRequirements
	(RequirementSetId,							RequirementId)
values
	('PLOT_HAS_REEF_OR_KELP_REQUIREMENTS',		'REQUIRES_PLOT_HAS_REEF');
insert or replace into RequirementSetRequirements
	(RequirementSetId,							RequirementId)
select
	'PLOT_HAS_REEF_OR_KELP_REQUIREMENTS',		'REQUIRES_PLOT_HAS_SUK_KELP'
where exists (select FeatureType from Features where FeatureType = 'FEATURE_SUK_KELP');

--ub
insert or replace into BuildingModifiers
	(BuildingType,								ModifierId)
values
	('BUILDING_SUK_PILLAR_TOMB',				'MONUMENT_CULTURE_AT_FULL_LOYALTY');
insert or replace into TechnologyModifiers
	(TechnologyType,							ModifierId)
values
	('TECH_CALENDAR_HD',						'TECH_CALENDAR_HD_PILLAR_TOMB_CULTURE');
insert or replace into Modifiers
	(ModifierId,													ModifierType)
values
	('TECH_CALENDAR_HD_PILLAR_TOMB_CULTURE',						'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');
insert or replace into ModifierArguments
	(ModifierId,												Name,						Value)
values
    ('TECH_CALENDAR_HD_MONUMENT_CULTURE',                       'BuildingType',             'BUILDING_SUK_PILLAR_TOMB'),
    ('TECH_CALENDAR_HD_MONUMENT_CULTURE',                       'YieldType',                'YIELD_CULTURE'),
    ('TECH_CALENDAR_HD_MONUMENT_CULTURE',                       'Amount',                   1);
-- Unique Unit
/* update Units set PrereqTech = 'TECH_COMPASS_HD', BuildCharges = 0, CostProgressionModel = 'NO_PROGRESSION_MODEL', CostProgressionParam1 = 0 where UnitType = 'UNIT_SUK_JAHAZI';
--delete from UnitAbilityModifiers where UnitAbilityType = 'ABILITY_SUK_JAHAZI_YIELD_BOOST' and ModifierId = 'ABILITY_SUK_JAHAZI_TOURISM_BOOST';
delete from TraitModifiers where TraitType = 'TRAIT_CIVILIZATION_UNIT_SUK_JAHAZI' and ModifierId = 'SUK_JAHAZI_YIELD_BONUS';
delete from UnitAbilities where UnitAbilityType = 'ABILITY_SUK_JAHAZI' or UnitAbilityType = 'ABILITY_SUK_JAHAZI_EMBARKED_MOVEMENT';
insert or replace into Modifiers
	(ModifierId,								ModifierType,									SubjectRequirementSetId)
values	
	('SUK_JAHAZI_YIELD_CHANGE_MODIFIER',		'MODIFIER_PLAYER_ADJUST_PLOT_YIELD',			'PLOT_IS_WATER_AND_ADJACENT_JAHAZI'),
	('JAHAZI_INCREASE_HEAL_RATE',				'MODIFIER_PLAYER_UNITS_ADJUST_HEAL_PER_TURN',	'JAHAZI_HEALING_REQUIREMENTS');
insert or replace into ModifierArguments
	(ModifierId,								Name,				Value)
values
	('SUK_JAHAZI_YIELD_CHANGE_MODIFIER',		'YieldType',		'YIELD_FOOD,YIELD_PRODUCTION'),
	('SUK_JAHAZI_YIELD_CHANGE_MODIFIER',		'Amount',			'1,1'),
	('JAHAZI_INCREASE_HEAL_RATE',				'Type',				'ALL'),
	('JAHAZI_INCREASE_HEAL_RATE',				'Amount',			20);
insert or replace into RequirementSets
	(RequirementSetId,							RequirementSetType)
values	
	('PLOT_IS_WATER_AND_ADJACENT_JAHAZI',		'REQUIREMENTSET_TEST_ALL'),
	('JAHAZI_HEALING_REQUIREMENTS',				'REQUIREMENTSET_TEST_ALL');
insert or replace into RequirementSetRequirements
	(RequirementSetId,							RequirementId)
values	
	('PLOT_IS_WATER_AND_ADJACENT_JAHAZI',		'REQUIRES_PLOT_HAS_COAST'),
	('PLOT_IS_WATER_AND_ADJACENT_JAHAZI',		'SUK_PLOT_ADJACENT_TO_WAT_ARUN_REQUIREMENT'),
	('JAHAZI_HEALING_REQUIREMENTS',				'AOE_REQUIRES_OWNER_ADJACENCY'),
	('JAHAZI_HEALING_REQUIREMENTS',				'AOE_REQUIRES_SEA_DOMAIN'),
	('JAHAZI_HEALING_REQUIREMENTS',				'UNIT_IN_OWNER_TERRITORY_REQUIREMENT');
insert or replace into TypeTags
	(Type,												Tag)
values	
	('ABILITY_SUK_JAHAZI_ADJACENT_HEAL',				'CLASS_SUK_JAHAZI'),
	('ABILITY_SUK_JAHAZI_YIELD_BOOST',					'CLASS_SUK_JAHAZI');
insert or replace into Types
	(Type,										Kind)
values	
	('ABILITY_SUK_JAHAZI_ADJACENT_HEAL',		'KIND_ABILITY'),
	('ABILITY_SUK_JAHAZI_YIELD_BOOST',			'KIND_ABILITY');
insert or replace into UnitAbilities
	(UnitAbilityType,						Name,											Description,										Inactive,		Permanent)
values
	('ABILITY_SUK_JAHAZI_ADJACENT_HEAL',	'LOC_ABILITY_SUK_JAHAZI_ADJACENT_HEAL_NAME',	'LOC_ABILITY_SUK_JAHAZI_ADJACENT_HEAL_DESCRIPTION',	0,				1),
	('ABILITY_SUK_JAHAZI_YIELD_BOOST',		'LOC_ABILITY_SUK_JAHAZI_YIELD_BOOST_NAME',		'LOC_ABILITY_SUK_JAHAZI_YIELD_BOOST_DESCRIPTION',	0,				1);
insert or replace into UnitAbilityModifiers
	(UnitAbilityType,							ModifierId)
values	
	('ABILITY_SUK_JAHAZI_ADJACENT_HEAL',		'JAHAZI_INCREASE_HEAL_RATE'),
	('ABILITY_SUK_JAHAZI_YIELD_BOOST',			'SUK_JAHAZI_YIELD_CHANGE_MODIFIER');
*/
-- New Unique Unit
insert or replace into Types
	(Type,											Kind)
values
	('TRAIT_CIVILIZATION_UNIT_SWAHILI_DHOW',		'KIND_TRAIT'),
	('UNIT_SWAHILI_DHOW',							'KIND_UNIT');
insert or replace into Traits (TraitType) values ('TRAIT_CIVILIZATION_UNIT_SWAHILI_DHOW');
insert or replace into CivilizationTraits
	(CivilizationType, 				TraitType)
values
	('CIVILIZATION_SUK_SWAHILI',	'TRAIT_CIVILIZATION_UNIT_SWAHILI_DHOW');
insert or replace into TypeTags
	(Type,						Tag)
select
	'UNIT_SWAHILI_DHOW',		Tag
from TypeTags where Type = 'UNIT_GALLEY';
insert or replace into UnitAiInfos
	(UnitType,					AiType)
select
	'UNIT_SWAHILI_DHOW',		AiType
from UnitAiInfos where UnitType = 'UNIT_GALLEY';
insert or replace into Units
	(UnitType,					Name,								BaseSightRange,	BaseMoves,	Combat,	BuildCharges,	Domain,			FormationClass,				Cost,	Description,							CanCapture,	PromotionClass,						PrereqTech,			CanTrain,	PurchaseYield,	Maintenance,	ZoneOfControl,	AdvisorType,		TraitType)
values
	('UNIT_SWAHILI_DHOW',		'LOC_UNIT_SWAHILI_DHOW_NAME',		3,				3,			48,		1,				'DOMAIN_SEA',	'FORMATION_CLASS_NAVAL',	120,	'LOC_UNIT_SWAHILI_DHOW_DESCRIPTION',	1,			'PROMOTION_CLASS_NAVAL_MELEE',		'TECH_COMPASS_HD',	1,			'YIELD_GOLD',	3,				1,				'ADVISOR_CONQUEST',	'TRAIT_CIVILIZATION_UNIT_SWAHILI_DHOW');
insert or replace into UnitReplaces (CivUniqueUnitType, ReplacesUnitType) select 'UNIT_SWAHILI_DHOW', 'UNIT_DLV_COG'
where exists (select UnitType from Units where UnitType = 'UNIT_DLV_COG');
insert or replace into UnitUpgrades
	(Unit,						UpgradeUnit)
values
	('UNIT_SWAHILI_DHOW',		'UNIT_CARAVEL');
insert or replace into Improvement_ValidBuildUnits
	(ImprovementType,			UnitType)
select
	'IMPROVEMENT_INDUSTRY',		'UNIT_SWAHILI_DHOW'
where exists (select ImprovementType from Improvements where ImprovementType = 'IMPROVEMENT_INDUSTRY');

UPDATE CivilizationLeaders
SET CapitalName = 'LOC_CITY_NAME_ZANZIBAR'
WHERE LeaderType = 'LEADER_MINOR_CIV_ZANZIBAR'
AND EXISTS (SELECT * FROM CityNames WHERE CityName = 'LOC_CITY_NAME_ZANZIBAR');
/*
--修复LA
delete from TraitModifiers where TraitType = 'TRAIT_LEADER_SUK_HUSUNI_KUBWA';
insert or replace into TraitModifiers
	(TraitType,							ModifierId)
values
	('TRAIT_LEADER_SUK_HUSUNI_KUBWA',	'SUK_HUSUNI_KUBWA_HARBOR_CULTURE'),
	('TRAIT_LEADER_SUK_HUSUNI_KUBWA',	'SUK_HUSUNI_KUBWA_HARBOR_CULTURE_EXTRA'),
	('TRAIT_LEADER_SUK_HUSUNI_KUBWA',	'SUK_HUSUNI_KUBWA_HARBOR_HOUSING'),
	('TRAIT_LEADER_SUK_HUSUNI_KUBWA',	'SUK_HUSUNI_KUBWA_HARBOR_HOUSING_EXTRA'),
	('TRAIT_LEADER_SUK_HUSUNI_KUBWA',	'SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT');

insert or replace into Modifiers
	(ModifierId,											ModifierType,														SubjectRequirementSetId)
values
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE',						'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',					'DISTRICT_IS_DISTRICT_HARBOR_REQUIREMENTS'),
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE_EXTRA',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE',					'SUK_SWAHILI_DISTRICT_HARBOR_ADJACENT_TO_CITY_CENTER'),
	('SUK_HUSUNI_KUBWA_HARBOR_HOUSING',						'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',							'DISTRICT_IS_DISTRICT_HARBOR_REQUIREMENTS'),
	('SUK_HUSUNI_KUBWA_HARBOR_HOUSING_EXTRA',				'MODIFIER_PLAYER_DISTRICTS_ADJUST_HOUSING',							'SUK_SWAHILI_DISTRICT_HARBOR_ADJACENT_TO_CITY_CENTER'),
	('SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT',			'MODIFIER_PLAYER_DISTRICTS_ATTACH_MODIFIER',						'WONDER_IS_OR_ADJACENT_TO_COAST'),
	('SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT_MODIFIER',	'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_PATRONAGE_DISCOUNT_PERCENT',	NULL);

insert or replace into ModifierArguments
	(ModifierId,											Name,						Value)
values
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE',						'YieldType',				'YIELD_CULTURE'),
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE',						'Amount',					1),
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE_EXTRA',				'YieldType',				'YIELD_CULTURE'),
	('SUK_HUSUNI_KUBWA_HARBOR_CULTURE_EXTRA',				'Amount',					1),
	('SUK_HUSUNI_KUBWA_HARBOR_HOUSING',						'Amount',					1),
	('SUK_HUSUNI_KUBWA_HARBOR_HOUSING_EXTRA',				'Amount',					2),
	('SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT',			'ModifierId',				'SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT_MODIFIER'),
	('SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT_MODIFIER',	'Amount',					3),
	('SUK_HUSUNI_KUBWA_WONDER_PATRONAGE_DISCOUNT_MODIFIER',	'YieldType',				'YIELD_GOLD');
*/
--城市
delete from CityNames where CivilizationType = 'CIVILIZATION_SUK_SWAHILI';
update CivilizationLeaders set CapitalName = 'LOC_CITY_NAME_SUK_SWAHILI_KILWA_KISIWANI' where CivilizationType = 'CIVILIZATION_SUK_SWAHILI';
insert or replace into CityNames (ID, CivilizationType, CityName) values
(6901, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KILWA_KISIWANI'),
(6902, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_ZANZIBAR'),
(6903, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MOMBASA'),
(6904, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_LAMU'),
(6905, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MALINDI'),
(6906, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_SOFALA'),
(6907, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MOGADISHU'),
(6908, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_PATE'),
(6909, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MZIZIMA'),
(6910, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_BAGAMOYO'),
(6911, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_GEDI'),
(6912, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_QUELIMANE'),
(6913, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MOZAMBIQUE'),
(6914, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_FAZA'),
(6915, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_ANGOCHE'),
(6916, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_LINDI'),
(6917, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MKUMBULU'),
(6918, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_SHANGA'),
(6919, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_SONGO_MNARA'),
(6920, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MERCA'),
(6921, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KISIMANI_MAFIA'),
(6922, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_IBO'),
(6923, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_PANGANI'),
(6924, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_TANGA'),
(6925, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MUTSAMUDU'),
(6926, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_BRAVA'),
(6927, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_SIYU'),
(6928, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KIZIMKAZI'),
(6929, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_VANGA'),
(6930, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_TAKAUNGU'),
(6931, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_UNGUJA_UKUU'),
(6932, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KILWA_KIVINJE'),
(6933, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MUSHEMBO'),
(6934, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MNARANI'),
(6935, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_TONGONI'),
(6936, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KAOLE'),
(6937, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MBWENI'),
(6938, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MIKINDANI'),
(6939, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_MAKUNDUCHI'),
(6940, 'CIVILIZATION_SUK_SWAHILI', 'LOC_CITY_NAME_SUK_SWAHILI_KIZIMBANI');
