insert or replace into Colors
	(Type,										Color)
values
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY",			"37,66,82,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY",		"228,251,255,255"),	
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_1",		"179,154,117,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_1",		"59,51,45,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_2",		"11,148,103,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_2",		"17,42,29,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_3",		"228,251,255,255"),
	("COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_3",		"37,66,82,255");
insert or replace into PlayerColors (
	Type,
	Usage,
	PrimaryColor,
	SecondaryColor,
	Alt1PrimaryColor,
	Alt1SecondaryColor,
	Alt2PrimaryColor,
	Alt2SecondaryColor,
	Alt3PrimaryColor,
	Alt3SecondaryColor
) values (
	'LEADER_NEBUCHADNEZZAR_II',
	'Unique',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_1',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_1',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_2',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_2',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_PRIMARY_3',
	'COLOR_PLAYER_NEBUCHADNEZZAR_II_SECONDARY_3'
),
(
	'LEADER_ZHUDI',
	'Unique',
	'COLOR_STANDARD_BLUE_DK',
	'COLOR_STANDARD_YELLOW_MD',
	'COLOR_STANDARD_YELLOW_MD',
	'COLOR_STANDARD_RED_MD',
	'COLOR_STANDARD_RED_MD',
	'COLOR_STANDARD_YELLOW_MD',
	'COLOR_STANDARD_WHITE_LT',
	'COLOR_STANDARD_GREEN_DK'
),
(
	'LEADER_WU_ZETIAN_ALT',
	'Unique',
	'COLOR_STANDARD_YELLOW_MD',
	'COLOR_STANDARD_RED_MD',
	'COLOR_STANDARD_WHITE_LT',
	'COLOR_STANDARD_GREEN_DK',
	'COLOR_STANDARD_RED_MD',
	'COLOR_STANDARD_YELLOW_MD',
	'COLOR_STANDARD_BLUE_DK',
	'COLOR_STANDARD_YELLOW_MD'
);