insert or replace into LocalizedText (Language, Tag, Text) values
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_1", "'Galatea' means 'Gaul' in ancient Greek. It is obvious that they are part of Gauls that migrated east. According to Greek documentation, they formed a tribe named 'Tylis' during the Celtic invation of Thrace. "),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_1", "“加拉太”其实就是古希腊语“高卢”的意思，不难看出，他们是东迁的高卢人的一部分。在迁入此地之前，根据希腊人记载，他们先是在公元前三世纪凯尔特人入侵巴尔干的过程中在色雷斯建立了一个部落泰利斯。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_2", "What was called 'Galatea' by the Greeks was composed of three brances: Tectosages, Tromii and Tolistobogii. They were incoroprated and heavily hellenized. Their main settlements included 'Ancyra', 'Pessinus', 'Tavium' and 'Gordion'. "),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_2", "被希腊人称作加拉太人的高卢人有三支：特克托萨吉、特罗克米和托利斯托博吉。在经历了与希腊人的战争与融合之后，他们在弗里吉亚定居。到公元前一世纪，他们已经高度希腊化，被称为“希腊加拉太人”。他们的主要定居点包括安卡拉、培希努、塔维安和戈迪翁。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_3", "According to Strabo, after the death of King Deiotarus, the regime fell into the hans of Armyntas. He was under Brutus and Cassius. He controlled Lyconia and then Capadocia and Isuria. He originally assisted Brutus and Cassius against the Second triumvirate but later sided with Antionius and later Octavius. Later, Galatea gradually became a Roman province."),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_3", "根据斯特拉波的记载，在加拉太王迪奥塔卢斯去世之后，加拉太政权落入安明塔斯手中。他是布鲁图和卡西乌斯手下的辅助军指挥官。他先控制了吕考尼亚，然后是卡帕多西亚和伊苏利亚。他一开始辅助布鲁图和卡西乌斯对抗后三头同盟，然后又倒向安东尼，之后是屋大维。此后，加拉太逐步成为罗马行省。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_4", "Paul the Apostle once spreated Chrisianity here. Although the Galateans were heavily hellenized, they spoke a Celtic dialect. After the 4th Century, the Galateas was assimilated by Greek-speaking people in Asia Minor and ceased to exist as a people. "),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_4", "使徒保罗曾在此传播基督教，著有《加拉太书》。加拉太人虽然希腊化，但是还是使用了很长时间的加拉太高卢语，这是一种凯尔特语。到公元四世纪以后，加拉太人逐渐融入小亚细亚的希腊语居民，不复存在。");
delete from LocalizedText where Tag = "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_PRESLAV_CHAPTER_HISTORY_PARA_5";