-- Pack 1
insert or replace into LocalizedText (Language, Tag, Text) values
-- Hittites
("en_US", "LOC_TRAIT_LEADER_MER_BOND_AND_OATH_DESCRIPTION", "Each City-State type you are Suzerain of provides +10% of the corresponding yield in all your cities. +1 [ICON_Favor] Diplomatic Favor from Suzerainty of City-States and Alliance Level."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_MER_BOND_AND_OATH_DESCRIPTION", "成为宗主的每一个城邦类型为所有城市+10%对应产出。每个宗主城邦和同盟等级+1 [ICON_FAVOR] 外交支持。"),
("en_US", "LOC_TRAIT_CIVILIZATION_MER_SUN_AND_STORM_DESCRIPTION", "Reveals [ICON_RESOURCE_IRON] Iron without the normal technology requirement. Mines over [ICON_RESOURCE_IRON] Iron provides +1 [ICON_SCIENCE] Science and +1 [ICON_PRODUCTION] Production. Each type of improved Strategic Resource provides +1 [ICON_PRODUCTION] Production to districts in the city (except City Center), extra +1 [ICON_SCIENCE] Science in case of [ICON_RESOURCE_IRON] Iron."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_MER_SUN_AND_STORM_DESCRIPTION", "忽略科技要求显示 [ICON_RESOURCE_IRON] 铁资源。开发 [ICON_RESOURCE_IRON] 铁的矿山提供+1 [ICON_SCIENCE] 科技值、+1 [ICON_PRODUCTION] 生产力。每种已改良的战略资源给本城区域（市中心除外）+1 [ICON_PRODUCTION] 生产力，如果是 [ICON_RESOURCE_IRON] 铁资源则额外 +1 [ICON_SCIENCE] 科技值。"),
("en_US", "LOC_UNIT_MER_ANSUKURRA_DESCRIPTION", "Hittite Heavy Cavalry unit, stronger and faster than the Heavy Chariot it replaces. Does not gain additional movement on flat terrain but ignores additional [ICON_Movement] movement costs on hill terrain. Double Support Bonus."),
("zh_Hans_CN", "LOC_UNIT_MER_ANSUKURRA_DESCRIPTION", "取代重型战车的赫梯远古时代特色单位。战斗力更高，移动速度更快。[NEWLINE]在平坦单元格上开始回合不会获得 [ICON_MOVEMENT] 移动力加成，但能无视丘陵带来的 [ICON_MOVEMENT] 移动力减益。双倍支援加成。"),
("en_US", "LOC_BUILDING_MER_ROYAL_ARCHIVE_DESCRIPTION", "Hittite unique building that replaces the Library. +2 Influence Point. +1 [ICON_SCIENCE] Science to improved Strategic resources in the city.[NEWLINE]{LOC_BUILDING_LIBRARY_DESCRIPTION}"),
("zh_Hans_CN", "LOC_BUILDING_MER_ROYAL_ARCHIVE_DESCRIPTION", "赫梯特色建筑，取代图书馆。+2影响力点数。本城已改良的战略资源+1 [ICON_SCIENCE] 科技值。[NEWLINE]{LOC_BUILDING_LIBRARY_DESCRIPTION}"),
-- Pacal
("en_US", "LOC_TRAIT_LEADER_LEU_PACAL_DESCRIPTION", "+2 [ICON_HOUSING] Housing for cities on or adjacent to Luxury resource. Observatory provides +1 [ICON_PRODUCTION] Production to adjacent Bonus Resources, and +1 [ICON_CULTURE] Culture to adjacent Luxury Resources. +100% Wonders basic yield. [NEWLINE] May initiate the 'Sacrifice' Project, which removes 1 [ICON_CITIZEN] Citizen and provides 10 [ICON_CULTURE] and 30 [ICON_FAITH] Faith. Those yields are tripled in cities not founded by Maya."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_LEU_PACAL_DESCRIPTION", "位于或相邻奢侈品资源的城市+2 [ICON_HOUSING] 住房。天文台为相邻的加成资源+1 [ICON_PRODUCTION] 生产力，为相邻的奢侈资源+1 [ICON_CULTURE] 文化值。奇观基础产出+100%。[NEWLINE]可以进行“献祭”项目，若城市 [ICON_CITIZEN] 人口数量大于1，减少1个 [ICON_CITIZEN] 人口，获得10 [ICON_CULTURE] 文化值和30 [ICON_FAITH] 信仰值。在非玛雅建立的城市中这些产出变为三倍。"),
("zh_Hans_CN", "LOC_PROJECT_SACRIFICE_NAME", "献祭"),
("en_US", "LOC_PROJECT_SACRIFICE_NAME", "Sacrifice"),
("zh_Hans_CN", "LOC_PROJECT_SACRIFICE_DESCRIPTION", "减少1个 [ICON_CITIZEN] 人口，获得10 [ICON_CULTURE] 文化值和30 [ICON_FAITH] 信仰值。若此城非玛雅建立，这些产出翻3倍。"),
("en_US", "LOC_PROJECT_SACRIFICE_DESCRIPTION", "Removes 1 [ICON_CITIZEN] Citizen and provides 10 [ICON_CULTURE] and 30 [ICON_FAITH] Faith. Those yields are tripled if the citt is not founded by Maya."),
-- Assyria
("en_US", "LOC_TRAIT_LEADER_BOOM_ASHURBANIPAL_DESCRIPTION", "Gain +2 [ICON_CULTURE] Culture for each city you Razed. May construct the Library of Ashurbanipal in the Government Plaza."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_BOOM_ASHURBANIPAL_DESCRIPTION", "每座您焚毁的城市为首都+2 [ICON_CULTURE] 文化值。可在市政广场中建造亚述巴尼拔图书馆。"),
("en_US", "LOC_TRAIT_CIVILIZATION_BOOM_ASSYRIA_DESCRIPTION", "Combat victories reduce 10 Health of all adjacent enemy units. Whenever you raze a city or one of your city is captured, gain a Settler in the capital and gain 20 [ICON_SCIENCE] Science per [ICON_CITIZEN] population in the razed city."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_BOOM_ASSYRIA_DESCRIPTION", "在战斗中击杀一个单位时，所有相邻敌方单位失去10点生命值。焚毁城市时，在首都获得一个开拓者，且该城市每有1 [ICON_CITIZEN] 人口便获得20点 [ICON_SCIENCE] 科技值。"),
("en_US", "LOC_BOOM_IMPROVEMENT_LAMASSU_DESCRIPTION", "Unlocks the builder ability to construct a Lamassu, unique to Assyria.[NEWLINE][NEWLINE]+1 [ICON_FAITH] Faith. Gain yields equal to the basic yields of all City Center buildings (except Palace) in the city. Encampments adjacnet to Lamassu provides +2 [ICON_GREATGENERAL] Great General Points. Cannot be built adjacent to another Lamassu."),
("zh_Hans_CN", "LOC_BOOM_IMPROVEMENT_LAMASSU_DESCRIPTION", "解锁建造者建造亚述特色改良拉玛苏像的能力。+1 [ICON_FAITH] 信仰值。获得所在城市市中心建筑（不包括宫殿）的基础产出。军营相邻拉玛苏像时+2 [ICON_GREATGENERAL] 大将军点数。不能建造在另一个拉玛苏像旁。"),
("en_US", "LOC_BUILDING_BOOM_ROYAL_LIBRARY_DESCRIPTION", "+30% construction speed towards Military units in your empire. +100% Yields gained from pilaging and coastal raids. Your cities gain +3% [ICON_CULTURE] Culture, +3% [ICON_GOLD] Gold for each city you razed. +1 [ICON_MOVEMENT] Movement to Builder and Settler units.[NEWLINE]Awards +1 [ICON_Governor] Governor Title."),
("zh_Hans_CN", "LOC_BUILDING_BOOM_ROYAL_LIBRARY_DESCRIPTION", "全国建造军事单位时+30%建造速度。劫掠和海岸扫荡的收益+200%。每座您焚毁的城市为您的所有城市+3% [ICON_CULTURE] 文化值，+3% [ICON_GOLD] 金币。建造者和开拓者+1 [ICON_MOVEMENT] 移动力。[NEWLINE]奖励1个 [ICON_GOVERNOR] 总督头衔。"),
("en_US", "LOC_BOOM_UNIT_SIEGE_ENGINE_DESCRIPTION", "Assyrian unique unit that replaces the Battering Ram. Adjacent units gain +5 [ICON_Strength] Strength against fortifications and +8 [ICON_Strength] Strength when defending against ranged attacks.[NEWLINE]When adjacent to a city, attacking melee, anti-cavalry units and Warrior Monks ignore Walls and immediately assault the city. Does not affect cities with Renaissance Walls. Ineffective against Urban Defenses."),
("zh_Hans_CN", "LOC_BOOM_UNIT_SIEGE_ENGINE_DESCRIPTION", "亚述远古时代特色支援单位，取代破城锤。相邻的单位攻击区域时+5 [ICON_STRENGTH] 战斗力，防御远程攻击时+8 [ICON_STRENGTH] 战斗力。[NEWLINE]与城市相邻时，近战、抗骑兵单位和武僧可无视城墙直接对城市发起进攻。对拥有文艺复兴城墙的城市无效。对现代城市防御无效。"),
("en_US", "LOC_BOOM_ASSYRIA_UNIT_SIEGE_BONUS_DESCRIPTION", "+5 [ICON_Strength] Combat Strength against defensible districts from the Siege Engine"),
("zh_Hans_CN", "LOC_BOOM_ASSYRIA_UNIT_SIEGE_BONUS_DESCRIPTION", "攻击区域时+5 [ICON_STRENGTH] 战斗力，来自相邻攻城车"),
("en_US", "LOC_BOOM_ASSYRIA_UNIT_DEFENSE_BONUS_DESCRIPTION", "+8 [ICON_Strength] Combat Strength when defending against Ranged Attacks from Siege Engine"),
("zh_Hans_CN", "LOC_BOOM_ASSYRIA_UNIT_DEFENSE_BONUS_DESCRIPTION", "防御远程攻击时+5 [ICON_STRENGTH] 战斗力，来自相邻攻城车"),
("zh_Hans_CN", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_COMBAT_BONUS_NAME", "与攻城车相邻"),
("en_US", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_COMBAT_BONUS_NAME", "Adjacent to Siege Engine"),
("zh_Hans_CN", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_COMBAT_BONUS_DESCRIPTION", "此单位与攻城车相邻，攻击区域时+5 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_COMBAT_BONUS_DESCRIPTION", "This unit is adjacent to a Siege Engine, it gets +5 [ICON_STRENGTH] Combat Strength vs. District defenses."),
("zh_Hans_CN", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_DEFENSE_BONUS_NAME", "与攻城车相邻"),
("en_US", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_DEFENSE_BONUS_NAME", "Adjacent to Siege Engine"),
("zh_Hans_CN", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_DEFENSE_BONUS_DESCRIPTION", "此单位与攻城车相邻，防御远程攻击时+8 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_ABILITY_BOOM_SIEGE_ENGINE_GRANT_DEFENSE_BONUS_DESCRIPTION", "This unit is adjacent to a Siege Engine, it gets +8 [ICON_STRENGTH] Combat Strength when defending against ranged attacks."),
("en_US", "LOC_UNIT_ASSYRIA_KISIR_SARRUTI_NAME", "kiṣir šarrūti"),
("zh_Hans_CN", "LOC_UNIT_ASSYRIA_KISIR_SARRUTI_NAME", "皇家禁卫"),
("en_US", "LOC_UNIT_ASSYRIA_KISIR_SARRUTI_DESCRIPTION", "Assyrian Classical Era Unique Unit that replaces the Pikeman. Lower [ICON_STRENGTH] Strength, but is unlocked earlier, has more [ICON_MOVEMENT] Movement and cheaper to build. Has 1 free promotion."),
("zh_Hans_CN", "LOC_UNIT_ASSYRIA_KISIR_SARRUTI_DESCRIPTION", "亚述古典时期特色抗骑兵单位，取代长矛兵。[ICON_STRENGTH] 战斗力更低，但解锁更早，[ICON_MOVEMENT] 移动力更高且建造成本更低。初始便拥有1次免费升级。"),
-- Nebuchadnezzar
("en_US", "LOC_TRAIT_HANGING_GARDENS_DESCRIPTION", "+5% construction speed towards Wonders for each city you captured. +50% Yield from pilaging and coastal raids. When you capture a city, gain 30 [ICON_GOLD] for each [ICON_CITIZEN] citizen in that city."),--Each city you captured provides +1 [ICON_FOOD] Food, +1 [ICON_PRODUCTION] Production to each city you founded. 
("zh_Hans_CN", "LOC_TRAIT_HANGING_GARDENS_DESCRIPTION", "每占领一座城市，建造奇观时+5%建造速度。劫掠和海岸扫荡的收益+50%。占领城市时，该城市每有1个 [ICON_CITIZEN] 人口便获得30 [ICON_GOLD] 金币。"),--每个占领的城市为每个巴比伦建立的城市+1 [ICON_FOOD] 食物、+1 [ICON_PRODUCTION] 生产力。
("en_US", "LOC_AGENDA_BABYLONIAN_CAPTIVITY_DESCRIPTION", "Likes civilization that has high [ICON_SCIENCE] Science and is at war with any major civilization. Dislikes civilization that build many wonders but has low military power."),
("zh_Hans_CN", "LOC_AGENDA_BABYLONIAN_CAPTIVITY_DESCRIPTION", "喜欢 [ICON_SCIENCE] 科技值高且与主要文明处于战争状态的文明。不喜欢建造大量奇观但军事实力弱的文明。");

-- Pack 3
insert or replace into LocalizedText (Language, Tag, Text) values
-- Bulgaria
("en_US", "LOC_TRAIT_LEADER_MER_CLAIM_TO_BYZANTIUM_DESCRIPTION", "+2 [ICON_GREATPROPHET] Great Prophet point after any player recruits a [ICON_GREATPROPHET] Great Prophet. +3 [ICON_CULTURE] Culture for each city following Bulgaria's Religion. Your cities exert +100% Religious pressure. Bulgaria's Religion is spread to nearby cities when your religious unit is killed."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_MER_CLAIM_TO_BYZANTIUM_DESCRIPTION", "每有一个大预言家被招募便为你+2 [ICON_GREATPROPHET] 大预言家点数。每座信奉保加利亚宗教的城市+3 [ICON_CULTURE] 文化值。城市的宗教传播的压力增加100%。宗教单位被击杀时向周围6个单元格内的城市施加250宗教压力。"),
("en_US", "LOC_CLAIM_TO_BYZANTIUM_UNIT_STRENGTH", "+{1_Amount} [ICON_STRENGTH] Combat Strength from 'Claim to Byzantium'"),
("zh_Hans_CN", "LOC_CLAIM_TO_BYZANTIUM_UNIT_STRENGTH", "+{1_Amount} [ICON_STRENGTH] 战斗力，来自“宣称拜占庭”"),
("en_US", "LOC_TRAIT_CIVILIZATION_MER_CYRILLIC_SCRIPTS_DESCRIPTION", "Cities on Hills or adjacent to Mountains can build one more district than the [ICON_CITIZEN] Population limit allows. Districts on Hills or adjacent to Mountains gain +1 [ICON_CULTURE] Culture. District provides +2 [ICON_FAITH] Faith to adjacent Hills."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_MER_CYRILLIC_SCRIPTS_DESCRIPTION", "相邻山脉或位于丘陵的城市+1区域位。相邻山脉或位于丘陵的区域+1 [ICON_CULTURE] 文化值。每个区域为相邻的丘陵单元格+2 [ICON_FAITH] 信仰值。"),
("en_US", "LOC_UNIT_MER_CUMAN_CAVALRY_DESCRIPTION", "Bulgarian unique Heavy Cavalry unit that replaces the Knight. Can perform Ranged attack. Costs only 1 [ICON_Movement] Movement to pillage. Costs [ICON_RESOURCE_HORSES] Horses instead of [ICON_RESOURCE_IRON] Iron."),
("zh_Hans_CN", "LOC_UNIT_MER_CUMAN_CAVALRY_DESCRIPTION", "保加利亚特色重骑兵单位，取代骑士。拥有远程攻击能力。劫掠只需要1点 [ICON_MOVEMENT] 移动力。消耗 [ICON_RESOURCE_HORSES] 马而不是 [ICON_RESOURCE_IRON] 铁。"),
("en_US", "LOC_BUILDING_MER_LITERARY_SCHOOL_DESCRIPTION", "Bulgarian unique building. +2 [ICON_CULTURE] Culture and +2 [ICON_SCIENCE] with 4-tile regional effect. Provides +2 [ICON_GREATWRITER] Great Writer Points, and has 2 [ICON_GREATWORK_WRITING] Great Works of Writing slots, themed when displaying [ICON_GREATWORK_WRITING] Great Works of Writing from different writers."),
("zh_Hans_CN", "LOC_BUILDING_MER_LITERARY_SCHOOL_DESCRIPTION", "保加利亚特色建筑。+2 [ICON_CULTURE] 文化值，+2 [ICON_SCIENCE]科技值，4环辐射。+2 [ICON_GREATWRITER] 大作家点数，拥有2个 [ICON_GREATWORK_WRITING] 著作巨作槽位，当展示来自不同作家的作品时获得主题化。"),
("en_US", "LOC_BUILDING_THEMINGBONUS_LITERARY_SCHOOL", "Theming bonus doubling output when displaying objects from different writers."),
("zh_Hans_CN", "LOC_BUILDING_THEMINGBONUS_LITERARY_SCHOOL", "当展示来自不同作家的作品时，主题加成翻倍。"),
("en_US", "LOC_UNIT_BULGARIA_KONIKK_NAME", "Bulgarian Konikk"),
("zh_Hans_CN", "LOC_UNIT_BULGARIA_KONIKK_NAME", "保加尔骑兵"),
("en_US", "LOC_UNIT_BULGARIA_KONIKK_DESCRIPTION", "Bulgarian Unique Unit that replaces the Courser. Has higher [ICON_STRENGTH] Combat Strength. +5 [ICON_STRENGTH] Strength when occupying a district or v.s. district defenses."),
("zh_Hans_CN", "LOC_UNIT_BULGARIA_KONIKK_DESCRIPTION", "保加利亚特色单位，取代追猎者。具有更高的 [ICON_STRENGTH] 战斗力。占领区域或对抗区域防御时+5 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_ABILITY_BULGARIA_KONIKK_DESCRIPTION", "+5 [ICON_STRENGTH] Strength when occupying a district or v.s. district defenses."),
("zh_Hans_CN", "LOC_ABILITY_BULGARIA_KONIKK_DESCRIPTION", "占领区域或对抗区域防御时+5 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_BULGARIA_KONIKK_ADD_STRENGTH", "+5 Strength for occupying a district or v.s. district defenses."),
("zh_Hans_CN", "LOC_BULGARIA_KONIKK_ADD_STRENGTH", "占领区域或对抗区域防御+5战斗力。"),
-- Romania
("en_US", "LOC_TRAIT_CIVILIZATION_CVS_ROMANIA_UA_DESCRIPTION", "Gain 50% progress of all civics that unlock government when the game starts. All cities get +10% of all yields if you have switched to a new Tier of Government for the first time in the past 10 turns. Your Government provides the Legacy Effect of all Governments of lower Tiers."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_CVS_ROMANIA_UA_DESCRIPTION", "游戏开始时获得所有解锁政体的市政50%的研究进度。如果在过去10个回合内曾首次切换到新一级的政体，所有城市+10%所有产出。政体提供所有更低级政体的传承效果。"),
("en_US", "LOC_TRAIT_LEADER_CVS_VLAD_III_UA_DESCRIPTION", "Pillaging deals damage to adjacent units of the pillaged player equal to the basic [ICON_STRENGTH] Strength of the pillaging unit."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_VLAD_III_UA_DESCRIPTION", "攻击相邻单元格的单位时，若目标存活，则对其身后至多两个单元格的单位造成额外伤害。每隔一个单元格，伤害衰减20%。"),
("en_US", "LOC_BUILDING_CVS_ROMANIA_UI_DESCRIPTION", "An Encampment building unique to Romania. When built, gain yields equal to the sum of yields of all adjacent tiles. Units trained in this city heal 30 health after killing a unit. Allow purchasing Military Engineers."),
("zh_Hans_CN", "LOC_BUILDING_CVS_ROMANIA_UI_DESCRIPTION", "罗马尼亚特色军营建筑。建成时，获得所有相邻单元格的产出作为此建筑的产出。此城市生产的单位击杀单位时回复30点生命值。允许购买军事工程师。"),
("en_US", "LOC_UNIT_CVS_VLAD_III_UU_DESCRIPTION", "Romania unique cavalry unit that replaces the Courser. Can perform Ranged attack. Costs only 1 [ICON_MOVEMENT] Movement to pillage."),
("zh_Hans_CN", "LOC_UNIT_CVS_VLAD_III_UU_DESCRIPTION", "罗马尼亚特色轻骑兵单位，取代追猎者。拥有远程攻击能力。劫掠只需要1点 [ICON_MOVEMENT] 移动力。"),
("en_US", "LOC_UNIT_CVS_ROMANIA_UU_DESCRIPTION", "Romania unique recon unit that replaces the Spec Ops. +7 [ICON_STRENGTH] Combat Strength on Hills. +50% experience from combat."),
("zh_Hans_CN", "LOC_UNIT_CVS_ROMANIA_UU_DESCRIPTION", "罗马尼亚特色侦察单位，取代特种部队。在丘陵上时+7 [ICON_STRENGTH] 战斗力。从战斗中获得的经验+50%。"),
("en_US", "LOC_MODIFIER_CVS_ROMANIA_UU_HILLS_COMBAT", "+{1_Amount} [ICON_STRENGTH] Combat Strength on Hills"),
("zh_Hans_CN", "LOC_MODIFIER_CVS_ROMANIA_UU_HILLS_COMBAT", "位于丘陵 +{1_Amount} [ICON_STRENGTH] 战斗力"),
-- Charlemagne
("en_US", "LOC_PROJECT_CHALEMAGNE_FOOD_NAME", "Capitulare de villis"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_FOOD_NAME", "庄园敕令"),
("en_US", "LOC_PROJECT_CHALEMAGNE_FAITH_NAME", "Synod"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_FAITH_NAME", "宗教会议"),
("en_US", "LOC_PROJECT_CHALEMAGNE_GOLD_NAME", "Tithe Collection"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_GOLD_NAME", "征收什一税"),
("en_US", "LOC_PROJECT_CHALEMAGNE_CULTURE_NAME", "Latin Teaching"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_CULTURE_NAME", "拉丁文教学"),
("en_US", "LOC_PROJECT_CHALEMAGNE_SCIENCE_NAME", "Seven Liberal Arts"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_SCIENCE_NAME", "七艺"),
("en_US", "LOC_PROJECT_CHALEMAGNE_FOOD_FLAVOR", "And now, the King is in control!"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_FOOD_FLAVOR", "现在，国王掌握一切！"),
("en_US", "LOC_PROJECT_CHALEMAGNE_FAITH_FLAVOR", "The Pope went away happily!"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_FAITH_FLAVOR", "教皇高兴地离开了！"),
("en_US", "LOC_PROJECT_CHALEMAGNE_GOLD_FLAVOR", "Good, but at what cost?"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_GOLD_FLAVOR", "很好，但是代价是什么？"),
("en_US", "LOC_PROJECT_CHALEMAGNE_CULTURE_FLAVOR", "The literacy rate of this city has increased! Hooray!"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_CULTURE_FLAVOR", "这座城市的识字率提升了！好耶！"),
("en_US", "LOC_PROJECT_CHALEMAGNE_SCIENCE_FLAVOR", "Students are really proud of what they have mastered!"),
("zh_Hans_CN", "LOC_PROJECT_CHALEMAGNE_SCIENCE_FLAVOR", "学生们对自己掌握的一切都很自豪！"),
-- Charlemagne (France)
("en_US", "LOC_TRAIT_LEADER_GEDEMO_CHARLEMAGNE1_DESCRIPTION", "[ICON_CITIZEN] Citizens in cities with at least 7 population provide 0.5 [ICON_SCIENCE] Science, 0.5 [ICON_CULTURE] Culture and 2 [ICON_GOLD] Gold. Allow unique projects that can convert [ICON_PRODUCTION] Production into other yields. Gain the Paladin Unique Unit after progressing 'Literary Tradition' Civic. Grant a free Paladin whenever you recruit a [ICON_GREATWRITER] Great Writer."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_GEDEMO_CHARLEMAGNE1_DESCRIPTION", "至少7人口的城市中每位 [ICON_CITIZEN] 公民提供0.5 [ICON_SCIENCE] 科技值、0.5 [ICON_CULTURE] 文化值和2 [ICON_GOLD] 金币。可以在城市中进行特色项目来将 [ICON_PRODUCTION] 生产力转化为其他产出。解锁“文学传统”市政以后，获得特色单位圣骑士。每招募一个 [ICON_GREATWRITER] 大作家获得一个免费的圣骑士。"),
("en_US", "LOC_UNIT_GEDEMO_PALADIN_DESCRIPTION", "Charlemagne's Unique heavy cavalry Unit. Weaker than Combat victories provide [ICON_CULTURE] Culture equal to 50% of the killed unit's base [ICON_Strength] Combat Strength."),
("zh_Hans_CN", "LOC_UNIT_GEDEMO_PALADIN_DESCRIPTION", "查理曼特色重骑兵单位。战斗胜利后，获得等同于被击杀单位50%基础 [ICON_Strength] 战斗力的 [ICON_CULTURE] 文化值。"),
("en_US", "LOC_ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS_DESCRIPTION", "Combat victories provide [ICON_CULTURE] Culture equal to 50% of the killed unit's base [ICON_Strength] Combat Strength."),
("zh_Hans_CN", "LOC_ABILITY_CHARLEMAGNE_GAIN_CULTURE_ON_KILLS_DESCRIPTION", "战斗胜利后，获得等同于被击杀单位50%基础 [ICON_Strength] 战斗力的 [ICON_CULTURE] 文化值。"),
-- Charlemagne (Germany)
("en_US", "LOC_TRAIT_LEADER_GEDEMO_KARLDERGROSSE1_DESCRIPTION", "[ICON_CITIZEN] Citizens in cities with at least 7 population provide 0.5 [ICON_SCIENCE] Science, 0.5 [ICON_CULTURE] Culture and 2 [ICON_GOLD] Gold. Allow unique projects that can convert [ICON_PRODUCTION] Production into other yields. Gain the Paladin Unique Unit after progressing 'Literary Tradition' Civic. Grant a free Paladin whenever you recruit a [ICON_GREATWRITER] Great Writer."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_GEDEMO_KARLDERGROSSE1_DESCRIPTION", "至少7人口的城市中每位 [ICON_CITIZEN] 公民提供0.5 [ICON_SCIENCE] 科技值、0.5 [ICON_CULTURE] 文化值和2 [ICON_GOLD] 金币。可以在城市中进行特色项目来将 [ICON_PRODUCTION] 生产力转化为其他产出。解锁“文学传统”市政以后，获得特色单位圣骑士。每招募一个 [ICON_GREATWRITER] 大作家获得一个免费的圣骑士。"),
("en_US", "LOC_UNIT_GEDEMO_GPALADIN_DESCRIPTION", "Charlemagne's Unique heavy cavalry Unit. Weaker than Combat victories provide [ICON_CULTURE] Culture equal to 50% of the killed unit's base [ICON_Strength] Combat Strength."),
("zh_Hans_CN", "LOC_UNIT_GEDEMO_GPALADIN_DESCRIPTION", "查理曼特色重骑兵单位。战斗胜利后，获得等同于被击杀单位50%基础 [ICON_Strength] 战斗力的 [ICON_CULTURE] 文化值。"),
-- Ottoman
("en_US", "LOC_TRAIT_CIVILIZATION_GREAT_TURKISH_BOMBARD_NAME", "Passha"),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_GREAT_TURKISH_BOMBARD_NAME", "帕夏"),
("en_US", "LOC_TRAIT_CIVILIZATION_GREAT_TURKISH_BOMBARD_DESCRIPTION", "All siege units gain +5 [ICON_STRENGTH] Combat Strength against district defenses. Conquered cities do not lose [ICON_CITIZEN] Population. Cities not founded by Ottoman gain +1 [ICON_AMENITIES] Amenity, +20% [ICON_GOLD] Gold and +40% construction speed towards district and building."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_GREAT_TURKISH_BOMBARD_DESCRIPTION", "攻击区域防御时，所有攻城单位+5 [ICON_STRENGTH] 战斗力。征服城市不会造成 [ICON_CITIZEN] 人口损失。非奥斯曼建立的城市+1 [ICON_AMENITIES] 宜居度，+20% [ICON_GOLD] 金币，建造区域和建筑时+40%建造速度。"),
("en_US", "LOC_TRAIT_LEADER_SULEIMAN_GOVERNOR_DESCRIPTION", "+20% construction speed towards all units. Exclusive unique Governor with military and diplomatic abilities. Gain a [ICON_GOVERNOR] Governor Title the first time you conquer a City State or an [ICON_CAPITAL] original capital."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SULEIMAN_GOVERNOR_DESCRIPTION", "生产单位时+20%建造速度。拥有特色总督“大维齐尔”。首次占领城邦或一个文明的 [ICON_CAPITAL] 原始首都时获得1个 [ICON_GOVERNOR] 总督头衔。"),
("en_US", "LOC_GOVERNOR_PROMOTION_PASHA_DESCRIPTION", "Each [ICON_CITIZEN] Citizen in the city provides +1 [ICON_PRODUCTION] Production. Gain [ICON_SCIENCE] Science equal to 25% of the unit's cost when a non-civilian unit is trained in this city, doubled if this city has an Armory. Establishes in 3 turns."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_PASHA_DESCRIPTION", "城市中每位 [ICON_CITIZEN] 公民提供+1 [ICON_PRODUCTION] 生产力。此城生产非平民单位时，获得等同于单位花费25%的 [ICON_SCIENCE] 科技值，若此城有兵工厂则翻倍。就职需要3回合。"),
("en_US", "LOC_GOVERNOR_PROMOTION_HEAD_FALCONER_DESCRIPTION", "+50% construction speed towards Encampment buildings in this city. +3 [ICON_SCIENCE] Science for each Encampment and Encampment building in this city. Units within 10 tiles of the City Center get +10 [ICON_STRENGTH] Combat Strength when attacking districts."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_HEAD_FALCONER_DESCRIPTION", "此城建造军营建筑时+30%建造速度，每个军营和军营建筑+3 [ICON_SCIENCE] 科技值。攻击防御性区域时，此城市中心10个单元格内的所有单位+10 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_GOVERNOR_PROMOTION_GRAND_VISIER_DESCRIPTION", "+5 [ICON_STRENGTH] Combat Strength to all units."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_GRAND_VISIER_DESCRIPTION", "所有单位+5 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_GRAND_VISIER_COMBAT", "+{1_Amount} from Grand Vizier"),
("zh_Hans_CN", "LOC_GRAND_VISIER_COMBAT", "+{1_Amount} 来自大维齐尔"),
("en_US", "LOC_GOVERNOR_PROMOTION_SERASKER_DESCRIPTION", "Encampement and Commercial Hub in this city recieve +100% adjancency bonus and provide [ICON_SCIENCE] Science equal to their adjacency bonus."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SERASKER_DESCRIPTION", "此城的军营和商业中心+100%相邻加成，并提供等同于相邻加成的 [ICON_SCIENCE] 科技值。"),
("en_US", "LOC_GOVERNOR_PROMOTION_KHASS_ODA_BASHI_DESCRIPTION", "Trader units within 5 tiles provides +10 [ICON_GOLD] Gold and +3 [ICON_GREATMERCHANT] Great Merchant points to this city. In this city, each Commercial Hub, Harbor district and building in these districts provides +10% [ICON_PRODUCTION] Production to this city."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_KHASS_ODA_BASHI_DESCRIPTION", "5个单元格内的商人单位为此城+10 [ICON_GOLD] 金币、+3 [ICON_GREATMERCHANT] 大商人点数。此城中每个商业中心、港口和这些区域中的建筑为此城+10% [ICON_PRODUCTION] 生产力。"),
("en_US", "LOC_GOVERNOR_PROMOTION_CAPOU_AGHA_DESCRIPTION", "Receive a copy of unit each time you train a Renaissance era or later melee/siege unit."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_CAPOU_AGHA_DESCRIPTION", "此城训练文艺复兴及之后时代的近战和攻城单位时可以额外获得一个相同的单位。");

-- Pack 2
insert or replace into LocalizedText (Language, Tag, Text) values
-- Siam
("en_US", "LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_DESCRIPTION", "+1 [ICON_Housing] Housing, +1 [ICON_Amenities] Amenity to cities adjacent to river. +1 [ICON_Culture] Culture to Farms adjacent to river. Receive an additional [ICON_Envoy] Envoy from Civics that provide [ICON_Envoy] Envoys."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_SUK_SRI_AYUTTHAYA_DESCRIPTION", "相邻河流的城市+1 [ICON_Housing] 住房和+1 [ICON_Amenities] 宜居度。相邻河流的农场+1 [ICON_Culture] 文化值。每个提供 [ICON_Envoy] 使者的市政额外提供1个 [ICON_Envoy] 使者。"),
("en_US", "LOC_UNIT_SUK_SIAM_CHANGSUEK_DESCRIPTION", "Siamese unique Unit that replaces the Knight. Stronger, does not costs [ICON_RESOURCE_HORSES] Horses, but has less [ICON_MOVEMENT] Movement and is more expensive than the Knight. Adjacent units gain double experience from battles."),
("zh_Hans_CN", "LOC_UNIT_SUK_SIAM_CHANGSUEK_DESCRIPTION", "取代骑士的暹罗特色单位。比骑士更强，不消耗 [ICON_RESOURCE_HORSES] 马，但 [ICON_MOVEMENT] 移动力更低，价格更高。相邻单位从战斗中获得双倍经验。"),
("en_US", "LOC_UNIT_SIAMESE_EXPEDITIONARY_FORCES_DESCRIPTION", "Siamese unique Unit that replaces the Infantry. Cheaper then the Infantry. Ignores [ICON_MOVEMENT] Movement and [ICON_STRENGTH] Combat Strength penalty from rivers."),
("zh_Hans_CN", "LOC_UNIT_SIAMESE_EXPEDITIONARY_FORCES_DESCRIPTION", "取代步兵的暹罗特色单位。造价更低。忽视河流带来的 [ICON_MOVEMENT] 移动力和 [ICON_STRENGTH] 战斗力惩罚。"),
("en_US", "LOC_DISTRICT_SUK_FLOATINGMARKET_EXPANSION_2_DESCRIPTION", "A district unique to Siam, replacing the Commercial Hub district.[NEWLINE]+3 [ICON_GOLD] Gold to Resources in this city. If built adjacent to river, provides +1 [ICON_FOOD] Food and [ICON_Production] Production to districts adjacent to river in this city. Cannot be built on Hills.[NEWLINE][NEWLINE]+2 [ICON_Gold] Gold from [ICON_TradeRoute] Trade Routes starting from this city. Immediately create a [ICON_TRADINGPOST] Trading Post in this city."),
("zh_Hans_CN", "LOC_DISTRICT_SUK_FLOATINGMARKET_EXPANSION_2_DESCRIPTION", "暹罗特色区域，取代“商业中心”。[NEWLINE]为本城的资源+3 [ICON_GOLD] 金币。如果相邻河流建造，则为本城相邻河流的区域+1 [ICON_FOOD] 食物和 [ICON_Production] 生产力。不能建造在丘陵上。[NEWLINE][NEWLINE]本城出发的 [ICON_TradeRoute] 贸易路线+2 [ICON_Gold] 金币。本城建立一个 [ICON_TRADINGPOST] 贸易站。"),
("en_US", "LOC_SUK_FLOATINGMARKET_RIVER_PRODUCTION", "+{1_num} [ICON_PRODUCTION] Production from the adjacent river."),
("zh_Hans_CN", "LOC_SUK_FLOATINGMARKET_RIVER_PRODUCTION", "+{1_num} [ICON_Production] 生产力来自相邻河流。"),
("en_US", "LOC_ABILITY_UNIT_SIAMESE_EXPEDITIONARY_FORCES_IGNORE_RIVER_DESCRIPTION", "Ignores [ICON_MOVEMENT] Movement and [ICON_STRENGTH] Combat Strength penalty from rivers."),
("zh_Hans_CN", "LOC_ABILITY_UNIT_SIAMESE_EXPEDITIONARY_FORCES_IGNORE_RIVER_DESCRIPTION", "忽视河流带来的 [ICON_MOVEMENT] 移动力和 [ICON_STRENGTH] 战斗力惩罚。"),
-- Siam (Ramkhamhaeng)
("en_US", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_DESCRIPTION", "Receive [ICON_Gold] Gold when a [ICON_TechBoosted] Eureka or [ICON_CivicBoosted] Inspiration is triggered."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_DESCRIPTION", "获得 [ICON_TechBoosted] 尤里卡和 [ICON_CivicBoosted] 鼓舞时也获得 [ICON_Gold] 金币。"),
("en_US", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_EUREKA", "+{1} [ICON_Gold] Gold from triggering the [ICON_TechBoosted] Eureka for {2}"),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_EUREKA", "从{2}的 [ICON_TechBoosted] 尤里卡中获得{1} [ICON_Gold] 金币。"),
("en_US", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_INSPIRATION", "+{1} [ICON_Gold] Gold from triggering the [ICON_CivicBoosted] Inspiration for {2}"),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_THE_THAI_ALPHABET_INSPIRATION", "从{2}的 [ICON_CivicBoosted] 鼓舞中获得{1} [ICON_Gold] 金币。"),
-- Siam (Chulalongkorn)
("en_US", "LOC_TRAIT_LEADER_SUK_MONTHON_SYSTEM_XP2_DESCRIPTION", "The city with Government Plaza can build one more district than the [ICON_CITIZEN] population limit allows. 1 unused [ICON_ENVOY] Envoy is converted to a [Icon_Governor] Governor Title when the Government Plaza or a Government Plaza building is constructed. Has an exclusive unique Governor 'The Mahatthai'."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_MONTHON_SYSTEM_XP2_DESCRIPTION", "市政广场所在的城市可以无视 [ICON_CITIZEN] 人口限制额外建造一个区域。完成市政广场或其中的建筑时，将1个未使用的 [ICON_ENVOY] 使者转化为1个 [Icon_Governor] 总督头衔。拥有一名特色总督“摩诃泰”。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_ROYAL_SURVEY_DESCRIPTION", "+3 [ICON_Food] Food and +3 [ICON_Production] Production to cities within 6 tiles."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_ROYAL_SURVEY_DESCRIPTION", "6个单元格内的城市获得+3 [ICON_FOOD] 食物、+3[ICON_PRODUCTION] 生产力。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SANITARY_DISTRICTS_DESCRIPTION", "In cities within 6 tiles, +50% construction speed towards Aqueduct, Dam, Canal and buildings in these districts. Cities within 6 tiles get +1 [ICON_FOOD] Food for each of these districts or building in these districts this city has."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SANITARY_DISTRICTS_DESCRIPTION", "6个单元格内的城市建造水渠、堤坝和运河及其中的建筑时+50%建造速度。此城市每有一个这些区域或其中的建筑，6个单元格内的城市便获得+1 [ICON_FOOD] 食物。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SUANKULARB_COLLEGE_DESCRIPTION", "In cities within 6 tiles, +20% construction speed towards Campus and Campus buildings. Cities within 6 tiles get +2 [ICON_Science] Science for each Campus or Campus building in this city."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SUANKULARB_COLLEGE_DESCRIPTION", "6个单元格内的城市建造学院和学院建筑时+20%建造速度。此城市每有一个学院或学院建筑，6个单元格内的城市便获得+2 [ICON_SCIENCE] 科技值。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_MONTHON_REFORMS_DESCRIPTION", "+2 [ICON_Production] Production for each of your specialty districts within 6 tiles."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_MONTHON_REFORMS_DESCRIPTION", "6个单元格内的每个专业化区域+2 [ICON_PRODUCTION] 生产力。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SIAM_SOCIETY_DESCRIPTION", "In cities within 6 tiles, +20% construction speed towards Theater Square and Theater Square buildings. Cities within 6 tiles get +2 [ICON_CULTURE] Culture for each Theater Square or Theater Square building in this city."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_SIAM_SOCIETY_DESCRIPTION", "6个单元格内的城市建造剧院广场和剧院广场建筑时+20%建造速度。此城市每有一个剧院广场或剧院广场建筑，6个单元格内的城市便获得+2 [ICON_CULTURE] 文化值。"),
("en_US", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_KHWAM_SIWILAI_DESCRIPTION", "Cities within 6 tiles with a [ICON_GOVERNOR] Governor get +10% [ICON_Science] Science and +10% [ICON_Culture] Culture."),
("zh_Hans_CN", "LOC_GOVERNOR_PROMOTION_SUK_DAMRONG_KHWAM_SIWILAI_DESCRIPTION", "6个单元格内有总督的城市获得+10% [ICON_SCIENCE] 科技值和+10% [ICON_CULTURE] 文化值。"),
-- Siam (Narai)
("en_US", "LOC_TRAIT_LEADER_SUK_SIAMOISES_DESCRIPTION", "Alliance Points with all allies increase by an additional 0.25 per turn, and each of your Alliances grant +15 [ICON_Gold] Gold, +3 [ICON_Culture] Culture, and +2 [ICON_FAVOR] Diplomatic Favor for both civilizations. The Floating Market district and its buildings each grant +1 [ICON_Science] Science to International [ICON_TradeRoute] Trade Routes sent from that city."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_SIAMOISES_DESCRIPTION", "每回合额外增加0.25点同盟点数。每个同盟为双方提供+15 [ICON_GOLD] 金币、+3 [ICON_CULTURE] 文化值和+2 [ICON_FAVOR] 外交支持。水上市场和其中的建筑为该城出发的国际 [ICON_TRADEROUTE] 贸易路线+1 [ICON_SCIENCE] 科技值。"),
("en_US", "LOC_TRAIT_LEADER_SUK_SIAMOISES_DESCRIPTION_XP2_DLC", "The city with Diplomatic Quarter district can build one more district than the [ICON_CITIZEN] population limit allows. Each time you meet a City-State, [ICON_CAPITAL] Capital receives corresponding yields of its type; Diplomatic Quarter districts receive these yields as well after Diplomatic Service Civic is researched. After forming an Alliance with every major civilization for the first time, your cities receive +10% corresponding yield of Alliance."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_SIAMOISES_DESCRIPTION_XP2_DLC", "外交区所在的城市可以无视 [ICON_CITIZEN] 人口限制额外建造一个区域。会晤城邦后 [ICON_CAPITAL] 首都获得该城邦类型的对应产出；解锁“外交部门”市政后，外交区也可获得这些产出。首次与每一位主要文明建立同盟时，所有城市获得+10%对应产出。"),
-- Zimbabwe
("en_US", "LOC_TRAIT_CIVILIZATION_GEDEMO_ZIMBABWE_CIV_TRAIT_DESCRIPTION", "[ICON_TradeRoute] Trade Routes get +1 [ICON_Culture] Culture for each Camp and Plantation at the destination."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_GEDEMO_ZIMBABWE_CIV_TRAIT_DESCRIPTION", "[ICON_TradeRoute] 贸易路线从目的地每个种植园和营地获得+1 [ICON_CULTURE] 文化值。"),
("en_US", "LOC_TRAIT_LEADER_GEDEMO_MUTOTA_LTRAIT_DESCRIPTION", "'Early Empire' and 'Feudalism' Civic each provides an [ICON_TradeRoute] Trade Route Capacity. Units that start their turn adjacent to river gain +5 [ICON_Strength] Combat Strength."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_GEDEMO_MUTOTA_LTRAIT_DESCRIPTION", "“帝国初期”和“封建主义”市政各解锁一个 [ICON_TradeRoute] 贸易路线容量。相邻河流开始回合的单位+5 [ICON_STRENGTH] 战斗力。"),
("en_US", "LOC_UNIT_GEDEMO_ROZWI_DESCRIPTION", "Zimbawe Unique Unit that replaces the Spearman. Stronger and is unlocked earlier. Deals full damage to Walls.[NEWLINE][NEWLINE]Anti Cavalry: +10 [ICON_Strength] Combat Strength when defending against cavalry units."),
("zh_Hans_CN", "LOC_UNIT_GEDEMO_ROZWI_DESCRIPTION", "津巴布韦特色单位，取代枪兵。更强且解锁更早。对城墙造成全额伤害。[NEWLINE][NEWLINE]抗骑兵：防御骑兵单位时额外+10 [ICON_Strength] 战斗力。"),
("en_US", "LOC_ABILITY_MUTOTA_DESCRIPTION", "+5 [ICON_Strength] Combat Strength when starting adjacent to river."),
("zh_Hans_CN", "LOC_ABILITY_MUTOTA_DESCRIPTION", "相邻河流开始回合时+5 [ICON_Strength] 战斗力。"),
("en_US", "LOC_IMPROVEMENT_GEDEMO_DZIMBABWE_DESCRIPTION", "+1 [ICON_FOOD] Food. +2 [ICON_GOLD] Gold.+1 [ICON_FOOD] Food from every adjacent Farm, Camp and Plantation, +1 [ICON_PRODUCTION] from every adjacent Pasture and Quarry. Additional [ICON_FOOD] Food and [ICON_PRODUCTION] Production as you advance through the Civics and Technology Tree. After researching 'Masonry' Technology, Cities have a Dzimbabwe gain +3 [ICON_GREATMERCHANT] Great Merchant points. Only can be built on Hills. Once Buttress is unlocked it can also be built on plains."),
("zh_Hans_CN", "LOC_IMPROVEMENT_GEDEMO_DZIMBABWE_DESCRIPTION", "+1 [ICON_FOOD] 食物、+2 [ICON_GOLD] 金币。每相邻一个农田、营地或种植园+1 [ICON_FOOD] 食物，每相邻一个牧场或采石场+1 [ICON_PRODUCTION] 生产力。随着科技和市政的发展，还将提供更多食物和生产力。解锁“砌砖”后，拥有津巴布韦石城的城市获得+3 [ICON_GREATMERCHANT] 大商人点数。只能建造在丘陵上。解锁“扶壁”后可以建造在平地上。"),
("en_US", "LOC_UNIT_ZIMBABWE_PATHFINDER_NAME", "Zimbawe Pathfinder"),
("zh_Hans_CN", "LOC_UNIT_ZIMBABWE_PATHFINDER_NAME", "津巴布韦探路者"),
("en_US", "LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION_FRONTEND", "{LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION}[NEWLINE][NEWLINE]If 'Tycoons and Investors' Mod is enabled, replaces the Tycoon, is unlocked earlier, cheaper to build and with an additional build charge."),
("zh_Hans_CN", "LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION_FRONTEND", "{LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION}[NEWLINE][NEWLINE]若开启了“大亨与投资人”模组，则替代大亨，解锁更早，造价更低，且拥有额外一次劳动力。"),
("en_US", "LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION", "Zimbawe Unique Unit. Can record the Luxury Resource in plot and then generate that Resource in your territory. Can be used twice."),
("zh_Hans_CN", "LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION", "津巴布韦特色单位。可以记录所在位置的奢侈品资源，并之后将其生成在您的领土内。可以使用2次。"),
("en_US", "LOC_UNIT_ZIMBABWE_PATHFINDER_MONOPOLY_DESCRIPTION_PREFIX", "{LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION}[NEWLINE][NEWLINE]Replaces the Tycoon. Is unlocked earlier, cheaper to build and with an additional build charge.[NEWLINE][NEWLINE]"),
("zh_Hans_CN", "LOC_UNIT_ZIMBABWE_PATHFINDER_MONOPOLY_DESCRIPTION_PREFIX", "{LOC_UNIT_ZIMBABWE_PATHFINDER_DESCRIPTION}[NEWLINE][NEWLINE]替代大亨。解锁更早，造价更低，且拥有额外一次劳动力。[NEWLINE][NEWLINE]"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_RECORD_NAME", "Record Luxury Resource"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_RECORD_NAME", "记录奢侈品资源"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_RECORD_RECORDING", "Recorded Luxury Resource:"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_RECORD_RECORDING", "已记录的奢侈品资源："),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_RECORD_CURRENT", "Active to record"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_RECORD_CURRENT", "激活以记录"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_RECORD_DISABLED_TT", "Must be on a Luxury Resource"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_RECORD_DISABLED_TT", "必须位于奢侈品资源上"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_NAME", "Generate Luxury Resource"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_NAME", "生成奢侈品资源"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_CHARGES", "Can be used {1_num} more {1_num : plural 1?time; other?times;}"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_CHARGES", "还可以使用{1_num}次"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_RECORDING", "Active to generate"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_RECORDING", "激活以生成"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_HAS_RECORD", "Must have a Luxury Resource recorded"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_HAS_RECORD", "需要记录奢侈品资源"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_OWN", "Must be in your terrirory"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_OWN", "必须在您的领土中"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_HAVE_NO_DISTRICT", "Must be not on districts"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_HAVE_NO_DISTRICT", "不能位于区域"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_ON_LAND", "Must be on land tiles"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_ON_LAND", "必须在陆地单元格"),
("en_US", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_ON_WATER", "Must be on water tiles"),
("zh_Hans_CN", "LOC_UNITCOMMAND_PATHFINDER_PLANT_MUST_ON_WATER", "必须在水域单元格");

-- Pack 4
insert or replace into LocalizedText (Language, Tag, Text) values
-- Berbers
("en_US", "LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_XP2_DESCRIPTION", "+50% construction speed towards non-specialty Districts. Aqueduct provides +1 [ICON_FOOD] Food for every adjacenct District, and [ICON_PRODUCION] Production equal to its [ICON_FOOD] Food bonus. Aqueduct buildings are 20% cheaper to purchase. May purchase Aqueduct buildings with [ICON_FAITH] Faith."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_XP2_DESCRIPTION", "建造非专业化区域时+50%建造速度。水渠每相邻一个区域+1 [ICON_FOOD] 食物，并提供等同于 [ICON_FOOD] 食物加成的 [ICON_PRODUCTION] 生产力。购买水渠建筑的费用降低20%且可以用 [ICON_FAITH] 信仰值购买。"),
("en_US", "LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_DESCRIPTION", "{LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_XP2_DESCRIPTION}"),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_DESCRIPTION", "{LOC_TRAIT_CIVILIZATION_CVS_BERBER_UA_XP2_DESCRIPTION}"),
("en_US", "LOC_DISTRICT_FOOD", "+{1_num} [ICON_FOOD] Food from the adjacent {1_Num : plural 1?district; other?districts;}."),
("zh_Hans_CN", "LOC_DISTRICT_FOOD", "+{1_Amount} [ICON_FOOD] 食物来自相邻区域。"),
("en_US", "LOC_TRAIT_LEADER_CVS_DIHYA_UA_DESCRIPTION", "+1 [ICON_MOVEMENT] movement if starting turn in friendly territory. When an enemy unit pillages one of your improvements, all enemy units on or adjacent to that tile with the same owner recieve 30 Damage."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_DIHYA_UA_DESCRIPTION", "单位在友好领土开始回合+1 [ICON_MOVEMENT] 移动力。当敌人的单位劫掠您的改良时，该文明位于或相邻该单元格的所有单位受到30点伤害。"),
("en_US", "LOC_IMPROVEMENT_CVS_BERBER_UI_DESCRIPTION", "+1 [ICON_HOUSING] Housing, +1 extra [ICON_HOUSING] Housing after researching 'Engineering' Technology, +1 extra [ICON_HOUSING] Housing after researching 'Apprenticeship' Technology. +1 [ICON_FOOD] Food to adjacent resources, extra +1 [ICON_PRODUCTION] Production after researching 'Engineering' Technology. Provides +2 [ICON_FOOD] to adjacent Aqueduct and +2 [ICON_PRODUCTION] Production adjacency bonus to Industial Zone. Cannot be worked. Can only be built on flat lands not adjacent to another Foggara. Can be built on Hills and Floodplains after researching 'Iron Working' Technology."),
("zh_Hans_CN", "LOC_IMPROVEMENT_CVS_BERBER_UI_DESCRIPTION", "+1 [ICON_HOUSING] 住房，解锁“工程”科技后额外+1 [ICON_HOUSING] 住房，解锁“学徒”科技后额外+1 [ICON_HOUSING] 住房。为相邻资源+1 [ICON_FOOD] 食物，解锁“工程”科技后额外+1 [ICON_PRODUCTION] 生产力。为相邻水渠+2 [ICON_FOOD] 食物，为工业区提供+2 [ICON_PRODUCTION] 生产力相邻加成。不能在此单元格工作。只能建造在平坦单元格，且不能相邻另一个柏柏尔井渠。解锁“炼铁术”科技后，允许修建在泛滥平原和丘陵上。"),
("en_US", "LOC_BERBER_UI_FOOD", "+{1_num} [ICON_FOOD] Food from the adjacent Foggara {1_Num : plural 2?improvement; other?improvements;}."),
("zh_Hans_CN", "LOC_BERBER_UI_FOOD", "+{1_Amount} [ICON_FOOD] 食物来自相邻柏柏尔井渠。"),
("en_US", "LOC_BERBER_UI_PRODUCTION", "+{1_num} [ICON_FOOD] Food from the adjacent Foggara {1_Num : plural 2?improvement; other?improvements;}."),
("zh_Hans_CN", "LOC_BERBER_UI_PRODUCTION", "+{1_Amount} [ICON_PRODUCTION] 生产力来自相邻柏柏尔井渠。"),
("en_US", "LOC_UNIT_CVS_BERBER_UU_DESCRIPTION", "Berbers unique unit that replaces the Pikeman. +7 [ICON_STRENGTH] Strength when defending ranged attack, doubled if in friendly territory."),
("zh_Hans_CN", "LOC_UNIT_CVS_BERBER_UU_DESCRIPTION", "柏柏尔特色单位，替代长矛兵。防御远程攻击时+7 [ICON_STRENGTH] 战斗力，位于友好领土时翻倍。"),
("en_US", "LOC_MODIFIER_CVS_BERBER_UU_DEFENDING", "+{1_Amount} Strength when defending ranged attack"),
("zh_Hans_CN", "LOC_MODIFIER_CVS_BERBER_UU_DEFENDING", "防御远程攻击+{1_Amount} 战斗力"),
("en_US", "LOC_MODIFIER_CVS_BERBER_UU_DEFENDING_FRIENDLY", "+{1_Amount} Strength when defending ranged attack in friendly territory."),
("zh_Hans_CN", "LOC_MODIFIER_CVS_BERBER_UU_DEFENDING_FRIENDLY", "位于友好领土防御远程攻击+{1_Amount} 战斗力"),
--城市
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CIRTA", "Cirta"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CIRTA", "锡尔塔"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHENCHELA", "Khenchela"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHENCHELA", "汉舍莱"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MARRAKECH", "Marrakech"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MARRAKECH", "马拉喀什"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_FEZ", "Fez"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_FEZ", "非斯"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ALGERS", "Algers"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ALGERS", "阿尔及尔"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUNIS", "Tunis"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUNIS", "突尼斯"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TLEMCEN", "Tlemcen"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TLEMCEN", "特雷姆森"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAIROUAN", "Kairouan"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAIROUAN", "凯鲁万"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ANNABA", "Annaba"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ANNABA", "安纳巴"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SIGA", "Siga"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SIGA", "西加"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RUSSICADA", "Russicada"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RUSSICADA", "罗西卡达"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIMGAD", "Timgad"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIMGAD", "提姆加德"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GAFSA", "Gafsa"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GAFSA", "加夫萨"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SETIF", "Sétif"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SETIF", "塞提夫"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THAGASTE", "Thagaste"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THAGASTE", "塔加斯特"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TETOUAN", "Tétouan"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TETOUAN", "得土安"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TOUGGOURT", "Touggourt"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TOUGGOURT", "图古尔特"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DARALBAYDA", "Dar al-Bayda"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DARALBAYDA", "达尔贝达"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TANGIER", "Tangier"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TANGIER", "丹吉尔"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SAFI", "Safi"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SAFI", "萨菲"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ORAN", "Oran"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ORAN", "奥兰"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CEUTA", "Ceuta"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_CEUTA", "休达"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAPES", "Kapes"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KAPES", "加贝斯"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SABHA", "Sabha"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SABHA", "塞卜哈"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TRIPOLI", "Tripoli"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TRIPOLI", "的黎波里"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SOUS", "Sous"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SOUS", "苏斯"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MZAB", "M'zab"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MZAB", "姆扎卜"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEILILLA", "Melilla"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEILILLA", "梅利利亚"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SALE", "Salé"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_SALE", "塞拉"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RADAT", "Rabat"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_RADAT", "拉巴特"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEKNES", "Meknes"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEKNES", "梅克内斯"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_OUJDA", "Oujda"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_OUJDA", "乌季达"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHOURIBGA", "Khouribga"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KHOURIBGA", "胡里卜盖"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KENITRA", "Kenitra"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_KENITRA", "盖尼特拉"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BLIDA", "Blida"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BLIDA", "卜利达"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DJELFA", "Djelfa"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_DJELFA", "杰勒法"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THEVESTE", "Theveste"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_THEVESTE", "泰贝萨"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BEJAIA", "Béjaïa"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BEJAIA", "贝贾亚"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIARET", "Tiaret"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TIARET", "提亚雷特"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MOSTAGANEM", "Mostaganem"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MOSTAGANEM", "穆斯塔加奈姆"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TATAOUINE", "Tataouine"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TATAOUINE", "泰塔温"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BAGAI", "Bagai"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_BAGAI", "巴加伊"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MILEVUM", "Milevum"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MILEVUM", "米勒弗姆"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ZARAI", "Zaraï"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ZARAI", "扎拉伊"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUBUNAE", "Tubunae"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_TUBUNAE", "图布那"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MACRI", "Macri"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MACRI", "马克里"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GEMELLAE", "Gemellae"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_GEMELLAE", "格美拉"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEDEA", "Médéa"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_MEDEA", "麦迪亚"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_LAGHOUT", "Laghouat"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_LAGHOUT", "艾格瓦特"),
("en_US", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ERFOUD", "Erfoud"),
("zh_Hans_CN", "LOC_CITY_NAME_CIVILIZATION_CVS_BERBER_ERFOUD", "伊尔富德"),
-- Swahili
("en_US", "LOC_TRAIT_CIVILIZATION_SUK_CORAL_CONSTRUCTION_DESCRIPTION_XP1", "Districts in coastal Cities receive extra Major adjacency bonus from the City Center, and extra standard bonus from being adjacent to a Harbor. "), --International [ICON_TradeRoute] Trade Routes provide +1 [ICON_Gold] Gold per Fishing Boat in the origin city. +1 [ICON_Production] Production from Sea Features.
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_SUK_CORAL_CONSTRUCTION_DESCRIPTION_XP1", "沿海城市中的区域从市中心获得额外大量相邻加成，从港口获得额外标准相邻加成。海洋地貌+1 [ICON_PRODUCTION] 生产力。"),
("en_US", "LOC_TRAIT_LEADER_SUK_HUSUNI_KUBWA_XP2_DESCRIPTION", "Harbours adjacent to a Wonder provide +1 [ICON_TradeRoute] Trade Route Capacity. Patronage of [ICON_GreatPerson] Great People costs 20% less [ICON_GOLD] Gold."), --Patronage of [ICON_GreatPerson] Great People costs 3.33% less [ICON_Gold] Gold for every Wonder built on or adjacent to a Coast tile. The Harbor District provides +1 [ICON_Housing] Housing and +1 [ICON_Culture] Culture, increasing to +3 [ICON_Housing] Housing and +2 [ICON_Culture] Culture if adjacent to a City Center.
("zh_Hans_CN", "LOC_TRAIT_LEADER_SUK_HUSUNI_KUBWA_XP2_DESCRIPTION", "相邻奇观的港口提供+1 [ICON_TradeRoute] 贸易路线，赞助 [ICON_GreatPerson] 伟人消耗的 [ICON_GOLD] 金币减少20%。"), --每座建造在海岸上或与海岸相邻的奇观使赞助 [ICON_GreatPerson] 伟人消耗的 [ICON_GOLD] 金币减少3.33%。港口+1 [ICON_HOUSING] 住房、+1 [ICON_CULTURE] 文化值，若与市中心相邻，则改为+3 [ICON_HOUSING] 住房、+2 [ICON_CULTURE] 文化值。
("en_US", "LOC_BUILDING_SUK_PILLAR_TOMB_XP1_DESCRIPTION", "A building unique to the Swahili. It is cheaper than the Monument which it replaces. +1 [ICON_Culture] Culture, Provides +1 Loyalty per turn in this city. If the city already has maximum Loyalty, also provides an additional +1 [ICON_Culture] Culture. After Calendar is researched, provides an additional +1 [ICON_CULTURE] Culture. International [ICON_TradeRoute] Trade Routes from this city generate +1 [ICON_Gold] Gold, +1 [ICON_Culture] Culture for each of this city’s districts that are within 2 tiles of the City Centre (Capped at +6 [ICON_Gold] )."),
("zh_Hans_CN", "LOC_BUILDING_SUK_PILLAR_TOMB_XP1_DESCRIPTION", "取代纪念碑的斯瓦希里特色建筑。比纪念碑更便宜。提供+1 [ICON_Culture] 文化值。使此城每回合+1忠诚度。若城市忠诚度已达最高，则额外+1 [ICON_Culture] 文化值。研究“历法”科技后，额外+1 [ICON_Culture] 文化值。市中心两个单元格内的每个区域为本城出发的国际 [ICON_TradeRoute] 贸易路线提供+1 [ICON_Culture] 文化值和+1 [ICON_Gold] 金币（上限是+6 [ICON_Culture] 文化值）。"),
("en_US", "LOC_UNIT_SUK_JAHAZI_DESCRIPTION_XP2", "Swahili unique Medieval era support unit. When adjacent to a Jahazi, features on a water tile provide +2 [ICON_Culture] Culture, and Fishing Boats provide +2 [ICON_Gold] Gold. Features on water tiles adjacent to a Jahazi provide +2 [ICON_Tourism] Tourism after researching Conservation. If the Jahazi is in friendly territory, your Naval units within 2 tiles heal +20 HP per turn."),
("zh_Hans_CN", "LOC_UNIT_SUK_JAHAZI_DESCRIPTION_XP2", "斯瓦希里特色中世纪支援单位。相邻的海洋地貌+2 [ICON_Culture] 文化，相邻的渔船+2 [ICON_Gold] 金币。如果在友方领土内，为两个单元格内您的海军单位每回合+20生命值。"),
("en_US", "LOC_UNIT_SWAHILI_DHOW_DESCRIPTION", "Swahili unique unit. Has higher [ICON_STRENGTH] Strength but is more expensive. If 'Industries and Corporations' Mode is enabled, can build a Industry on Sea Luxury."),
("zh_Hans_CN", "LOC_UNIT_SWAHILI_DHOW_DESCRIPTION", "斯瓦希里特色单位。[ICON_STRENGTH] 战斗力更高但更贵。若已开启“行业与公司模式”，可以在海洋奢侈品上建立一个行业。"),
-- Armenia
("en_US", "LOC_TRAIT_CIVILIZATION_CVS_ARMENIA_UA_DESCRIPTION", "Grant a [ICON_GREATPROPHET] Great Prophet when a Vank is built (if you have not received one). +1 [ICON_CULTURE] Culture for every 2 followers of the religion you founded in foreign cities."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_CVS_ARMENIA_UA_DESCRIPTION", "建成凡克修道院时获得一位 [ICON_GREATPROPHET] 大预言家（如果您尚未获得大预言家）。外国城市每有2个您所创立宗教的信徒便+1 [ICON_CULTURE] 文化值。"),
("en_US", "LOC_TRAIT_LEADER_CVS_TIGRANES_II_UA_DESCRIPTION", "Being [ICON_PROMOTION] Promoted or [ICON_GOLD] Upgraded restores the unit's actions. +1 [ICON_MOVEMENT] Movement for units starting on Hills."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_TIGRANES_II_UA_DESCRIPTION", "单位晋升和升级会回复已消耗的行动力。单位在丘陵开始回合时+1 [ICON_MOVEMENT] 移动力。"),
("en_US", "LOC_DISTRICT_CVS_ARMENIA_UI_DESCRIPTION", "A district unique to Armenia that replaces the Holy Site. Major adjacency bonus from adjacency Quarry. +1 [ICON_CULTURE] Culture to Quarries in the city."),
("zh_Hans_CN", "LOC_DISTRICT_CVS_ARMENIA_UI_DESCRIPTION", "亚美尼亚特色区域，取代圣地。相邻采石场获得大量相邻加成。此城中采石场+1 [ICON_CULTURE] 文化值。"),
("en_US", "LOC_CVS_ARMENIA_UI_STONE_CIRCLES_DESCRIPTION", "+{1_Amount} [ICON_FAITH] Faith from adjacent Quarry {1_Num : plural 2?improvement; other?improvements;}."),
("zh_Hans_CN", "LOC_CVS_ARMENIA_UI_STONE_CIRCLES_DESCRIPTION", "+{1_Amount} [ICON_FAITH] 信仰来自相邻采石场。"),
("en_US", "LOC_UNIT_CVS_ARMENIA_UU_DESCRIPTION", "Armenia unique unit that replaces the Horseman. Ignore [ICON_MOVEMENT] Movement cost from hills. +5 [ICON_STRENGTH] Strength when attacking Melee units. May be purchased with [ICON_FAITH] Faith."),
("zh_Hans_CN", "LOC_UNIT_CVS_ARMENIA_UU_DESCRIPTION", "亚美尼亚特色单位，取代骑手。忽略丘陵带来的 [ICON_MOVEMENT] 移动力消耗。攻击近战单位时+5 [ICON_STRENGTH]战斗力。可以用 [ICON_FAITH] 信仰值购买。"),
("en_US", "LOC_UNIT_ARMENIA_APOSTLE_DESCRIPTION", "Armenia unique unit that replaces the Apostle. Unlocked with 'Drama and Poetry' Civic, and can be purchased in cities with a Shrine. Increase 500 Religion pressure in cities within 6 tiles when killed."),
("zh_Hans_CN", "LOC_UNIT_ARMENIA_APOSTLE_DESCRIPTION", "亚美尼亚特色单位，取代使徒。由“戏剧与诗歌”市政解锁，需要神社便可以购买。被击杀时向周围6个单元格内的城市施加500宗教压力。"),
-- Malaysia
("en_US", "LOC_TRAIT_CIVILIZATION_CVS_MALAYSIA_UA_DESCRIPTION", "Coast and Lake tiles provide standard adjacency bonus for Commercial Hubs. Gain 1 [ICON_ENVOY] Envoy when you recuit a [ICON_GREATMERCHANT] Great Merchant. +1 [ICON_ENVOY] Envoys awarded for completing City-State Quests if another Civilization is its Suzerain."),
("zh_Hans_CN", "LOC_TRAIT_CIVILIZATION_CVS_MALAYSIA_UA_DESCRIPTION", "海岸和湖泊单元格可为商业中心提供标准相邻加成。每招募一个 [ICON_GREATMERCHANT] 大商人时+1 [ICON_ENVOY] 使者。首次通往城邦的[ICON_TRADEROUTE] 贸易路线将向该城邦派遣1位 [ICON_ENVOY] 使者。"),
("en_US", "LOC_DISTRICT_CVS_MALAYSIA_UI_DESCRIPTION", "Malaysia Unique District that replaces the Harbor. Citizens working in this district also yield [ICON_GREATMERCHANT] Great Merchant points. International trade routes from this City provide +1 [ICON_GOLD] Gold for each Fishing Boat owned by this City.[NEWLINE]Removes the [ICON_MOVEMENT] Movement penalty for embarking and disembarking to and from this tile. Must be built on Coast or Lake Terrain adjacent to land. +2 [ICON_HOUSING] Housing if this city is adjacent to a Coast or a Lake. Fishing Boats provide +1 [ICON_FOOD] Food in this city. +10% [ICON_PRODUCTION] production towards all naval units."),
("zh_Hans_CN", "LOC_DISTRICT_CVS_MALAYSIA_UI_DESCRIPTION", "马来西亚特色区域，取代港口。专家产出额外的 [ICON_GREATMERCHANT] 大商人点数。本城拥有的每个渔船为从该城出发的国际商路+1 [ICON_GOLD] 金币。[NEWLINE]取消从该单元格上下船的 [ICON_MOVEMENT] 移动力消耗。必须修建在和陆地相邻的海岸或湖泊单元格上。如此城与海岸或湖边相邻，则+2 [ICON_HOUSING] 住房。为本城的渔船 +1 [ICON_FOOD] 食物。建造海军单位加速10%。"),
("en_US", "LOC_UNIT_CVS_MALAYSIA_UU_DESCRIPTION", "Malaysia Unique Unit that replaces the Caravel. Stronger. Combat victories heal 30 [ICON_Damaged] Health and provide 20 [ICON_GREATMERCHANT] Great Merchant Points."),
("zh_Hans_CN", "LOC_UNIT_CVS_MALAYSIA_UU_DESCRIPTION", "马来西亚特色单位，取代轻快帆船, 比轻快帆船战斗力更强，每次击杀敌方单位会恢复30 [ICON_Damaged] 生命值，击杀单位后将获得20 [ICON_GREATMERCHANT] 大商人点数。"),
("en_US", "LOC_TRAIT_LEADER_CVS_ISKANDAR_UA_DESCRIPTION", "Cities within 3 tiles of Coast or Lake gain +1 [ICON_CITIZEN] Population and +1 [ICON_AMENITIES] Amenity."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_ISKANDAR_UA_DESCRIPTION", "建立在海岸或者湖泊3个单元格内的城市+1 [ICON_CITIZEN] 人口、+1 [ICON_AMENITIES] 宜居度。"),
("en_US", "LOC_TRAIT_LEADER_CVS_TUN_PERAK_UA_DESCRIPTION", "In [ICON_GLORY_GOLDEN_AGE] Golden Age, [ICON_CITIZEN] citizens provides +0.3 [ICON_CULTURE] Culture, units gain +3 [ICON_STRENGTH] Combat Strength. Each Government Plaza and Government Plaza building provides +3 [ICON_PRODUCTION] Production and +2 Influence Points."),
("zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_TUN_PERAK_UA_DESCRIPTION", "处于 [ICON_GLORY_GOLDEN_AGE] 黄金或英雄时代时，每位 [ICON_CITIZEN] 市民+0.3 [ICON_CULTURE] 文化值，所有战斗单位+3 [ICON_STRENGTH] 战斗力。每个市政广场和市政广场建筑+3 [ICON_PRODUCTION] 生产力、+2影响力点数。"),
("en_US", "LOC_UNIT_CVS_TUN_PERAK_UU_DESCRIPTION", "Malaysia Unique Unit that replaces the Swordsman. Stronger, and can ignore Zone of Control. +2 [ICON_MOVEMENT] Movement if embarked."),
("zh_Hans_CN", "LOC_UNIT_CVS_TUN_PERAK_UU_DESCRIPTION", "马来西亚特色单位，取代剑士。具有更高的战斗力，且无视区域控制。如果在海岸和湖泊单元格上开始一个回合，会获得2 [ICON_MOVEMENT] 移动力加成。"),
("en_US", "LOC_DISTRICT_COMMERCIAL_HUB_GOLD", "+{1_num} [ICON_GOLD] Gold from the adjacent Coast and Lake {1_Num : plural 1?tile; other?tiles;}."),
("zh_Hans_CN", "LOC_DISTRICT_COMMERCIAL_HUB_GOLD", "+{1_num} [ICON_GOLD] 金币来自相邻的海岸和湖泊单元格。"),
("en_US", "LOC_TUN_PERAK_COMBAT_PREVIEW_TEXT", "from Kingmaker"),
("zh_Hans_CN", "LOC_TUN_PERAK_COMBAT_PREVIEW_TEXT", "来自造王者"),
("en_US", "LOC_ABILITY_CVS_TUN_PERAK_UU_DESCRIPTION", "Ignores Zone of Control"),
("zh_Hans_CN", "LOC_ABILITY_CVS_TUN_PERAK_UU_DESCRIPTION", "无视区域控制");
insert or replace into LocalizedText (Language, Tag, Text) select
"en_US", "LOC_TRAIT_LEADER_CVS_TUN_PERAK_UA_DESCRIPTION", "In [ICON_GLORY_GOLDEN_AGE] Golden Age, [ICON_CITIZEN] citizens provide +0.3 [ICON_CULTURE] Culture, units gain +3 [ICON_STRENGTH] Combat Strength. Each Government Plaza, Diplomatic Quarter and building in these districts provides +3 [ICON_PRODUCTION] Production and +2 Influence Points."
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');
insert or replace into LocalizedText (Language, Tag, Text) select
"zh_Hans_CN", "LOC_TRAIT_LEADER_CVS_TUN_PERAK_UA_DESCRIPTION", "处于 [ICON_GLORY_GOLDEN_AGE] 黄金或英雄时代时，每位 [ICON_CITIZEN] 市民+0.3 [ICON_CULTURE] 文化值，所有战斗单位+3 [ICON_STRENGTH] 战斗力。每个市政广场、外交区及这些区域中的建筑+3 [ICON_PRODUCTION] 生产力、+2影响力点数。"
where exists (select Tag from LocalizedText where Tag = 'LOC_CIVILIZATION_ETHIOPIA_NAME');