insert or replace into LocalizedText (Language, Tag, Text) values
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_1", "Baku is situated on the south of the Abşeron yarımadası and on the coast of the Caspian sea. It is currentlly the capital city of Azerbaijan. "),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_1", "巴库位于高加索山向东延伸入里海的阿普歇伦半岛南部，目前是阿塞拜疆共和国首都。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_2", "Archaeological sites on the Abşeron yarımadası can date back to the Bronze Age. During the 1st Century B.C., Roman legions passed through, leaving the first known written records of settlements here. It was not until the 8th Century A.D., when Baku became under the control of the Shirvinshah, did it become a capital. The previous capital of Shirvin, Shamakhi, was devastated by an earthquake, and it was particularly vunerable to invasions. Therefore, the Shah decided to move his capital to Baku. Multiple Shahs constructed palaces, fortresses and towers here, all becoming invaluable cultural heritage in Baku."),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_2", "阿普歇伦半岛在青铜时代已经留下了遗迹，公元1世纪时，罗马军团途经此处，留下了对这个地区定居点的最早的一批书面记录。巴库真正成为大城市还要到公元8世纪此地成为希尔万沙阿的领土。1191年，希尔万之前的首都沙马基被地震摧毁了一部分，加之之前这个首都经常受可萨人和罗斯人的侵袭，希尔万沙阿迁都巴库。历代希尔万沙阿在此建立了大量宫殿、城堡和塔楼，这些都成为了巴库珍贵的文化遗产。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_3", "In the 16th Century, Qara Qoyunlu and Aq Qoyunlu both craved for the commercial and strategic values. After the demise of the Aq Qoyunlu Dynasty, Isma‘il I of the Safavid Empire incorporated Baku into its sphere of influence, turning Shirvin into a vassal. His successor abolished the throne of Shirvin and turned Baku into a Persian province."),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_3", "到16世纪，黑羊、白羊王朝觊觎着巴库的军事和商业价值。白羊灭亡之后，波斯萨法维王朝的伊斯玛仪一世又将巴库纳入自己的势力范围。他1501年占领了巴库，把希尔万变成了自己的傀儡国，他的后继者塔赫马斯普又废黜了希尔万沙阿并把巴库变成了波斯的一个省。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_4", "Struggles for dominance in the Caucasians between the Safavid and Ottoman empires saw multiple shifts in ownership of Baku. In the 17th Century, Baku was occupied by the emerging Nader Shah of the Afsharid Dynasty. After his death, the Caucassian Khanate, a Persian vassal, was established by Iranians, with Azerbajanis as Khans. The Russian Tsardom invaded Persia and took Baku."),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_4", "萨法维和奥斯曼在高加索的争霸战争使得巴库几经易手。到17世纪，巴库被崛起的阿夫沙尔王朝的纳迪尔沙阿占领。他死后，伊朗在此建立了高加索汗国，由阿塞拜疆人做可汗，作为波斯的臣属。直到19世纪沙俄入侵波斯，该地被沙俄占领。"),
("en_US", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_5", "Oil was discovered here by Russians, but due to the feeble control the Tsardom exerts on frontier regions and the weak industrial production, extraction was limited. After the October Revolution, the Soviet Union  demanded oil resources in the Caucassians, and Baku became the center of petroleum chemistry in the Caucassians. It played a decisive part in the victory of the Soviet Union in WWII. However, mineral resources cannot escape eventual depletion. In the 1980s, due to the depletion of local resources and the utilization of Siberian resources, Baku lost its status as an oil hub, but the Soviet Union developed other industrial departments here. Baku avoided becoming a ghost town due to its status as a political and economic center and industrial heritage left by the Soviets and continued to develop modern industries. "),
("zh_Hans_CN", "LOC_PEDIA_CITYSTATES_PAGE_CIVILIZATION_HATTUSA_CHAPTER_HISTORY_PARA_5", "虽然沙俄时期该地已经发现了石油，但是沙俄落后的工业和对边疆地区低下的控制能力使得沙俄对这些石油的开发不多。十月革命以后，急需石油进行工业建设的苏维埃政权开始大力开发高加索的石油资源，巴库则成为了高加索的石油工业中心。在二战中高加索油田为苏军的胜利做了极大地贡献。然而，开发矿产资源为主的工业总有枯竭的时候。到20世纪80年代，因为自身的枯竭和西伯利亚资源的开发，巴库几乎失去了石油城的地位，而苏联在此进行了许多其它门类的重工业建设。到苏联解体以后，因为苏联的工业遗产和巴库经济政治中心的地位，巴库没有向其他资源型城市那样化为空城，而是着力于现代化的产业建设。");