insert or replace into LocalizedText
	(Language,		Tag,																																	Text)
values
-- 264988360_RF'Sukritacts Ingolfur Arnarson (Iceland)'CN_Add_FI
	("zh_Hans_CN",	"LOC_CIVILIZATION_SUK_ICELAND_NAME",																									"冰岛"),
	("zh_Hans_CN",	"LOC_CIVILIZATION_SUK_ICELAND_DESCRIPTION",																								"冰岛帝国"),
	("zh_Hans_CN",	"LOC_CIVILIZATION_SUK_ICELAND_ADJECTIVE",																								"冰岛的"),
	("zh_Hans_CN",	"LOC_CIVILIZATION_SUK_ICELAND_DESCRIPTION_JFD_CIVILIZATION",																			"冰岛文明"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_NAME",																				"冰岛人萨迦"),
	("en_US",		"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_DESCRIPTION_XP2",																	"Earn extra 2 [ICON_GREATWRITER] Great Writer point for each [ICON_GLORY_NORMAL_AGE] era score earned, and earn more more [ICON_GreatWriter] Great Writer Points as you advance through the Civics and Technology Tree. Natural Wonders, Volcanoes, Volcanic Soil and Geothermal Fissures provide +1 Appeal to adjacent tiles, and these features each provide +1 [ICON_Amenities] Amenity in the city."),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_DESCRIPTION_XP2",																	"每获得1点 [ICON_GLORY_NORMAL_AGE] 时代得分，额外获得2点[ICON_GREATWRITER] 大作家点数，随着科技与市政的研究，还将提供更多[ICON_GREATWRITER] 大作家点数。火山、火山土、地热裂缝和自然奇观单元格为相邻单元格+1魅力。城市中每有一种火山、火山土、地热裂缝和自然奇观地貌，则+1 [ICON_Amenities] 宜居度。"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_SCIENCE",																			"+{1_num} [ICON_Science] 科技值 来自相邻 {1_Num : plural 1?自然奇观; other?自然奇观;}"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_CULTURE",																			"+{1_num} [ICON_Culture] 文化值 来自相邻 {1_Num : plural 1?自然奇观; other?自然奇观;}"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_GOLD",																				"+{1_num} [ICON_Gold] 金币 来自相邻 {1_Num : plural 1?自然奇观; other?自然奇观;}"),
	("zh_Hans_CN",	"LOC_TRAIT_CIVILIZATION_SUK_SAGAS_OF_THE_ICELANDERS_NOTIFICATION",																		"{1}书写了传奇来纪念历史时刻，奖励您文明{2}点 [ICON_GreatWriter] 大作家点数。"),
	("zh_Hans_CN",	"LOC_UNIT_SUK_LAWSPEAKER_NAME",																											"法律讲述官"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_CLASS_SUK_LAWSPEAKER_NAME",																											"法律讲述官"),
	("en_US",	"LOC_GREAT_PERSON_CLASS_SUK_LAWSPEAKER_NAME",																											"Lawspeaker"),
	("zh_Hans_CN",	"LOC_UNIT_SUK_LAWSPEAKER_DESCRIPTION",																									"冰岛特色伟人，在建造市政广场区域及其建筑时获得1名，首次采用某一级政府时获得1名，如果是为世界首个采用该级政体的文明，则额外获得1名。产生独特加成。"),
	("zh_Hans_CN",	"LOC_PEDIA_UNITS_PAGE_UNIT_SUK_LAWSPEAKER_CHAPTER_HISTORY_PARA_1",																		"[NEWLINE][NEWLINE]法律讲述官 (lögsögumadur) 是阿尔廷自由民议会中的高级官员。他在冰岛还没有书面文字的时候，法律讲述官的职责是在议会上背诵冰岛的法律。他们背诵议会程序的法律，主持法庭会议，并解决争端。法律讲述官被认为是在“法律岩”上向议会发表讲话的，那里是宣布判决、发表重要讲话的地方，也是议会正式开幕和解散的地方。由于旧联邦时期是冰岛社会的一个变革时期，关于权力和宗教的争端给社会和议会的工作带来了影响，所以关于议会和法律发言人的作用还有很多不清楚的地方。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_AMPHITHEATER_DUMMY",																						"若此城尚未拥有可放置 [ICON_GreatWork_Writing] 著作的古罗马剧场，则立即建成一个古罗马剧场，且额外+2 [ICON_GreatWork_Writing] 著作槽位。若非上述情况，则此城每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Culture] 文化值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_LIBRARY_DUMMY",																								"若此城尚未拥有可放置 [ICON_GreatWork_Writing] 著作的图书馆，则立即建成一个图书馆，且额外+2 [ICON_GreatWork_Writing] 著作槽位。若非上述情况，则此城每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Science] 科技值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_SHRINE_DUMMY",																								"若此城尚未拥有可放置 [ICON_GreatWork_Writing] 著作的神社，则立即建成一个神社，且额外+2 [ICON_GreatWork_Writing] 著作槽位。若非上述情况，则此城每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Faith] 信仰值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_MARKET_DUMMY",																								"若此城尚未拥有可放置 [ICON_GreatWork_Writing] 著作的市场，则立即建成一个市场，且额外+2 [ICON_GreatWork_Writing] 著作槽位。若非上述情况，则此城每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Gold] 金币。"),
	("en_US",		"LOC_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_ACTIVE",																					"City Center on tiles with Charming Appeal provide +1 [ICON_Culture] Culture, +1 [ICON_FOOD] Food and +1 [ICON_PRODUCTION] Production, and double on tiles with Breathtaking Appeal."),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_SKAFTI_THORODDSSON_ACTIVE",																					"位于魅力为“迷人的”单元格上的市中心+1 [ICON_CULTURE] 文化值，+1 [ICON_FOOD] 食物和+1 [ICON_PRODUCTION] 生产力，若位于惊艳单元格则翻倍。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_SNORRI_STURLUSON_ACTIVE",																					"每次招募一位 [ICON_GreatWriter] 大作家可奖励 [ICON_Culture] 文化值。[ICON_GreatWork_Writing] 著作额外+50% [ICON_Culture] 文化值。"),
	("en_US",		"LOC_GREATPERSON_LAWSPEAKER_ULFLJOTR_ACTIVE",																							"Torfbæir on tiles with Charming Appeal provide +2 [ICON_Culture] Culture and +2 [ICON_GreatWriter] Great Writer Points, and double on tiles with Breathtaking Appeal."),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_ULFLJOTR_ACTIVE",																							"位于魅力为“迷人的”单元格上的草屋提供+2 [ICON_Culture] 文化值，+2 [ICON_GreatWriter] 大作家点数，若位于惊艳单元格则翻倍。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_HRAFN_HAENGSSON_ACTIVE",																					"该剧院广场的 [ICON_Culture] 文化值相邻加成翻倍。所在城市的每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Culture] 文化值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_THORGEIR_LJOSVETNINGAGODI_ACTIVE",																			"每次招募一位 [ICON_GreatWriter] 大作家可奖励 [ICON_Faith] 信仰值。所在城市的每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Faith] 信仰值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_OLAFR_THORTHARSON_ACTIVE",																					"该剧院广场可提供等同于自身 [ICON_Culture] 文化值相邻加成的 [ICON_Science] 科技值。所在城市的每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Science] 科技值。"),
	("zh_Hans_CN",	"LOC_GREATPERSON_LAWSPEAKER_MARKUS_SKEGGJASON_ACTIVE",																					"每次招募一位 [ICON_GreatWriter] 大作家可奖励 [ICON_Gold] 金币。所在城市的每本 [ICON_GreatWork_Writing] 著作可奖励{Amount} [ICON_Gold] 金币。"),
	("zh_Hans_CN",	"LOC_ABILITY_SUK_LAWSPEAKER_RECRUIT_WRITER_MESSAGE",																					"{1_Bonus} 来自于招募大作家“{2_WriterName}”的奖励"),
	("zh_Hans_CN",	"LOC_ABILITY_SUK_LAWSPEAKER_RECRUIT_WRITER_SUBMESSAGE",																					"{3_Color}+{1_num}[ENDCOLOR] {2_FontIcon}"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_NAME",																										"草屋"),
	("en_US",		"LOC_DISTRICT_SUK_TORFBAEIR_XP2_DESCRIPTION",																							"A district unique to Iceland, replacing the Aqueduct district. Unlock in Early Empire civic.[NEWLINE][NEWLINE]Instead of the Aqueduct's usual restrictions and bonuses, Torfbæir provide +2 [ICON_Housing] Housing, +1 [ICON_Food] Food, +1 [ICON_Production] Production. Increases to +3 [ICON_Housing], +2 [ICON_Food], +2 [ICON_Production], on Charming tiles, or to +4 [ICON_Housing], +3 [ICON_Food], +3 [ICON_Production] on Breathtaking tiles. No adjacency bonus to Industrial Zones.[NEWLINE][NEWLINE]+1 [ICON_Amenities] Amenity if built on a Geothermal Fissure or Volcanic Soil.+1 Appeal to adjacent tiles. Prevents [ICON_Food] Food loss during Drought. Cannot be built on Desert tiles."),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_XP2_DESCRIPTION",																							"冰岛特色区域，取代蓄水池。[NEWLINE][NEWLINE]取消了通常的限制和加成，提供+2 [ICON_Housing] 住房、+1 [ICON_Food] 食物、+1 [ICON_Production] 生产力；建造在魅力为“迷人的”单元格上时，提升至+3 [ICON_Housing] 住房、+2 [ICON_Food] 食物、+2 [ICON_Production] 生产力；建造在魅力为“惊艳的”单元格上时，提升至+4 [ICON_Housing] 住房、+3 [ICON_Food] 食物、+3 [ICON_Production] 生产力。为相邻单元格+1魅力。建造在火山土或地热裂缝上+1 [ICON_AMENITIES] 宜居度。不能建造在沙漠上。"),
	("en_US",		"LOC_DISTRICT_SUK_TORFBAEIR_XP2_FRONTEND_DESCRIPTION",																					"A district unique to Iceland, replacing the Aqueduct district. Unlock in Early Empire civic.[NEWLINE][NEWLINE]Instead of the Aqueduct's usual restrictions and bonuses, Torfbæir provide +2 [ICON_Housing] Housing, +1 [ICON_Food] Food, +1 [ICON_Production] Production. Increases to +3 [ICON_Housing], +2 [ICON_Food], +2 [ICON_Production], on Charming tiles, or to +4 [ICON_Housing], +3 [ICON_Food], +3 [ICON_Production] on Breathtaking tiles. No adjacency bonus to Industrial Zones.[NEWLINE][NEWLINE]+1 [ICON_Amenities] Amenity if built on a Geothermal Fissure or Volcanic Soil.+1 Appeal to adjacent tiles. Prevents [ICON_Food] Food loss during Drought. Cannot be built on Desert tiles."),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_XP2_FRONTEND_DESCRIPTION",																					"冰岛特色区域，取代蓄水池，[NEWLINE][NEWLINE]取消了通常的限制和加成，提供+2 [ICON_Housing] 住房、+1 [ICON_Food] 食物、+1 [ICON_Production] 生产力；建造在魅力为“迷人的”单元格上时，提升至+3 [ICON_Housing] 住房、+2 [ICON_Food] 食物、+2 [ICON_Production] 生产力；建造在魅力为“惊艳的”单元格上时，提升至+4 [ICON_Housing] 住房、+3 [ICON_Food] 食物、+3 [ICON_Production] 生产力。为相邻单元格+1魅力。建造在火山土或地热裂缝上+1 [ICON_AMENITIES] 宜居度。不能建造在沙漠上。"),
	("zh_Hans_CN",	"LOC_PEDIA_DISTRICTS_PAGE_DISTRICT_SUK_TORFBAEIR_CHAPTER_HISTORY_PARA_1",																"[NEWLINE][NEWLINE]当看到冰岛的图片时，一定会出现看起来小巧可爱的草屋（Torfbæir）。由于冰岛缺乏树木，用草皮建造是一种流行的建筑材料，厚厚的草皮墙对抵御寒冷很有用。这种用草皮建筑的技术最早出现在9至11世纪欧洲维京时代的巅峰时期，随着北欧和不列颠定居者的到来而产生。历史记录表明，直到19世纪末，多达50%的冰岛住宅是由草皮构建构成的，尽管这一数字在20世纪开始下降。到1960年，冰岛有234个有人居住的草皮住宅，其中大部分在接下来的十年中被遗弃。"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_BASE_FOOD",																									"+{1_num} [ICON_Food] 食物"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_BASE_PRODUCTION",																							"+{1_num} [ICON_Production] 生产力"),
	("en_US",		"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_PRODUCTION",																							"+{1_num} [ICON_Production] Production from the tile's Appeal."),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_PRODUCTION",																							"+{1_num} [ICON_Production] 生产力 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_FOOD",																								"+{1_num} [ICON_Food] 食物 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_CULTURE",																							"+{1_num} [ICON_Culture] 文化值 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BASE",																						"无吸引力及更差的"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_CHARMING",																					"迷人的"),
	("zh_Hans_CN",	"LOC_DISTRICT_SUK_TORFBAEIR_APPEAL_HOUSING_BREATHTAKING",																				"惊艳的"),
	("zh_Hans_CN",	"LOC_LEADER_SUK_INGOLFUR_NAME",																											"殷格·亚纳逊"),
	("zh_Hans_CN",	"LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_NAME",																						"定居书"),
	("en_US",		"LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_XP2_DESCRIPTION",																				"Settlers and Recon units receive +1 [ICON_Movement] Movement, +1 Sight. Recon units can escort moving civilian and support units at their [ICON_MOVEMENT] Movement speed. Cities on tiles with Charming Appeal or better receive Loyalty equal to the tile’s Appeal. When placing a district on a tile with Breathtaking Appeal, receive a burst of [ICON_Production] Production towards that district."),
	("zh_Hans_CN",	"LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_XP2_DESCRIPTION",																				"开拓者和侦查单位+1 [ICON_MOVEMENT] 移动力并+1视野范围。侦查单位可利用自身的 [ICON_MOVEMENT] 移动力护送平民和支援单位。建造在迷人以上单元格的城市获得额外的忠诚度，等于其市中心所在单元格的魅力。建造在惊艳单元格的区域直接获得33%建造进度。"),
	("zh_Hans_CN",	"LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_MESSAGE",																						"[COLOR_FLOAT_PRODUCTION]+{1_num}[ENDCOLOR] [ICON_Production]"),
	("zh_Hans_CN",	"LOC_UNIT_SUK_BOOK_OF_SETTLEMENTS_DESCRIPTION",																							"+1 [ICON_Movement] 移动力，+1视野。（{LOC_TRAIT_LEADER_SUK_BOOK_OF_SETTLEMENTS_NAME}）"),
	("zh_Hans_CN",	"LOC_SUK_BOOK_OF_SETTLEMENTS_APPEAL_DISTRICT_CAMPUS",																					"+{1_num} [ICON_Science] 科技值 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_SUK_BOOK_OF_SETTLEMENTS_APPEAL_DISTRICT_THEATER",																					"+{1_num} [ICON_Culture] 文化值 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_SUK_BOOK_OF_SETTLEMENTS_APPEAL_DISTRICT_COMMERCIAL_HUB",																			"+{1_num} [ICON_Gold] 金币 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_SUK_BOOK_OF_SETTLEMENTS_APPEAL_DISTRICT_HOLY_SITE",																				"+{1_num} [ICON_Faith] 信仰值 来自 单元格魅力"),
	("zh_Hans_CN",	"LOC_AGENDA_SUK_BAY_OF_SMOKE_NAME",																										"雷克雅未克"),
	("zh_Hans_CN",	"LOC_AGENDA_SUK_BAY_OF_SMOKE_DESCRIPTION",																								"喜欢积极探索地图和定居在自然奇观附近的文明，厌恶对探索不感兴趣的文明。"),
	("zh_Hans_CN",	"LOC_DIPLO_KUDO_LEADER_SUK_INGOLFUR_REASON_ANY",																						"（您拥有自然奇观，并正在探索地图）"),
	("zh_Hans_CN",	"LOC_DIPLO_MODIFIER_SUK_BAY_OF_SMOKE_KUDO",																								"英格尔夫欣赏你的自然奇观和冒险精神。"),
	("zh_Hans_CN",	"LOC_DIPLO_WARNING_LEADER_SUK_INGOLFUR_REASON_ANY",																						"（您没有探索地图）"),
	("zh_Hans_CN",	"LOC_DIPLO_MODIFIER_SUK_BAY_OF_SMOKE_WARNING",																							"你缺乏对探索的兴趣，英格尔夫感到失望。"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_REYKJAVIK",																									"雷克雅未克"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_THINGVELLIR",																								"辛格韦德利"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_HUSAVIK",																									"胡萨维克"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_SKALHOLT",																									"斯考尔霍特"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_HOLAR",																										"希拉"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_AKUREYRI",																									"阿克雷里"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_SEYTHISFJORTHUR",																							"塞济苏菲厄泽"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_GARTHABAER",																									"伽阿伯"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_ISAFJORTHUR",																								"伊萨菲厄泽"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_SAUTHARKROKUR",																								"斯卡加"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_BORGARNES",																									"博尔加内斯"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_GARTHUR",																									"加尔泽"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_AKRANES",																									"阿克拉内斯"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_GRINDAVIK",																									"格林达维克"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_SELFOSS",																									"塞尔福斯"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_HAFNARFJORTHUR",																								"哈夫纳夫约杜尔"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_VESTMANNAEYJAR",																								"韦斯特曼纳"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_KOPAVOGUR",																									"科帕沃于尔"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_KEFLAVIK",																									"凯夫拉维克"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_EGILSSTATHIR",																								"埃伊尔斯塔济"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_NESKAUPSTATHUR",																								"内斯克伊斯塔泽"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_STYKKISHOLMUR",																								"斯蒂斯基霍尔米"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_MOSFELLSBAER",																								"莫斯费德斯拜尔"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_HVERAGERTHI",																								"惠拉盖尔济"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_THORLAKSHOFN",																								"奥拉克什"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_ALFTANES",																									"阿尔法涅斯"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_HOFN",																										"霍芬"),
	("zh_Hans_CN",	"LOC_CITY_NAME_SUK_ICELAND_SANDGERTHI",																									"桑得格斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_1",																										"斯诺里"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_2",																										"英格维"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_3",																										"哈拉尔德"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_4",																										"西格夫斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_5",																										"乌伏"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_6",																										"提尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_7",																										"巴尔德"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_8",																										"古迪富尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_9",																										"梭迩"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_10",																										"艾伊瑟"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_1",																										"西格加"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_2",																										"奥德龙"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_3",																										"阿尔弗希尔德"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_4",																										"恩娜"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_5",																										"拉格海乌尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_6",																										"黑斯露"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_7",																										"艾迪斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_8",																										"伊伦纳"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_9",																										"阿尔弗里德"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_10",																									"劳菲"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_1",																								"英戈尔富"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_2",																								"克里斯蒂安"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_3",																								"埃米利"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_4",																								"奥拉夫"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_5",																								"古蒙杜尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_6",																								"阿纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_7",																								"乔恩"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_8",																								"乔翰"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_9",																								"汤玛士"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_10",																								"比约恩"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_1",																								"凯瑟琳"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_2",																								"弗雷雅"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_3",																								"海尔加"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_4",																								"希尔杜尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_5",																								"玛格丽特"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_6",																								"霍格纳"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_7",																								"伊尔萨"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_8",																								"比约克"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_9",																								"奥图斯塔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_10",																								"哈尔多拉"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_1_GENITIVE",																								"斯诺拉"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_2_GENITIVE",																								"英格瓦"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_3_GENITIVE",																								"哈拉尔兹"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_4_GENITIVE",																								"西格夫斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_5_GENITIVE",																								"乌珐"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_6_GENITIVE",																								"提斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_7_GENITIVE",																								"巴尔德斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_8_GENITIVE",																								"古迪富尔斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_9_GENITIVE",																								"梭迩拉"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MALE_10_GENITIVE",																								"艾伊西斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_1_GENITIVE",																							"西格鲁纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_2_GENITIVE",																							"奥德鲁纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_3_GENITIVE",																							"阿尔弗希达尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_4_GENITIVE",																							"恩努"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_5_GENITIVE",																							"拉格海萨尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_6_GENITIVE",																							"黑斯鲁纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_7_GENITIVE",																							"艾迪萨尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_8_GENITIVE",																							"伊伦纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_9_GENITIVE",																							"阿尔弗里萨尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_FEMALE_10_GENITIVE",																							"劳菲加尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_1_GENITIVE",																						"英戈尔夫斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_2_GENITIVE",																						"克里斯蒂安斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_3_GENITIVE",																						"埃米利斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_4_GENITIVE",																						"奥拉夫斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_5_GENITIVE",																						"古蒙杜尔斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_6_GENITIVE",																						"阿纳尔斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_7_GENITIVE",																						"乔恩斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_8_GENITIVE",																						"乔翰斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_9_GENITIVE",																						"汤玛士"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_MALE_10_GENITIVE",																						"比约恩斯"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_1_GENITIVE",																						"凯瑟琳纳尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_2_GENITIVE",																						"弗雷鸠"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_3_GENITIVE",																						"海尔鸪"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_4_GENITIVE",																						"希尔达尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_5_GENITIVE",																						"玛格丽塔尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_6_GENITIVE",																						"霍格努"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_7_GENITIVE",																						"伊尔苏"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_8_GENITIVE",																						"比约卡尔"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_9_GENITIVE",																						"奥图斯途"),
	("zh_Hans_CN",	"LOC_CITIZEN_SUK_ICELAND_MODERN_FEMALE_10_GENITIVE",																					"哈尔多鲁"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_THJORSA_NAME",																											"肖尔索河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_HVITA_NAME",																											"惠特河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_FNJOSKA_NAME",																											"弗纽斯特河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_KUTHAFLJOT_NAME",																										"库萨弗廖特河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_SKJALFANDAFLJOT_NAME",																									"斯乔尔万达河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_JOKULSA_A_FJOLLUM_NAME",																								"菲约德勒姆冰河"),
	("zh_Hans_CN",	"LOC_NAMED_RIVER_JOKULSA_A_DAL_NAME",																									"达尔冰河"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_ESJAN_NAME",																										"埃夏山"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_HOFSJOKULL_NAME",																									"霍夫斯冰川"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_VATNAJOKULL_NAME",																									"瓦特纳冰原"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_LANGJOKULL_NAME",																									"朗格冰川"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_MYRDALSJOKULL_NAME",																								"米达尔斯冰原"),
	("zh_Hans_CN",	"LOC_NAMED_MOUNTAIN_LANDMANNALAUGAR_NAME",																								"兰德曼纳劳卡山脉"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_HEKLA_NAME",																											"海克拉火山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_BARTHARBUNGA_NAME",																									"巴达本加山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_KATLA_NAME",																											"卡特拉火山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_KRAFLA_CALDERA_NAME",																								"克拉夫拉火山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_ASKJA_CALDERA_NAME",																									"阿斯恰火山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_ELDFELL_NAME",																										"埃尔德菲尔火山"),
	("zh_Hans_CN",	"LOC_NAMED_VOLCANO_THRIHNJUKAGIGUR_NAME",																								"斯瑞努卡基古火山"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_THINGVALLAVATN_NAME",																									"辛格瓦尔德拉湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_MYVATN_NAME",																											"米湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_KERITH_NAME",																											"凯瑞斯火山口湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_OSKJUVATN_NAME",																										"厄斯克湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_JOKULSARLON_NAME",																										"冰河湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_LAGARFLJOT_NAME",																										"拉加尔湖"),
	("zh_Hans_CN",	"LOC_NAMED_LAKE_HVITARVATN_NAME",																										"克维塔湖"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_BAKKAFLOI_NAME",																											"巴卡湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_FAXAFLOI_NAME",																											"法赫萨湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_GRUNNAVIK_NAME",																											"格伦纳维湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_HERADSFLOI_NAME",																										"赫拉德斯湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_HUNAFLOI_NAME",																											"胡纳湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_THISTILFJORTHUR_NAME",																									"锡斯蒂尔菲厄泽"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_BREITHAFJORTHUR_NAME",																									"布雷扎湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_ISAFJARTHARDJUP_NAME",																									"伊萨深峡湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_SKAGAFJORTHUR_NAME",																										"斯卡加峡湾"),
	("zh_Hans_CN",	"LOC_NAMED_SEA_EYJAFJORTHUR_NAME",																										"埃亚峡湾"),
	("zh_Hans_CN",	"LOC_CIVINFO_SUK_ICELAND_LOCATION",																										"欧洲"),
	("zh_Hans_CN",	"LOC_CIVINFO_SUK_ICELAND_SIZE",																											"约39.7万平方英里（10.27万平方公里）"),
	("zh_Hans_CN",	"LOC_CIVINFO_SUK_ICELAND_POPULATION",																									"33万8349（2017年）"),
	("zh_Hans_CN",	"LOC_CIVINFO_SUK_ICELAND_CAPITAL",																										"雷克雅未克"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_1",															"冰岛的历史是一个漫长而冒险的传奇，充满了许多转变和发现。当第一批维京人定居者在公元9世纪末抵达冰岛时，他们发现了一个无人居住的岛屿。今天的冰岛是一个彻底的现代国家——但过去的时代和他们丰富的文化遗产的证据仍然随处可见"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_2",															"我们对冰岛最早的定居者的了解主要可以追溯到Landnámabók，即 “定居书”，这是一份由五部分组成的中世纪手稿，讲述了诺森人在9世纪和10世纪发现并定居冰岛的故事。殷格·亚纳逊被认为是冰岛的第一个永久定居者，他和他的姐夫希约莱夫·赫罗兹马森一起来到了冰岛，后来在现代维克东部的希约莱夫山定居后被他的奴隶杀害。在接下来的几十年里，挪威酋长们集体追随殷格，以躲避挪威国王哈拉尔的高压统治，在大约60年的时间里，冰岛就完全被定居化了。到公元930年，人们认为这个国家的所有可耕地都已经被定居。在冰岛即将经历漫长的发展时期之前，定居点已经变得如此之大，以至于需要一个新的立法机构；因此，统治者的酋长们建立了阿尔廷自由民议会，许多人认为这是世界上最古老的全国性议会。公元930年，第一届议会的召开标志着独立共和国的开始。这段时期的治理被称为冰岛联邦（Þjóðveldið）或自由国家：“冰岛的黄金时代”。"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_3",															"930-1030年被称为“萨迦时代”，因为冰岛人萨迦中后来记录的许多事件（12和13世纪）实际上都发生在这个时期。此外，传奇中涉及的许多关键事件都发生在辛格韦德利。999年或1000年，基督教也是在辛格韦德利被接纳到冰岛的。1120年代至1230年代，伟大的写作时代，是一个文学成就斐然的时代。大多数冰岛传奇都是在这个时期写成的，还有伟大的历史著作： 在这一时期，大部分的冰岛传奇都是在这一时期写成的，还有伟大的历史作品：冰岛人之书和挪威诸王萨迦。冰岛的第一部国家历史冰岛人之书是在1130年左右由阿利·索尔基尔松（1067-1148）撰写的，他被称为智者阿利。《挪威国王史》（Heimskringla）是由斯诺里·斯图鲁森（1179-1241）撰写的。"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_4",															"1220年是“斯德龙时代”的开始。这是冰岛的一个内部冲突时期，也是冰岛作为一个独立自由国家近400年的最后时期。斯德龙家族是最有权势的家族成员；他们当中有冰岛经典传奇故事的作者。其中最著名和最伟大的是斯诺里·斯图鲁森。通过联姻和政治联盟，斯图鲁森家族统治了全国大部分地区，但其他酋长和有影响力的家族却反对他们。酋长们之间长期的争斗和权力斗争带来了经济和社会的毁灭。当时，挪威国王哈康·哈康纳森（哈康四世）正试图在冰岛扩大其影响力，作为其统一挪威维京时代所有定居点的活动的一部分。几个最伟大的冰岛酋长已经成为国王的附庸，而斯诺里·斯图鲁森由于支持哈康国王的对手斯库利伯爵而失势。1241年，在哈康国王的支持下，斯诺里·斯图鲁森在雷克霍特被杀。最终，1262-1264年，冰岛的酋长们向挪威国王哈康四世宣誓效忠，部分原因是希望他能给国家带来和平。1262年标志着冰岛联邦时期的结束。"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_5",															"在挪威王室的统治下，冰岛人开始依赖挪威船只的补给，而挪威船只经常不来。随后是一段非常艰难和荒凉的时期。冰雪经常阻挡峡湾和航线。剧烈的火山爆发、反复出现的流行病和饥荒蹂躏着整个国家。1349年，黑死病困扰着挪威，切断了所有贸易供应。1380年，挪威君主国与丹麦结盟；然而，这一变化并没有影响冰岛的地位。1397年，瑞典、挪威和丹麦组成卡尔马同盟，冰岛被置于丹麦王室的统治之下。这个国家的状况进一步恶化。冰岛酋长被丹麦皇家官员所取代。阿尔廷议会成为了一个法庭；法官由皇家官员挑选。15世纪初的1402-1404年，黑死病折磨着冰岛，使三分之一以上的人口死亡。在1540-1550年期间，根据丹麦国王的命令，路德宗被强加在冰岛，第一位路德宗主教被安置在斯考尔霍特。1550年，最后一位天主教主教约恩·阿拉松（Jón Arason）被斩首，冰岛反对宗教改革的局面结束。1602年，丹麦建立了贸易垄断，禁止冰岛与丹麦以外的任何国家进行贸易，从而引发了一个极端贫困的时期。这种垄断一直持续到1787年。丹麦王室在宪法层面上也加强了对冰岛的控制。1662年，丹麦国王拥有了世袭的权力，绝对君主制被强加在冰岛，议会的权力明显下降。18世纪是冰岛的一个人口减少、贫困加剧和自然灾害频发的悲惨时期。1703年，当冰岛进行第一次人口普查时，人口数量为50,366，大约20%的人处于贫困状态。1707年天花流行后，约有18,000人丧生。一系列的自然灾害和饥荒接踵而至，使人口在本世纪内又两次下降到远低于40000人。1755年卡特拉火山爆发，1783年发生了灾难性的拉基火山爆发，造成洪水、火山灰和有毒烟雾，随之而来的饥饿使1万人死亡。"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_6",															"1800年，阿尔廷议会被皇家法令解散，后来被最高法院取代。然而，到了19世纪中期，一种新的民族意识在冰岛复苏，约恩·西古尔德松成为冰岛独立运动的伟大领袖。1843年，阿尔廷议会作为一个协商机构被重新建立，但只有少数有权势的封建男爵和地主当选。1848年，丹麦国王腓特烈七世放弃了他的绝对权力，这也导致了冰岛在新政府形式下的地位问题。约恩·西古尔德松的立场是国王只能将其对冰岛的绝对权力统治权交还给冰岛人自己，因为他们是在1662年将其放弃给丹麦王室的人。此外，冰岛最初是作为一个自由国家与挪威君主国结盟的，根据1262-1264年的协议享有某些权利。1854年，丹麦的贸易垄断被解除，最终给予了冰岛完全的贸易自由。1855年确立了新闻自由。1874年，定居千年庆祝活动举行，丹麦国王克里斯蒂安九世访问了冰岛。他向冰岛提交了一部新的宪法，授予阿尔廷议会在内部事务中的立法权。1904年，该宪法被修订，冰岛获得了丹麦的地方自治权，第一任冰岛总理在雷克雅未克就职。"),
	("zh_Hans_CN",	"LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ICELAND_CHAPTER_HISTORY_PARA_7",															"虽然自治时期（1904-1918）的特点是经济和社会领域的进步，但冰岛争取更大自主权的斗争仍在继续。1918年12月1日，冰岛成为一个主权国家，即冰岛王国，并与丹麦国王建立了联合统治。1944年，冰岛取消了与丹麦的联盟，冰岛共和国在辛格韦德利成立。冰岛共和国的宣布标志着七个世纪的外国统治的结束。冰岛历史上的一个新纪元开始了。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SNORRI_STURLUSON_NAME",																		"斯诺里·斯图鲁森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SNORRI_STURLUSON_CHAPTER_HISTORY_PARA_1",			 				"斯诺里·斯图鲁森（1178年-1241年）是冰岛的历史学家、诗人和政治家，被认为是冰岛文学中最重要的诗人之一。他今天以两部长篇诗集（或称埃达）的作者而闻名，这两部诗集是《散文艾达》和《挪威诸王萨迦》。在《散文艾达》中，斯图鲁森讲述了北欧神话中的一些故事，同时阐述了他所讲述的每一个神话中所使用的诗词形式和文学技巧，这是一首对学习者有很大价值的指导性诗歌。《挪威诸王萨迦》是一连串比较传统的半神话式的传奇故事，讲述了北欧国王的历史。通过文体和语言学证据，斯图鲁森也被认为是《埃吉尔萨迦》的作者，这是冰岛所有传奇中最重要和最广泛阅读的一部。作为诗歌、历史和教学诗篇的作者，斯图鲁森是研究中世纪斯堪的纳维亚历史和文化的学者们最丰富的资料之一。他的作品也被普遍认为是所有冰岛诗歌中最美丽和最出色的作品之一。作为对自己时代的冰岛诗人的主要影响，斯图鲁森也影响了许多非斯堪的纳维亚作家，包括阿根廷诗人和故事作家豪尔赫·路易斯·博尔赫斯以及德国浪漫主义的一些诗人。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFLJOTR_NAME",																				"乌尔夫约特"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFLJOTR_CHAPTER_HISTORY_PARA_1",									"乌尔夫约特为冰岛带来了法律，并被一些人认为是冰岛的第一个立法者。大约在公元927-930年，乌尔夫约特被一群酋长派往挪威，研究法律和文化，并将足够的理解带回冰岛，以帮助建立冰岛的法律框架和政府形式。而当他在挪威逗留了大约三年的时间后，乌尔夫约特的同父异母的兄弟格里姆尔·盖特斯科尔对冰岛进行了调查，以寻找建立阿尔廷的最佳地点。为了纪念乌尔夫约特，Alþing制定了第一部法律《乌尔夫约特法》，并以乌尔夫约特斯瓦特湖和乌尔夫约特法律评论来纪念他。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_HRAFN_HAENGSSON_NAME",																		"赫拉芬·海格森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_HRAFN_HAENGSSON_CHAPTER_HISTORY_PARA_1",								"赫拉芬·海格森是十世纪的冰岛法学家和牧师。他是冰岛早期定居者之一凯蒂尔·海格和他的妻子英贡的儿子。赫拉芬是冰岛统一的主要负责人之一，在公元930年的第一次议会上被任命为法律讲述官。他在这个职位上一直任职到949年。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_THORGEIR_LJOSVETNINGAGODI_NAME",															"索吉尔·约斯韦特宁加戈迪"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_THORGEIR_LJOSVETNINGAGODI_CHAPTER_HISTORY_PARA_1",					"索尔格尔·约斯韦特宁加戈迪·索尔科尔松是985年至1001年冰岛议会的法律讲述官。在999年或1000年，冰岛的立法会议正在讨论他们应该信奉哪种宗教： 北欧多神教或基督教。索尔格尔本人是一名异教牧师和酋长，他在毛毯下默默沉思了一天一夜后决定支持基督教，从而避免了潜在的灾难性国内冲突。根据妥协方案，异教徒仍然可以私下进行宗教活动，一些旧的习俗也得以保留。在他做出决定后，索尔格尔本人也皈依了基督教。索尔格尔的故事被保存在阿利·索尔基尔松的冰岛人之书中。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON_NAME",																	"斯卡普蒂·索罗罗德松"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_SKAFTI_THORODDSSON_CHAPTER_HISTORY_PARA_1",							"斯卡普蒂·索罗罗德松（卒于1030年）是冰岛的一位法律发言人和吟游诗人。他于1004年成为法律讲述官，在他的叔叔格里姆尔嗓子不灵的时候接替了他。他一直任职到1030年去世，比其他任何人都长。根据冰岛人之书的说法，他通过建立 “第五法庭”，即一个全国性的上诉法庭，进行了司法改革。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_OLAFR_THORTHARSON_NAME",																	"奥拉夫·索罗尔达尔森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_OLAFR_THORTHARSON_CHAPTER_HISTORY_PARA_1",							"奥拉夫·索罗尔达尔森是冰岛的一名吟游诗人和学者，大约生于1210年，死于1259年。他通常被称为Óláfr hvítaskáld（“白诗人奥拉夫”）与Óláfr svartaskáld（“黑诗人奥拉夫”）并称。奥拉夫尔是斯诺里·斯图鲁森的侄子，他在斯诺里的家中度过了他的青年时期，在那里他接受了重要的学术教育。特别重要的是他的《语法学论》。从1252年到1256年，他是冰岛的法律讲述官。他成为著名的吟游诗人，并创作了关于斯堪的纳维亚半岛三个国王的诗歌，这些诗歌部分收录在《克尼特林列王萨迦》中，他可能是根据他在丹麦收集的材料制作的。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_STURLA_THORTHARSON_NAME",																	"斯图拉·索罗尔达尔森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_STURLA_THORTHARSON_CHAPTER_HISTORY_PARA_1",							"斯图拉·索罗尔达尔森的生活被记录在《斯德龙萨迦》中。斯图拉是冰岛酋长索尔达尔·斯图鲁森和他的情妇索罗拉的儿子，也是老斯图拉·索罗尔达尔松的孙子。他是著名传奇作家斯诺里·斯图鲁森的侄子和学生。他的兄弟是冰岛的吟游诗人和学者奥拉夫·索罗尔达尔森。斯图拉在冰岛联邦解体后的短暂时期内被任命为全冰岛的法律讲述官，并撰写了法律书籍《贾恩西达》。他最出名的是写了《冰岛人之书》，这是《斯德龙萨迦》中最长的传奇，以及《哈康萨迦》，这是挪威王哈康四世的故事。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_HAUKR_ERLENDSSON_NAME",																		"豪克·埃尔伦森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_HAUKR_ERLENDSSON_CHAPTER_HISTORY_PARA_1",							"豪库尔·埃伦德松是冰岛的法律讲述官，后来成为挪威的法律讲述官和骑士，因编纂了许多冰岛的传奇故事和其他资料而闻名，这些资料大多是他亲手编纂的，以他的名字装订成书，称为豪库尔之书。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_GUNNAR_THORGRIMSSON_NAME",													 				"冈纳尔·索格里姆松"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_GUNNAR_THORGRIMSSON_CHAPTER_HISTORY_PARA_1",							"冈纳尔“智者”·索尔格里姆森，是11世纪的冰岛法律讲述官，第一次任职是在1063-1065年间，第二次是在1075年。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_MARKUS_SKEGGJASON_NAME",													 				"马库斯·斯科吉亚森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_MARKUS_SKEGGJASON_CHAPTER_HISTORY_PARA_1",							"马库斯·斯科吉亚森是斯科吉·比约恩纳松的儿子，可能是诗人索罗拉林·斯科吉亚森的兄弟。他从1084年到1107年10月15日在冰岛担任法律讲述官。在冰岛人之书中，他被阿利·索尔基尔森从他的兄弟、父亲和祖父那里的信息推测出他是研究冰岛早期立法者生活的重要线索。马库斯似乎与教会关系密切：在他担任立法者期间，在他的指导下，斯考尔霍特的主教基祖尔·艾斯雷夫森（1081-1118）制定了I冰岛什一税法。马库斯是13世纪冰岛最受尊敬的诗人之一。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_JON_EINARSSON_NAME",														 				"约恩·艾纳尔森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_JON_EINARSSON_CHAPTER_HISTORY_PARA_1",								"约恩·艾纳尔森是13世纪冰岛的一位法律讲述官。法律书《约恩之书》就是以他的名字命名的。当斯图拉·索罗尔达尔森不再能够充分履行法律讲述官的所有职责时，约恩·艾纳尔森被安排在他身边。在冰岛主教阿尔尼于1277年秋天写给挪威国王的信中，他说，法律讲述官约恩做得很好，很有智慧，但斯图拉做得并不尽如人意。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_KETILL_THORLAKSSON_NAME",																	"凯迪尔·索尔拉克森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_KETILL_THORLAKSSON_CHAPTER_HISTORY_PARA_1",							"凯迪尔·索尔拉克森是13世纪冰岛的一位法律讲述官和牧师。凯迪尔在1259年至1262年期间担任法律顾问，并在 “旧盟约”——一项促成冰岛和挪威联合的协议——签订时担任该职务。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_STYRMIR_KARASON_NAME",														 				"斯蒂尔米尔·卡拉森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_STYRMIR_KARASON_CHAPTER_HISTORY_PARA_1",								"斯蒂尔米尔·卡拉森是一位法律讲述官、作家和富德亚尔克劳斯图的前任法律讲述官。1228年至1235年，他在雷克霍特担任斯诺里·斯图鲁森的牧师。他在1210-1214年和1232-1235年期间担任法律顾问。之后，他在1235-1245年间成为维泽伊修道院的院长。鉴于斯蒂尔米尔是雷克霍特的牧师，他很可能是斯诺里·斯图鲁森的写作和制书助手。斯蒂尔米尔在他的时代是一位著名的作家，在几本当时的书籍中都提到了他。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_GISSUR_HALLSSON_NAME",																		"吉苏尔·哈尔森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_GISSUR_HALLSSON_CHAPTER_HISTORY_PARA_1",								"吉苏尔·哈尔森是12世纪冰岛的牧师、马夫和立法者。他在1181年至1201年期间担任法律讲述官。他备受尊敬，被认为是一位伟大的学者。他写了《救饥者》，讲述了斯考尔霍特的第一批主教的故事。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_KOLBEINN_FLOSASON_NAME",																	"科尔宾·弗洛萨森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_KOLBEINN_FLOSASON_CHAPTER_HISTORY_PARA_1",							"科尔宾·弗洛萨森是1066-1071年间的冰岛法律讲述官。长期以来，对这个科尔宾是谁一直存在争议，有两个人可能是此人：来自斯维林家族的科尔宾·弗洛萨森；以及来自兰兹韦特的维利尔的弗洛西的儿子科尔宾“法律讲述官”。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_BERGTHOR_HRAFNSSON_NAME",																	"贝格索尔·赫拉夫森"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_BERGTHOR_HRAFNSSON_CHAPTER_HISTORY_PARA_1",							"贝格索尔·赫拉夫森是12世纪冰岛的一位法律讲述官。在他担任法律讲述官期间，冰岛撰写了成文法。他于1117年从乌尔夫赫丁手中接过法律讲述官的职位，并一直任职到1122年。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFHETHINN_GUNNARSSON_NAME",																"奥夫海因·冈纳松"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_ULFHETHINN_GUNNARSSON_CHAPTER_HISTORY_PARA_1",						"乌夫赫丁·冈纳尔森是12世纪的冰岛法律家。他是阿利·索尔基尔森在撰写《冰岛人之书》时的资料来源之一。"),
	("zh_Hans_CN",	"LOC_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_TEITUR_THORVALDSSON_NAME",																	"泰图尔·索瓦尔德松"),
	("zh_Hans_CN",	"LOC_PEDIA_GREATPEOPLE_PAGE_GREAT_PERSON_INDIVIDUAL_SUK_LAWSPEAKER_TEITUR_THORVALDSSON_CHAPTER_HISTORY_PARA_1",							"泰图尔·索尔瓦德森是13世纪冰岛的一位法律讲述官。他来自豪克达尔家族，是赫鲁纳劳格的索尔瓦杜尔·吉苏尔拉尔森的儿子，是吉苏尔·索尔瓦德森的同父异母兄弟。泰图尔曾被任命为牧师，住在布拉德拉通加。他在1219年至1221年以及1236年至1247年期间担任法律讲述官。据说他是一个明智的、谦逊的人。"),
	("zh_Hans_CN",	"LOC_LOADING_INFO_LEADER_SUK_INGOLFUR",																									"去冒险吧，因为世界是广阔的，充满了奇迹！遥远的土地蕴藏着巨大的机遇，也面临着巨大的困难，但请放心，你们人民的韧性和创造力将使冰岛永远向前。开拓时代已经来临，你们今天书写的故事将永远载入史册。"),
	("zh_Hans_CN",	"LOC_DIPLO_FIRST_MEET_LEADER_SUK_INGOLFUR_ANY",																							"我是殷格·亚纳逊，我代表冰岛议会欢迎你们来到我的家园。"),
	("zh_Hans_CN",	"LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_INGOLFUR_ANY",																			"我们在附近有个定居点。你应该去看看！我们不能让人们说我们冰岛人不好客！"),
	("zh_Hans_CN",	"LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_INGOLFUR_ANY",																	"是的！去看看新的地方一定很棒！"),
	("zh_Hans_CN",	"LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_INGOLFUR_ANY",																	"我们主要的定居点现在还没有很多。但是这里的温泉太棒了！这就是为什么我们叫它雷克雅未克。"),
	("zh_Hans_CN",	"LOC_DIPLO_KUDO_EXIT_LEADER_SUK_INGOLFUR_ANY",																							"生活在如此宏伟的奇观下面，会让人有强烈的探索欲望，不是吗？"),
	("zh_Hans_CN",	"LOC_DIPLO_WARNING_EXIT_LEADER_SUK_INGOLFUR_ANY",																						"你没有冒险精神吗？你不知道世界上有多少奇迹。"),
	("zh_Hans_CN",	"LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																				"我们的人民很强悍，否则他们不会在这里定居。你真的认为你的战士能与他们匹敌吗？"),
	("zh_Hans_CN",	"LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																				"我们为荣誉而战！斯卡德尔家族将为我们即将到来的战斗而歌唱和写诗！"),
	("zh_Hans_CN",	"LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_INGOLFUR_ANY",																			"我们都赢得了和平。"),
	("zh_Hans_CN",	"LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_INGOLFUR_ANY",																			"这个提议几乎是无礼的。"),
	("zh_Hans_CN",	"LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																					"我们都证明了自己的勇敢。现在是结束流血冲突的时候了。"),
	("zh_Hans_CN",	"LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																						"我的旅程就此结束。至少我的事迹将流传于传奇故事中。"),
	("zh_Hans_CN",	"LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																				"世界是残酷的。让我们像朋友一样一起面对吧。"),
	("zh_Hans_CN",	"LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																		"好，好的。"),
	("zh_Hans_CN",	"LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																		"也许下次吧。"),
	("zh_Hans_CN",	"LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																	"我衷心地接受！让我带点啤酒来庆祝一下！"),
	("zh_Hans_CN",	"LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																	"虽然我很想答应，但最好还是再等一会儿。"),
	("zh_Hans_CN",	"LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																					"我给你送去了各种各样的冰岛臭食，有羊头、鱼干、发酵鲨鱼肉，好好享受吧！"),
	("zh_Hans_CN",	"LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																		"我亲自欢迎他们来到我的家园。"),
	("zh_Hans_CN",	"LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																		"我很遗憾地说，一切都已定局。"),
	("zh_Hans_CN",	"LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																				"你要侮辱我？我保证你会为这些话后悔的。"),
	("zh_Hans_CN",	"LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																					"就连我都无法忍受你了。[NEWLINE]（谴责你）"),
	("zh_Hans_CN",	"LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																				"你愿意结成同盟吗？"),
	("zh_Hans_CN",	"LOC_DIPLO_GREETING_LEADER_SUK_INGOLFUR_ANY",																							"你好！！"),
	("zh_Hans_CN",	"LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																			"真可惜。"),
	("zh_Hans_CN",	"LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																			"太好了。"),
	("zh_Hans_CN",	"LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_INGOLFUR_ANY",																				"你能允许我们通过你的土地吗？"),
	("zh_Hans_CN",	"LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																		"为什么不呢？这片土地的奇观值得分享。"),
	("zh_Hans_CN",	"LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_INGOLFUR_ANY",																		"我很抱歉，但我不能同意。"),
	("zh_Hans_CN",	"LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_INGOLFUR_ANY",																	"你知道唯一会被军队吓倒的是羊，对吧？"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_QUOTE",																							"每个人都是自己未来的主宰。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_TITLE",																							"英格尔夫·阿尔纳尔松"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_SUK_INGOLFUR_SUBTITLE",																							"冰岛的首位挪威定居者"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_CAPSULE_BODY",																		"冰岛一同迎接全新的领土与挑战。在他们的首位挪威定居者英格尔夫的领导下，您将能安全地在更远的海岸定居。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_DETAILED_BODY",																		"冰岛是探险家与作家的文明。尽早派出侦察兵以获得历史时刻（以及 [ICON_GreatWriter] 大作家点数），并找到下一个可能的定居点。自然奇观尤其具有价值：您文明的许多区域可从自然奇观获得大量相邻加成！草屋将减轻您对淡水源的依赖，因为除了沙漠地形外，草屋可被建造在任何地方，且其能提供少量 [ICON_Food] 食物与 [ICON_Production] 生产力来帮助您的城市运转起来。尽管宣法讲师训练成本很高，但其提供了进一步的提升，让您能获得额外的忠诚度，并您在所需之处获得收益。在英格尔夫的领导下，通过忠诚度与 [ICON_GreatWriter] 大作家点数的加成，在远方的土地上立足将会更加容易。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_1",																	"根据《定居书》（一份详述北欧人在冰岛定居的中世纪手稿），殷格·亚纳逊被广泛认为是冰岛最早的定居者之一，与他的妻子哈尔维格·弗洛达尔多特和他的养兄赫约尔雷夫·哈罗德马尔森一起。作为一个挪威血统的贵族，殷格（他的名字字面意思是 “高贵的狼”）在9世纪末被迫离开中世纪早期的挪威，因为他和他的养兄参与了一场与一个强大的北欧伯爵儿子的战斗。因此，在他杀害了这位北欧伯爵的两个儿子之后，他被迫将自己的所有土地财产交给了他。在他的故乡几乎一无所有的情况下，殷格决定向西航行，以寻求更好的生活。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_2",																	"在整个870年代初的某个时候，他和他的妻子、赫约尔雷夫的家人、一些为他们服务的奴隶，以及其他任何可以打包的有价值的东西一起上了船。这些东西中包括他在冰岛附近时从船上扔下的一对石柱。因为他想住在一个由神明指示的地方，所有他认为这对石柱代表了北欧诸神的意志。因此，当这些柱子到达冰岛海岸时，英格沃尔知道他必须在那里定居。此后不久，他和他的船员们在冰岛南部海岸的英戈尔夫斯基岬角度过了他们在冰岛土地上的第一个冬天。随后，他派两个奴隶去侦察周围的情况，寻找漂流的石柱。他们在冰岛的西南海岸一直这样做，直到他们在一个有一些温泉的海湾看到它们。因此，在874年，殷格·亚纳逊被认为是冰岛首都的创始人，该城市最初被命名为雷克雅未克（或英文中的 “烟湾”），在那里建立了他的新庄园。他之所以这样命名，是因为从今天的雷克雅未克附近的温泉中冒出的 “烟雾”（实际上是蒸汽）。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_3",																	"同样必须提到的是，即使在一个相对短暂的时期内，应也是该岛西南部的合法主人，但由于他不能居住在所有的地方，他已经将他的大部分土地财产捐赠或出售给即将到来的斯堪的纳维亚殖民者，让他们参与了北欧人在冰岛的定居阶段。如今，在雷克雅未克中部一座名为亚纳霍尔的小山上，矗立着一座为纪念殷格而建立的雕像。"),
	("zh_Hans_CN",	"LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_INGOLFUR_CHAPTER_HISTORY_PARA_4",																	"然而，关于殷格在雷克雅未克建立后的命运，人们所知不多。但可以肯定的是，他的儿子索尔斯泰因长大后成为维京时代冰岛显赫的酋长，并因其在克雅尔尼斯（目前是首都的一个区）建立该国最早的议会而被人铭记。"),
	("en_US",		"LOC_UNIT_KNARR_NAME",																													"Knarr"),
	("zh_Hans_CN",	"LOC_UNIT_KNARR_NAME",																													"克纳尔长船"),
	("en_US",		"LOC_UNIT_KNARR_DESCRIPTION",																											"Iceland unique Ancient era unit that replaces the Oarlocked Rowboats, and belongs to Recon."),
	("zh_Hans_CN",	"LOC_UNIT_KNARR_DESCRIPTION",																											"冰岛特色远古海军袭击者，取代桨架划艇，属于侦查单位。");
