INSERT OR REPLACE INTO LocalizedText (Language, Tag, Text)
VALUES
	("zh_Hans_CN",		"LOC_LEADER_CVS_MASINISSA_NAME",															"马西尼萨"),
	("zh_Hans_CN",		"LOC_LEADER_CVS_DIHYA_NAME",																"蒂娅"),
--UA	

	("zh_Hans_CN",		"LOC_TRAIT_LEADER_CVS_MASINISSA_UA_NAME",													"王者典范"),
	("zh_Hans_CN",		"LOC_TRAIT_LEADER_CVS_MASINISSA_UA_DESCRIPTION",											"与每一位其他文明首次宣布友好时，双方获得一个无需消耗资源维护的轻骑兵单位。你的建造者获得等同于最高同盟等级的额外次数。马西尼萨的盟友可以训练马西尼萨的特色单位。"),
	("en_US",			"LOC_TRAIT_LEADER_CVS_MASINISSA_UA_DESCRIPTION",											"When declaring friendship with every other civilizations for the first time, both sides get a light cavalry unit without resource maintenance cost. Your builders receive extra build charge equal to the highest alliance level. Masinisa's allies can train Masinisa's unique units."),
	("zh_Hans_CN",		"LOC_UNIT_OTTOMAN_BARBARY_CORSAIR_DESCRIPTION",												"中世纪奥斯曼和柏柏尔特色海军单位，取代海盗船。进行海岸扫荡时无需花费 [ICON_Movement] 移动力。除非与单位相邻，否则只能被其他海军袭击者发现。能使视线范围中的海军袭击者暴露位置"),
	("en_US",		"LOC_UNIT_OTTOMAN_BARBARY_CORSAIR_DESCRIPTION",													"Ottoman and Berbers unique Medieval era naval unit that replaces the Pirate Ship. It costs no [ICON_Movement] Movement to coastal raid. Can only be seen by other Naval Raiders unless adjacent to them. Reveals Naval Raiders within sight range."),
	("zh_Hans_CN", "LOC_ABILITY_HD_CVS_MASINISSA_GRANT_LIGHTCAVARLY_WITHOUT_RESOURCE_COST_DESCRIPTION",	"{LOC_TRAIT_LEADER_CVS_MASINISSA_UA_NAME}：无需消耗资源维护。"),
	("en_US", "LOC_ABILITY_HD_CVS_MASINISSA_GRANT_LIGHTCAVARLY_WITHOUT_RESOURCE_COST_DESCRIPTION",	"{LOC_TRAIT_LEADER_CVS_MASINISSA_UA_NAME}: No resource cost."),

	("zh_Hans_CN",		"LOC_UNIT_CVS_MASINISSA_UU_NAME",															"努米底亚骑兵"),
	("zh_Hans_CN",		"LOC_UNIT_CVS_MASINISSA_UU_DESCRIPTION",													"柏柏尔特色轻骑兵单位，造价更低，从每个同盟获得+2[ICON_Strength]战斗力。"),
	("en_US",			"LOC_UNIT_CVS_MASINISSA_UU_DESCRIPTION",													"A light cavalry unit unique to Masinissa and his Friends.Cheaper than the Horseman it replaces,+2[ICON_Strength] Strength for every alliance."),

	("zh_Hans_CN",		"LOC_ABILITY_CVS_MASINISSA_UU_DESCRIPTION",													"从每个同盟获得+2[ICON_Strength]战斗力。"),
	("en_US",			"LOC_ABILITY_CVS_MASINISSA_UU_DESCRIPTION",													"+2[ICON_Strength] Strength for every alliance"),

	("zh_Hans_CN",		"LOC_AGENDA_CVS_MASINISSA_NAME",															"努米底亚之主"),
	("zh_Hans_CN",		"LOC_AGENDA_CVS_MASINISSA_DESCRIPTION",														"喜欢外大陆的人口众多的文明，不喜欢在他家乡大陆上收入高的文明。"),
	("zh_Hans_CN",		"LOC_DIPLO_KUDO_LEADER_CVS_MASINISSA_REASON_ANY",											"你是外大陆上的强权。"),
	("zh_Hans_CN",		"LOC_DIPLO_MODIFIER_CVS_MASINISSA_HAPPY",													"马西尼萨对您的大都市印象深刻"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_LEADER_CVS_MASINISSA_REASON_ANY",										"您在他的大陆上收入颇丰。"),
	("zh_Hans_CN",		"LOC_DIPLO_MODIFIER_CVS_MASINISSA_UNHAPPY",													"马西尼萨对一个富裕的近在咫尺的强权颇为担忧"),
	("zh_Hans_CN",		"LOC_LOADING_INFO_LEADER_CVS_MASINISSA",													"万岁，马西尼萨！您是马西里之主和努米底亚的统一者。您打碎了迦太基人的桎梏，使努米底亚跃升为强权，将荒野开垦为沃土。别让桂冠使您踌躇不前，因为您还有伟业要去成就，有功绩要去书写。前进吧，让您的努米底亚王国屹立不倒！"),
	("zh_Hans_CN",		"LOC_DIPLO_FIRST_MEET_LEADER_CVS_MASINISSA_ANY",											"您好，客人，我是马西尼萨，马西里与努米底亚之王。如果您以赤诚之心待我，我将成为您忠实的挚友。"),
	("zh_Hans_CN",		"LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_CVS_MASINISSA_ANY",							"努米底亚的花园正值花季，您的使者愿意来一次私人拜访吗？"),
	("zh_Hans_CN",		"LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_CVS_MASINISSA_ANY",					"真是最慷慨的邀请啊。谢谢您，朋友。"),
	("zh_Hans_CN",		"LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_CVS_MASINISSA_ANY",						"告诉我，朋友：如果我想在以后的时间里继续和你谈话，我在哪里可以找到你？当然，伟大的努米底亚的首都也会对你的信使开放。"),
	("zh_Hans_CN",		"LOC_DIPLO_GREETING_LEADER_CVS_MASINISSA_HAPPY",											"问候您，朋友，今天有什么事？"),
	("zh_Hans_CN",		"LOC_DIPLO_GREETING_LEADER_CVS_MASINISSA_UNHAPPY",											"说吧。"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",							"别担心，我的朋友！ 您的使者将得到最大的尊重。我期待着从他们那里听到更多关于你和你的人民的消息。"),

	("zh_Hans_CN",		"LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",							"努米底亚大门不对不友好的人开放。"),
	("zh_Hans_CN",		"LOC_DIPLO_DELEGATION_FROM_AI_LEADER_CVS_MASINISSA_ANY",									"相信我们早就应该正式建立我们的关系了。我已经派出了一个代表团，带着使者前往你那里商讨细节问题，还有一匹珍贵的柏布马作为礼物送给你。如果我们的关系继续改善，我相信你会发现有更多的马供你使用。"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",						"是的，当然！ 如果他们不来拜访，有朋友的意义何在？"),
	("zh_Hans_CN",		"LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",						"你不是努米底亚的朋友。你不应该进入这些土地。"),
	("zh_Hans_CN",		"LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_CVS_MASINISSA_ANY",									"朋友，你好。我们的国家仍然彼此封闭。让我们结束这种可悲的状态，让我们的人民自由自在地漫游！"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",						"好吧，我以前就已经把你当作朋友了，但我很高兴能把它正式化。"),
	("zh_Hans_CN",		"LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",						"我不能接受。我一眼就能看出虚伪的朋友。"),
	("zh_Hans_CN",		"LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_CVS_MASINISSA_ANY",								"亲爱的朋友，我希望公布我们的亲密关系。让我们宣布我们心意相通，密不可分！"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_CVS_MASINISSA_ANY",							"谢谢，朋友。我的心也莫大地温暖了。"),
	("zh_Hans_CN",		"LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_CVS_MASINISSA_ANY",							"也许下次吧。"),
	("zh_Hans_CN",		"LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_CVS_MASINISSA_ANY",									"让我们用更强的约束力来加强我们的友谊：军事与文书。一个联盟将为我们两国人民带来巨大的利益，你同意吗？"),
	("zh_Hans_CN",		"LOC_DIPLO_KUDO_EXIT_LEADER_CVS_MASINISSA_ANY",												"您将您的国家开发成了沃土。我们可以缔结一个忠实的同盟。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_EXIT_LEADER_CVS_MASINISSA_ANY",											"尽管你在经济上占主导地位，但努米底亚绝不会向你低头。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_CVS_MASINISSA_UNHAPPY",					"不幸的是，你们在我们边界附近的军队使我的人民感到紧张。请撤走他们。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_CVS_MASINISSA_HAPPY","抱歉，朋友，我将驱使他们离开。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_CVS_MASINISSA_UNHAPPY","我的人民是惯于随心所欲自由漫游的民族。但我会要求他们暂时离开你的土地。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_CVS_MASINISSA_ANY",	"啊，是的。当然，他们将进入你们的城市，你们的农田。努米底亚的军队正向战争进发"),

	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_CVS_MASINISSA_HAPPY",						"这些是努米底亚的土地，朋友。请不要把它们作为你自己的土地。!"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_CVS_MASINISSA_UNHAPPY",					"我警告你：阿玛济格人将夺回他们的一切领地。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_CVS_MASINISSA_HAPPY",	"抱歉，朋友。我不知道您已经宣称这片土地了。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_CVS_MASINISSA_UNHAPPY",	"虽然这块土地的所有权仍然是个问题，但我们不应进一步激化这种局面。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_CVS_MASINISSA_HAPPY",	"来吧，朋友，这片土地当然够我们两个共享。"),
	("zh_Hans_CN",		"LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_CVS_MASINISSA_UNHAPPY",	"土地没有主人，只有用武力保卫它的人。"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_CVS_MASINISSA_HAPPY",							"好得很。"),
	("zh_Hans_CN",		"LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_CVS_MASINISSA_UNHAPPY",							"我想这是必须要做的。"),

	("zh_Hans_CN",		"LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CVS_MASINISSA_HAPPY",							"来吧，朋友，认真点！"),
	("zh_Hans_CN",		"LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_CVS_MASINISSA_UNHAPPY",							"不要继续用这种胡言乱语浪费我的时间。"),
	("zh_Hans_CN",		"LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",									"你可能觉得我是因弱小而注重友谊。那你就这么以为吧，很快你就会知错了……"),
	("zh_Hans_CN",		"LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_CVS_MASINISSA_ANY",										"让大家都知道：你的任何仇敌肯定是我的朋友。(谴责你)"),
	("zh_Hans_CN",		"LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",								"事情本不必至于此，但是现在你选择了暴力，你将被粉碎，消失在沙尘中。"),
	("zh_Hans_CN",		"LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_CVS_MASINISSA_ANY",									"作为国王，我的职责是为努米底亚和我的人民尽力而为。你挡住我的道路——所以你要做好准备：我的骑兵正要前去铺平道路。"),
	("zh_Hans_CN",		"LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_CVS_MASINISSA_ANY",								"最后，和平归来了。"),
	("zh_Hans_CN",		"LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_CVS_MASINISSA_ANY",								"这只会持续到你的恶行结束为止。"),
	("zh_Hans_CN",		"LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_CVS_MASINISSA_ANY",									"在这样的环境中，花朵都无法生长。来吧，让我们实现和平——为了我们两个国家的利益。"),

	("zh_Hans_CN",		"LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CVS_MASINISSA_ANY",										"我的努米底亚，消失了... ...它的花园被烧毁，它的人民被屠戮，它的高塔被推翻... ...你在这里的所作所为如同恶魔所为。"),
	("zh_Hans_CN",		"LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_CVS_MASINISSA_ANY",										"{LOC_DIPLO_DEFEAT_FROM_AI_LEADER_CVS_MASINISSA_ANY}"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_CVS_MASINISSA_QUOTE",												"为了一朵玫瑰，园丁成了一千个灵魂的仆人。"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_CVS_MASINISSA_TITLE",												"马西尼萨"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_CVS_MASINISSA_SUBTITLE",											"努米底亚国王"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_LEADER_CVS_MASINISSA_CHAPTER_CAPSULE_BODY",							"马西尼萨是一个理想的朋友，他为那些与他宣称有友谊的人提供恩惠，这些恩惠可以用于和平发展或快速袭击邻居。"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_LEADER_CVS_MASINISSA_CHAPTER_DETAILED_BODY",						"马西尼萨出生于公元前238年左右，是马西l里人的国王盖亚的儿子，也是迦太基的盟友。马西尼萨本人在迦太基人城长大，在第二次布匿战争期间与迦太基人并肩作战。17岁时，他率领部队取得了成功，以至于他与迦太基将军哈斯德鲁巴·吉斯戈的女儿索福尼斯巴订了婚。他继续为迦太基作战，在西班牙与大西庇阿发生冲突。虽然他在那里取得了几次胜利，但他无法阻止大西庇阿在伊利帕的胜利，导致迦太基失去了对此地的控制。"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_LEADER_CVS_MASINISSA_CHAPTER_HISTORY_PARA_1",						"在这场战争中，马西尼萨的父亲去世了，引发了马西尼萨和他的兄弟奥扎尔塞斯之间的权力斗争。由于敌对的马萨伊里王国在西帕克斯的领导下，趁着混乱，迦太基似乎在后退，马西尼萨得出结论，罗马是胜利的一方。北非的联盟很快发生了变化，两个柏柏尔王国转换了立场，西法克斯支持迦太基，马西尼萨则与罗马并肩作战。尽管马西尼萨在与西法克斯的军队作战时很吃力，但他还是与西庇阿联手，参加了公元前203年大平原战役的胜利。他追击西f法克斯到锡尔塔，并抓住了他，最后与索福尼斯巴结婚。然而，他们的结合是短暂的，因为西庇阿要求用铁链把她带到罗马。为了挽救她这一可耻的命运，马西尼萨给她送去了毒药，让她按自己的意愿j解脱。然而，战争仍在继续，最终马西尼萨在扎马战役中发挥了关键作用，粉碎了迦太基人的胜利。公元前201年签署的和平条约，将严重削弱曾经伟大的迦太基帝国。它还为马西尼萨的新王国努米底亚的建立铺平了道路。"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_LEADER_CVS_MASINISSA_CHAPTER_HISTORY_PARA_2",						"马西尼萨——在罗马人的支持下——建立了希尔塔作为他的首都，并迅速开始统一他的王国，其中包括马西里和马萨西里的土地。他还努力引进改进的农业技术，加强他的王国的城市建设，把努米底亚变成一个名副其实的粮仓。与此同时，他继续探寻迦太基的弱点，寻求扩张。虽然他从未能将自己的领地扩展到迦太基，但他与迦太基人的冲突在公元前149年引发了第三次布匿战争，罗马人摧毁了迦太基城。虽然马西尼萨没有参与这场战争，但据说他一直亲自带领军队，直到公元前148年去世。"),
	("zh_Hans_CN",		"LOC_PEDIA_LEADERS_PAGE_LEADER_CVS_MASINISSA_CHAPTER_HISTORY_PARA_3",						"他死后，马西尼萨的儿子米西斯帕将继承他的位置，努米底亚王国将一直延续到100年后被罗马人吞并。在他同时代的人中，马西尼萨被认为是一个坚定的盟友、有能力的统治者和娴熟的将军。希腊历史学家b波里比阿称他为 “我们这个时代所有国王中最好的人”。在现代，他被许多柏柏尔人视为祖先，是北非人民力量和文化的流行标志。"),
	("zh_Hans_CN",		"LOC_PEDIA_UNITS_PAGE_UNIT_CVS_MASINISSA_UU_CHAPTER_HISTORY_PARA_1",						"被普林尼描述为 “今为止非洲最好的骑兵”迄的努米底亚骑兵是战场上一支强大的力量，以至于迦太基人和罗马人都使用他们。骑兵们骑着小而快的马，没有马鞍，只用盾牌或皮肤来防御，用标枪和短剑来进攻。这使他们成为骚扰敌军的理想选择，在战斗中冲进冲出，骚扰和分散对手的注意力而不被击中。");
	